### ISSUE TITLE
Docker build: Error: EACCES: permission denied

### ISSUE THREAD

**Issue by BorntraegerMarc** [remy/nodemon#1014]
When I run my NodeJS app in a docker container (which uses nodemon) I get the following error:
```
/home/app/node_modules/mkdirp/index.js:90

Error: EACCES: permission denied, mkdir '/home/app/.config'
komed-app      |     at Error (native)
komed-app      |     at Object.fs.mkdirSync (fs.js:922:18)
komed-app      |     at sync (/home/app/node_modules/mkdirp/index.js:71:13)
komed-app      |     at Function.sync (/home/app/node_modules/mkdirp/index.js:77:24)
komed-app      |     at Object.get (/home/app/node_modules/nodemon/node_modules/configstore/index.js:38:13)
komed-app      |     at Object.Configstore (/home/app/node_modules/nodemon/node_modules/configstore/index.js:27:44)
komed-app      |     at new UpdateNotifier (/home/app/node_modules/nodemon/node_modules/update-notifier/index.js:34:17)
komed-app      |     at module.exports (/home/app/node_modules/nodemon/node_modules/update-notifier/index.js:123:23)
komed-app      |     at Object.<anonymous> (/home/app/node_modules/nodemon/bin/nodemon.js:15:27)
komed-app      |     at Module._compile (module.js:570:32)
```

My Dockerfile:
```
FROM node:6.9.2-alpine

RUN addgroup -g 997 -S app \
&& adduser -G app -u 998 -D -S app

ENV HOME=/home/app

RUN mkdir -p $HOME \
&& mkdir -p $HOME/.config
RUN chown -R app:app $HOME

USER app
WORKDIR $HOME/

VOLUME ["/home/app/uploads"]

EXPOSE 8000

CMD [ "npm", "run", "start" ]
```
The weird thing is that I already execute `chown -R app:app` in my build... Any ideas?

**Comment by BorntraegerMarc** [comment]
@remy any update to this? :)

**Comment by remy** [comment]
You can't write the update file. Change the write perms, or run as root, or, and *i think* use `--no-update`

**Comment by BorntraegerMarc** [comment]
@remy I tried to change the write perms but it seems not to take any effect when launching nodemon.
See the line `RUN chown -R app:app $HOME` in my Dockerfile. This should take care of the permissions but seems to take no effect... Or am I missing something?

**Comment by BorntraegerMarc** [comment]
And do you mean the nodemon option `--no-update`?

**Comment by BorntraegerMarc** [comment]
@remy To specify: I only have this issue on linux

**Comment by remy** [comment]
Can you raise the issue against update-notifer? https://github.com/yeoman/update-notifier

**Comment by BorntraegerMarc** [comment]
Done. thx!

**Comment by remy** [comment]
👍
