### ISSUE TITLE
Nodemon not working on Node v0.10.48

### ISSUE THREAD

**Issue by matheuslc** [remy/nodemon#1016]
We are using nodemon with node version 0.10.48 and today nodemon stopped working and started throw this error:

```bash
TypeError: Not an integer
    at Object.fs.writeSync (fs.js:540:18)
    at Function.writeFileSync [as sync] (/usr/local/lib/node_modules/nodemon/node_modules/update-notifier/node_modules/configstore/node_modules/write-file-atomic/index.js:114:10)
    at Object.create.all.set (/usr/local/lib/node_modules/nodemon/node_modules/update-notifier/node_modules/configstore/index.js:62:21)
    at Object.Configstore (/usr/local/lib/node_modules/nodemon/node_modules/update-notifier/node_modules/configstore/index.js:27:11)
    at new UpdateNotifier (/usr/local/lib/node_modules/nodemon/node_modules/update-notifier/index.js:34:17)
    at module.exports (/usr/local/lib/node_modules/nodemon/node_modules/update-notifier/index.js:123:23)
    at Object.<anonymous> (/usr/local/lib/node_modules/nodemon/bin/nodemon.js:15:27)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
```

Anyone knows how can I fix it?

**Comment by Matt007** [comment]
same here - same version - same error

**Comment by matheuslc** [comment]
Just for info: v6.9.0 works

**Comment by okv** [comment]
Same here, looks like the problem only with fresh install on older versions of node.js
Seems like some new version of dependency (update-notifier?) is not working on old node.

**Comment by matheuslc** [comment]
Guys, I found the problem.

The issue is on: bin/nodemon.js on update-notifier library.

I don't have time now to debug more and found the real problem, so, I remove it and when I have some time I will try to fix it properly.

If anyone wants to use my fix: https://github.com/matheuslc/nodemon
