### ISSUE TITLE
output from trying to rs then ctrl+c

### ISSUE THREAD

**Issue by mmclau14** [remy/nodemon#1038]
```cwd: /home/michaelmclaughlin/cloud-compiler/editor
OS: linux x64
--------------
{ run: false,
  system: 
   { cwd: '/home/michaelmclaughlin/cloud-compiler/editor',
     useFind: true,
     useWatch: false,
     useWatchFile: false },
  required: false,
  dirs: [ '/home/michaelmclaughlin/cloud-compiler/editor' ],
  timeout: 1000,
  options: 
   { ignore: [ 'public/', 'node_modules/', re: /public\/|node_modules\// ],
     dump: true,
     watch: [ '*.*', re: /.*\..*/ ],
     restartable: 'rs',
     execMap: { py: 'python', rb: 'ruby' },
     stdin: true,
     verbose: false,
     stdout: true,
     execOptions: 
      { script: './bin/www',
        exec: 'node',
        args: [],
        scriptPosition: 0,
        nodeArgs: undefined,
        ext: 'js',
        env: {},
        execArgs: [] },
     monitor: 
      [ '*.*',
        '!/home/michaelmclaughlin/cloud-compiler/editor/public/**/*',
        '!/home/michaelmclaughlin/cloud-compiler/editor/node_modules/**/*' ] },
  load: [Function],
  reset: [Function: reset],
  lastStarted: 0,
  loaded: [],
  command: 
   { raw: { executable: 'node', args: [ './bin/www' ] },
     string: 'node ./bin/www' },
  offset: 0 }
```

**Comment by mmclau14** [comment]
I get the following when updating to 1.11.0
```
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at exports._errnoException (util.js:1022:11)
    at Pipe.onread (net.js:572:26)
^C
```

**Comment by passabilities** [comment]
I get this message when using `nodemon` as a required module after I `ctrl+c` out of the process.

```
 ❯ events.js:161
      throw er; // Unhandled 'error' event
      ^

Error: read EIO
```

**Comment by linrz** [comment]
nodemon 1.17.5，after ctrl+c ，any keypress will trigger this error.
```
throw er; // Unhandled 'error' event
      ^

Error: read EIO
    at _errnoException (util.js:1022:11)
    at TTY.onread (net.js:628:25)
```
