### ISSUE TITLE
Cannot start the nodemon !!!

### ISSUE THREAD

**Issue by Sharmilee10895** [remy/nodemon#1056]
[nodemon] 1.11.0
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node index.js`
util.js:1050

Error: spawn cmd ENOENT
    at exports._errnoException (util.js:1050:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:367:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)

dont know how to solve...

**Comment by Petr73ru** [comment]
#913
