### ISSUE TITLE
how to auto clear console with restart?

### ISSUE THREAD

**Issue by MegaUITeam** [remy/nodemon#1081]
how to auto clear console with restart?

**Comment by remy** [comment]
Put it in your nodemon script or when your application starts. i.e. this on a mac:

```json
{
  "events": {
    "restart": "clear && printf '\e[3J'"
  }
```

**Comment by zhenyulin** [comment]
@remy I'm getting error 

```
SyntaxError: Unexpected token e in JSON at position 50
    at JSON.parse (<anonymous>)
```
with the escape character, is a good way to fix it?

**Comment by remy** [comment]
I don't know what the content of your nodemon.json file is though…

**Comment by zhenyulin** [comment]
@remy ah, here's my `nodemon.json` and the sublime json plugin reported invalid json:
```
{
  "events": {
    "restart": "clear && printf '\e[3J'"
  }
}
```
```
yarn run v1.3.2
$ nodemon --watch src -q --exec 'eslint src --fix'
SyntaxError: Unexpected token e in JSON at position 50
    at JSON.parse (<anonymous>)
    at /Users/zhenyulin/Desktop/ft-packages/n-event-logger/node_modules/nodemon/lib/config/load.js:196:23
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)
[nodemon] Failed to parse config /Users/zhenyulin/Desktop/ft-packages/n-event-logger/nodemon.json
error Command failed with exit code 1.
```
on `nodemon@1.14.11`
