### ISSUE TITLE
exception in nodemon killing node Error: Cannot find module 'internal/fs'

### ISSUE THREAD

**Issue by riyastk** [remy/nodemon#1087]
exception in nodemon killing node
Error: Cannot find module 'internal/fs'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at evalmachine.<anonymous>:18:20
    at Object.<anonymous> (/usr/lib/node_modules/nodemon/node_modules/update-notifier/node_modules/configstore/node_modules/graceful-fs/fs.js:11:1)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)

Node version 7.10.1
npm version 4.2.0
yarn version 0.23.3

**Comment by remy** [comment]
Can you try nodemon @ 1.12.0 - it bumped all the deps (and this error looks to be coming from configstore rather than nodemon).
