### ISSUE TITLE
Why nodemon command run twice ?

### ISSUE THREAD

**Issue by Jackclarify** [remy/nodemon#1094]
I want to run a gulp task, capture the stdout of 'Completed 'and then run the command again with the args 'report', but the nodemon run the script twice, what's the matter? Anyone can help? 
```
gulp.task('report', ['clean-build-app-dev', 'validate-devserver-scripts'], function(){
    // start nodemon to load test.js
    plugins.nodemon({ script: 'server/server.js', ext: 'js', args:['--ignore', 'test/'], env: { NODE_ENV: 'development' } })
        .on('start', function () {
            plugins.nodemon({ script: 'test/phantomFlow/test/test.js', args:['--delay', '2.5', '--ignore', 'test/'], stdout: false })
            .on('readable', function() {
                this.stdout.on('data', function(chunk) {
                    if (/Completed /.test(chunk)) {
                        plugins.nodemon({ script: 'test/phantomFlow/test/test.js', args:['report', '--delay', '2', '--ignore', 'test/'] });
                    }
                    process.stdout.write(chunk);
                });
                this.stderr.pipe(process.stderr);
            });
        });
});
```

the error code is below:
```
[nodemon] starting `node test/phantomFlow/test/test.js --delay 2.5 --ignore test/`
[nodemon] starting `node test/phantomFlow/test/test.js --delay 2.5 --ignore test/`
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::9001
    at Object.exports._errnoException (util.js:1026:11)
    at exports._exceptionWithHostPort (util.js:1049:20)
    at Server._listen2 (net.js:1257:14)
    at listen (net.js:1293:10)
    at Server.listen (net.js:1389:5)
    at Function.app.listen (C:\workspace\deleteme_0420\carepilot-web\test\phantomFlow\node_modules\connect\lib\proto.js:232:24)
    at Object.<anonymous> (C:\workspace\deleteme_0420\carepilot-web\test\phantomFlow\test\test.js:46:4)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
[17:55:41] [nodemon] app crashed - waiting for file changes before starting...

```
Can anyone help me ? Thanks

Edit:
I use 'exec' or 'spawn' to instant it here, it is work: 
```
 if (/Completed /.test(chunk)) {
                        plugins.nodemon({ script: 'test/phantomFlow/test/test.js', args:['report', '--delay', '2', '--ignore', 'test/'] });
```
==>
```
   if (/Completed /.test(data)) {
                        // plugins.nodemon({ script: 'test/phantomFlow/test/test.js', args:['report', '--delay', '2', '--ignore', 'test/'] });
                        // const { exec } = require('child_process');
                        // exec('node test/phantomFlow/test/test.js report', ['--delay', '2', '--ignore', 'test/']);
                        innerls = spawn('node', ['test/phantomFlow/test/test.js', 'report']);
                    }
```

**Comment by remy** [comment]
Can you try with nodemon@1.12.1 - this includes a windows fix.

**Comment by Jackclarify** [comment]
I'm sorry I forget to add the nodemon  version, I use the  "gulp-nodemon": "^2.0.6", but I have solve it in the edited section. Thank you @remy !

**Comment by remy** [comment]
Ok, sounds like I can close this then. 👍

**Comment by Halt001** [comment]
I'm seeing this exact same behavior and I'm on v1.12.1 (on Windows). The strange thing is that one of the 2 processes doesn't log to the console so it isn't immediately clear what happens. Can I somehow let nodemon output that it is starting a process?

**Comment by Anas-Alhariri** [comment]
In my case, I was writing to json file, and noticed later on that nodemon watches the following file types (js,mjs,json):
❯ nodemon app.js
[nodemon] 2.0.16
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,mjs,json


Therefore, it runs twice..... specially with Async file read from fs module.
