### ISSUE TITLE
nodemon suddenly doesn't work in VSCode, throws exceptions with paths everywhere

### ISSUE THREAD

**Issue by Dids** [remy/nodemon#1121]
Example exception:

```
Error: EEXIST: file already exists, mkdir '/Users/dids/.config/configstore'
    at Error (native)
    at Object.fs.mkdirSync (fs.js:924:18)
    at make (/Users/dids/Work/NodeJS/tyomaarain-realm/node_modules/make-dir/index.js:59:12)
    at Function.module.exports.sync (/Users/dids/Work/NodeJS/tyomaarain-realm/node_modules/make-dir/index.js:82:9)
    at Configstore.set all [as all] (/Users/dids/Work/NodeJS/tyomaarain-realm/node_modules/configstore/index.js:54:12)
    at new Configstore (/Users/dids/Work/NodeJS/tyomaarain-realm/node_modules/configstore/index.js:25:12)
    at new UpdateNotifier (/Users/dids/Work/NodeJS/tyomaarain-realm/node_modules/update-notifier/index.js:45:19)
    at module.exports.options (/Users/dids/Work/NodeJS/tyomaarain-realm/node_modules/update-notifier/index.js:146:25)
    at Object.<anonymous> (/Users/dids/Work/NodeJS/tyomaarain-realm/node_modules/nodemon/bin/nodemon.js:15:27)
    at Module._compile (module.js:570:32)
```

Note that I haven't actually updated nodemon or any other npm dependency when this started happening, and I don't believe VSCode itself updated either, so I'm not sure which to blame here.

Running `nodemon` from the command line works as expected, but never from within VSCode, so I'm _assuming_ it's a permission issue somewhere, but not sure why since it worked the last time I tried it (a few days ago).

Here's my VSCode launch.json:

```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "Launch Program",
            "program": "${workspaceFolder}/node_modules/nodemon/bin/nodemon.js",
            "args": ["${workspaceFolder}/src/server.js"],
            "cwd": "${workspaceFolder}",
            "runtimeArgs": ["--nolazy"],
            "preLaunchTask": "incrementVersionNumberPatch",
            "internalConsoleOptions": "openOnSessionStart"
        }
    ]
}
```

**Comment by Dids** [comment]
I previously used the following arguments in launch.json:

```
"args": ["--ext", "js,pug", "${workspaceFolder}/src/server.js"],
```

Which actually throws an even more obscure exception (thinks --ext is a file?):

```
Error: ENOENT: no such file or directory, stat '--ext'
    at Error (native)
    at fs.existsSync (fs.js:266:13)
    at parse (/Users/dids/Work/NodeJS/tyomaarain-realm/node_modules/nodemon/lib/cli/parse.js:53:30)
    at Object.parse (/Users/dids/Work/NodeJS/tyomaarain-realm/node_modules/nodemon/lib/cli/index.js:47:12)
    at Object.<anonymous> (/Users/dids/Work/NodeJS/tyomaarain-realm/node_modules/nodemon/bin/nodemon.js:5:19)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
```

If it helps, here's the command VSCode generates and runs:

```
/usr/local/bin/node --debug-brk=11286 --nolazy node_modules/nodemon/bin/nodemon.js --ext js,pug /Users/dids/Work/NodeJS/tyomaarain-realm/src/server.js 
```

**Comment by remy** [comment]
Can you confirm nodemon version? 

It looks like it's not parsing the arguments correctly - though, can you move `--debug-brk` and `--nolazy` after the nodemon.js script? It might make a difference.
