### ISSUE TITLE
[nodemon] app crashed - waiting for file changes before starting...

### ISSUE THREAD

**Issue by Boussarhane** [remy/nodemon#1132]
I get this problem when save my files. I have two file User.js and server.js

User.js
```
var mongoose = require('mongoose');
module.exports = mongoose.model('User', {
   email : string,
   pwd: string
});
```
server.js
```
var User = require('./models/User.js')

app.post('/register', (req,res) => {
    userData = req.body;
    var user = new User(userData);

    user.save((err, result) => {
        if(err) console.log('IL Y A UNE ERREUR')
        res.sendStatus(200);
    })
    
})

mongoose.connect('mongodb://log:pwd@ds267205.mlab.com:61755/social', { useMongoClient: true } , (erreur) => {
    if(!erreur) 
    console.log('Connexion etablie')
})
```

When I execute nodemon server.js I get this error :

D:\Bureau\MEAN\appBackend\models\User.js:5
   email : string,
           ^

ReferenceError: string is not defined
    at Object.<anonymous> (D:\Bureau\MEAN\appBackend\models\User.js:5:12)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (D:\Bureau\MEAN\appBackend\server.js:6:12)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
[nodemon] app crashed - waiting for file changes before starting...

**Comment by remy** [comment]
Nothing to do with nodemon. `string` is not an object. You need title case.
