### ISSUE TITLE
Unexpected token > in lib/config/exec.js:159 (.map(ext => ext.replace(/^\./, ''))) with v1.12.3 onwards

### ISSUE THREAD

**Issue by VinZ1A** [remy/nodemon#1143]
- `nodemon -v`: 1.12.3 to 1.12.5
- `node -v`: v0.10.47 
- npm : 3.10.10
- Command you ran:
npm run watch

### Expected behaviour
Compiling & Running the server

### Actual behaviour
> myProject@0.0.5 watch /Users/userName/myProject/xxxxxx
> NODE_ENV=local gulp watch

/Users/userName/myProject/node_modules/nodemon/lib/config/exec.js:161
    .map(ext => ext.replace(/^\./, ''))
              ^
SyntaxError: Unexpected token >
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/userName/myProject/node_modules/nodemon/lib/config/load.js:8:12)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)

### Steps to reproduce
just run npm install, nodemon is pulled by one of our internal library.

Problems is resolved by using nodemon 1.11.0 instead but I am not sure yet whether that would have any other side effects (incompatibilities issues...).
---

If applicable, please append the `--dump` flag on your command and include the output here **ensuring to remove any sensitive/personal details or tokens.

**Comment by remy** [comment]
Node 6 as a minimum is required. Node 0.10 isn't supported (by the node project) and includes open security vulns (also why nodemon is moving forward with LTS).

The solution is to upgrade node to (minimum) LTS
