### ISSUE TITLE
change files, but not restart at v1.12.7

### ISSUE THREAD

**Issue by zythum** [remy/nodemon#1162]
- `nodemon -v`: v1.12.7
- `node -v`: v6.2.2
- Command you ran:

change files, but not restart.

enter command 'rs' got error: 

```
/Users/zhuyi/Workspace/Lianjia/bucky-core/node_modules/nodemon/lib/monitor/run.js:241
              child.stdin.end();
                         ^

TypeError: Cannot read property 'end' of null
    at ChildProcess.<anonymous> (/Users/zhuyi/Workspace/Lianjia/bucky-core/node_modules/nodemon/lib/monitor/run.js:241:26)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:852:16)
    at Socket.<anonymous> (internal/child_process.js:323:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:492:12)
```

`v1.12.6` got the same error.
`v1.12.5` is good.

---

If applicable, please append the `--dump` flag on your command and include the output here **ensuring to remove any sensitive/personal details or tokens.

--------------

```

node: v6.2.2
nodemon: 1.12.7
command: /usr/local/bin/node /Users/zhuyi/Workspace/Lianjia/bucky-core/node_modules/.bin/nodemon --dump ./example/index.js
cwd: /Users/zhuyi/Workspace/Lianjia/bucky-core
OS: darwin x64
--------------
{ run: false,
  system: { cwd: '/Users/zhuyi/Workspace/Lianjia/bucky-core' },
  required: false,
  dirs: [ '/Users/zhuyi/Workspace/Lianjia/bucky-core' ],
  timeout: 1000,
  options:
   { dump: true,
     ignore:
      [ '.git',
        '.nyc_output',
        '.sass-cache',
        'bower_components',
        'coverage',
        'node_modules',
        re: /\.git|\.nyc_output|\.sass\-cache|bower_components|coverage|node_modules/ ],
     watch: [ '*.*', re: /.*\..*/ ],
     ignoreRoot:
      [ '.git',
        '.nyc_output',
        '.sass-cache',
        'bower_components',
        'coverage',
        'node_modules' ],
     restartable: 'rs',
     colours: true,
     execMap: { py: 'python', rb: 'ruby' },
     stdin: true,
     runOnChangeOnly: false,
     verbose: false,
     stdout: true,
     watchOptions: {},
     execOptions:
      { script: './example/index.js',
        exec: 'node',
        args: [],
        scriptPosition: 0,
        nodeArgs: undefined,
        execArgs: [],
        ext: 'js,json',
        env: {} },
     monitor:
      [ '*.*',
        '!/Users/zhuyi/Workspace/Lianjia/bucky-core/.git/**/*',
        '!.nyc_output',
        '!.sass-cache',
        '!bower_components',
        '!coverage',
        '!/Users/zhuyi/Workspace/Lianjia/bucky-core/node_modules/**/*' ] },
  signal: 'SIGUSR2',
  load: [Function],
  reset: [Function: reset],
  lastStarted: 0,
  loaded: [ '/Users/zhuyi/Workspace/Lianjia/bucky-core/package.json' ],
  watchInterval: null,
  command:
   { raw: { executable: 'node', args: [ './example/index.js' ] },
     string: 'node ./example/index.js' } }

```

**Comment by remy** [comment]
Can you provide an example index.js?

**Comment by remy** [comment]
Or even better, can you post up the minimal project (ideally `package.json` + `index.js`) to a gist?

**Comment by remy** [comment]
Ping or is this idle and (implied) fix is already live? I'd like to close in the next 24 hours otherwise.
