### ISSUE TITLE
TypeError: Path must be a string. Received null

### ISSUE THREAD

**Issue by Tjomas** [remy/nodemon#1169]
- `nodemon -v`: 1.13.0
- `node -v`: v8.9.1
- Operating system/terminal environment: Docker
- Command you ran: nodemon --legacy-watch --on-change-only --verbose

The proccess exits directly after first start. 

[nodemon] 1.13.0
[nodemon] reading config /app/nodemon.json
[nodemon] to restart at any time, enter `rs`
[nodemon] or send SIGHUP to 16 to restart
[nodemon] ignoring: .git .nyc_output .sass-cache bower_components coverage /app/node_modules/**/* src/**/*.spec.ts
[nodemon] watching: /app/dist/**/*
[nodemon] watching extensions: json,hbs,trigger
[nodemon] child pid: 36
[nodemon] watching 1 files
[nodemon] files triggering change check: dist/modules/api.controller.js
[nodemon] matched rule: **/app/dist/**/*
[nodemon] exiting
path.js:28
    throw new TypeError('Path must be a string. Received ' + inspect(path));
    ^

TypeError: Path must be a string. Received null
    at assertPath (path.js:28:11)
    at Object.resolve (path.js:1186:7)
    at filterAndRestart (/usr/local/share/.config/yarn/global/node_modules/nodemon/lib/monitor/watch.js:145:25)
    at FSWatcher.<anonymous> (/usr/local/share/.config/yarn/global/node_modules/nodemon/lib/monitor/watch.js:77:18)
    at emitTwo (events.js:126:13)
    at FSWatcher.emit (events.js:214:7)
    at FSWatcher.<anonymous> (/usr/local/share/.config/yarn/global/node_modules/chokidar/index.js:196:15)
    at FSWatcher._emit (/usr/local/share/.config/yarn/global/node_modules/chokidar/index.js:238:5)backend-api_1     |     at FSWatcher.NodeFsHandler._handleFile (/usr/local/share/.config/yarn/global/node_modules/chokidar/lib/nodefs-handler.js:275:10)
    at FSWatcher.<anonymous> (/usr/local/share/.config/yarn/global/node_modules/chokidar/lib/nodefs-handler.js:473:21)

**Comment by martin-dimitrov13** [comment]
Same here.

**Comment by remy** [comment]
Merged and will be auto-released live in nodemon@1.13.1

**Comment by art32** [comment]
I updated ```nodemon``` but the error remained. ```"nodemon": "^1.13.1"```

```nodemon --exec "./node_modules/.bin/flow-remove-types -d build src && node" --watch src --verbose build/index.js```

The first launch is successful, but when I update any file the nodemon falls.
```TypeError: Path must be a string. Received null```

**Comment by remy** [comment]
@art32 can you include a full stack trace so I don't have to guess the line number? Or a PR would be awesome too. The change definitely fixed a problem, but it's possible that a similar block of code is sneaking through too.

**Comment by art32** [comment]
```
[nodemon] Looking in package.json for nodemonConfig
[nodemon] 1.13.0
[nodemon] reading config /* path to project */package.json
[nodemon] to restart at any time, enter `rs`
[nodemon] or send SIGHUP to 25587 to restart
[nodemon] ignoring: .git .nyc_output .sass-cache bower_components coverage /* path to project */node_modules/**/*
[nodemon] watching: /* path to project */src/**/*
[nodemon] watching extensions: js,json
[nodemon] starting `./node_modules/.bin/flow-remove-types -d build src && node build/index.js`
[nodemon] child pid: 25661
[nodemon] watching 4 files
src/index.js
 ↳ build/index.js
src/sockets.js
 ↳ build/sockets.js
src/common/api_endpoint.js
 ↳ build/common/api_endpoint.js
src/common/errors/index.js
 ↳ build/common/errors/index.js
[nodemon] files triggering change check: src/sockets.js
[nodemon] matched rule: **/* path to project */src/**/*
[nodemon] exiting
path.js:28
    throw new TypeError('Path must be a string. Received ' + inspect(path));
    ^
TypeError: Path must be a string. Received null
    at assertPath (path.js:28:11)
    at Object.resolve (path.js:1186:7)
    at FSWatcher.filterAndRestart (~/.config/yarn/global/node_modules/nodemon/lib/monitor/watch.js:145:25)
    at emitOne (events.js:116:13)
    at FSWatcher.emit (events.js:211:7)
    at FSWatcher.<anonymous> (~/.config/yarn/global/node_modules/chokidar/index.js:196:15)
    at FSWatcher._emit (~/.config/yarn/global/node_modules/chokidar/index.js:238:5)
    at FSWatcher.<anonymous> (~/.config/yarn/global/node_modules/chokidar/lib/fsevents-handler.js:204:14)
    at addOrChange (~/.config/yarn/global/node_modules/chokidar/lib/fsevents-handler.js:210:7)
    at FSWatcher.<anonymous> (~/.config/yarn/global/node_modules/chokidar/lib/fsevents-handler.js:236:16)
```

**Comment by remy** [comment]
@art32 can you use the latest nodemon (currently 1.13.3)

**Comment by art32** [comment]
@remy i use 1.13.3 )

**Comment by remy** [comment]
@art32 you're using 1.13.0:

<img width="508" alt="screen shot 2017-12-16 at 11 06 59" src="https://user-images.githubusercontent.com/13700/34069851-4574655a-e251-11e7-8edd-09727018da4a.png">

**Comment by art32** [comment]
@remy oh sorry, indeed I used an old version installed globally... The problem was solved.
 Thank you!
