### ISSUE TITLE
ENOTCONN on Linux

### ISSUE THREAD

**Issue by Berkmann18** [remy/nodemon#1230]
- `nodemon -v`: 1.14.7
- `node -v`: 9.4.0
- Operating system/terminal environment: ArchLinux 4.13.0-rc3-mainline / xfce4-terminal (v0.8.6)
- Command you ran: `nodemon -e js,html,css --delay 1`

### Expected behaviour
Run `node server.js` and output the correct things such as `OSM Server listening at http://localhost:3000`
That shows properly when running `npm start`.

### Actual behaviour
```cli
events.js:137
      throw er; // Unhandled 'error' event
      ^

Error: read ENOTCONN
    at _errnoException (util.js:1003:13)
    at Socket._read (net.js:495:20)
    at Socket.Readable.read (_stream_readable.js:449:10)
    at Socket.read (net.js:376:43)
    at new Socket (net.js:259:12)
    at createSocket (internal/child_process.js:241:11)
    at ChildProcess.spawn (internal/child_process.js:357:23)
    at exports.spawn (child_process.js:499:9)
    at Object.exports.execFile (child_process.js:209:15)
    at exports.exec (child_process.js:139:18)
```

### Steps to reproduce
`nodemon [anything]`
Even `nodemon -v` returns an ENOTCONN error in on a WiFi connected laptop.
I can provide the relevant code for the server and routes, but the code remained the same as when nodemon used to work.

---

If applicable, please append the `--dump` flag on your command and include the output here **ensuring to remove any sensitive/personal details or tokens**.

Here's the log file:
```cli
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'live', '--dump' ]
2 info using npm@5.6.0
3 info using node@v9.4.0
4 verbose run-script [ 'prelive', 'live', 'postlive' ]
5 info lifecycle offosm@1.0.0~prelive: offosm@1.0.0
6 info lifecycle offosm@1.0.0~live: offosm@1.0.0
7 verbose lifecycle offosm@1.0.0~live: unsafe-perm in lifecycle true
8 verbose lifecycle offosm@1.0.0~live: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/maxie/Dropbox/MSciCS/y3/CS3821/osm/node_modules/.bin:/home/maxie/bin:/home/maxie/bin:/home/maxie/Dropbox/Script/bin:/home/maxie/bin:/home/maxie/bin:/home/maxie/Dropbox/Script/bin:/home/maxie/bin:/home/maxie/bin:/home/maxie/Dropbox/Script/bin:/home/maxie/bin:/home/maxie/bin:/home/maxie/Dropbox/Script/bin:/home/maxie/bin:/home/maxie/bin:/home/maxie/Dropbox/Script/bin:/home/maxie/bin:/home/maxie/bin:/home/maxie/Dropbox/Script/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
9 verbose lifecycle offosm@1.0.0~live: CWD: /home/maxie/Dropbox/MSciCS/y3/CS3821/osm
10 silly lifecycle offosm@1.0.0~live: Args: [ '-c', 'nodemon -e js,html,css --delay 1' ]
11 silly lifecycle offosm@1.0.0~live: Returned: code: 1  signal: null
12 info lifecycle offosm@1.0.0~live: Failed to exec live script
13 verbose stack Error: offosm@1.0.0 live: `nodemon -e js,html,css --delay 1`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
13 verbose stack     at EventEmitter.emit (events.js:160:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:160:13)
13 verbose stack     at maybeClose (internal/child_process.js:943:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
14 verbose pkgid offosm@1.0.0
15 verbose cwd /home/maxie/Dropbox/MSciCS/y3/CS3821/osm
16 verbose Linux 4.13.0-rc3-mainline
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "live" "--dump"
18 verbose node v9.4.0
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 1
22 error offosm@1.0.0 live: `nodemon -e js,html,css --delay 1`
22 error Exit status 1
23 error Failed at the offosm@1.0.0 live script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

Note: whenever I try to update nodemon either globally (or locally I get this:
```cli
npm i -g nodemon@latest

Error: read ENOTCONN
    at _errnoException (util.js:1003:13)
    at Socket._read (net.js:495:20)
    at Socket.Readable.read (_stream_readable.js:449:10)
    at Socket.read (net.js:376:43)
    at new Socket (net.js:259:12)
    at createSocket (internal/child_process.js:241:11)
    at ChildProcess.spawn (internal/child_process.js:357:23)
    at exports.spawn (child_process.js:499:9)
    at Object.exports.execFile (child_process.js:209:15)
    at uidNumber (/usr/lib/node_modules/npm/node_modules/uid-number/uid-number.js:33:17)
    at Conf.loadUid (/usr/lib/node_modules/npm/lib/config/load-uid.js:11:5)
    at Conf.<anonymous> (/usr/lib/node_modules/npm/lib/config/core.js:235:10)
    at Conf.setUser (/usr/lib/node_modules/npm/lib/config/set-user.js:15:34)
    at Conf.loadExtras (/usr/lib/node_modules/npm/lib/config/core.js:233:8)
    at Conf.<anonymous> (/usr/lib/node_modules/npm/lib/config/core.js:173:12)
    at Object.onceWrapper (events.js:255:19)
/usr/lib/node_modules/npm/lib/npm.js:61
      throw new Error('npm.load() required')
      ^

Error: npm.load() required
    at Object.get (/usr/lib/node_modules/npm/lib/npm.js:61:13)
    at process.errorHandler (/usr/lib/node_modules/npm/lib/utils/error-handler.js:205:18)
    at process.emit (events.js:160:13)
    at process._fatalException (bootstrap_node.js:386:26)
```

**Comment by Berkmann18** [comment]
Indeed, it was something to do with node where I add to re-install it and install `libuv-1.19` from Pacman.
