### ISSUE TITLE
Ability to avoid fork via config options (babel problem)

### ISSUE THREAD

**Issue by nodkz** [remy/nodemon#1245]
I'm using `nodemon` in a script which started via `babel-node` in some complex dev environment.

In simplified view it looks like:
```
$> ./node_modules/.bin/babel-node ./startNodemon.js
```

```js
import nodemon from 'nodemon';

...

  const opts = {
      execMap: {
        // js: 'node', // use `childProcess.fork` and it's bad, case transpile server.js via babel
        js: process.execPath, // use `childProcess.spawn` for running server.js
      },
      script: serverPath,
      env: {
        NODE_ENV: 'development',
        EXPRESS_PORT: port,
      },
      watch: [serverPath],
    };

    supervisor = nodemon(opts);
    ...
```

**So after several hours of debugging following error:**
```
[21:49:08] Starting 'backendNodemon'...

/app/build/development/webpack:/webpack/bootstrap 5a375fcb339c4e886c1a:271

^
Error: only one instance of @babel/polyfill is allowed
    at Object../node_modules/@babel/polyfill/lib/index.js (/app/build/development/webpack:/webpack/bootstrap 5a375fcb339c4e886c1a:271:1)
    at __webpack_require__ (/app/build/development/webpack:/webpack/bootstrap 5a375fcb339c4e886c1a:40:1)
    at fn (/app/build/development/webpack:/webpack/bootstrap 5a375fcb339c4e886c1a:7:1)

    at Object.0 (/app/build/development/webpack:/lib/rabota-fresh-jobs/WatchJob.js:60:1)
    at __webpack_require__ (/app/build/development/webpack:/webpack/bootstrap 5a375fcb339c4e886c1a:40:1)
    at module.exports.modules../lib/lvovich/city.js.Object.defineProperty.value (/app/build/development/webpack:/webpack/bootstrap 5a375fcb339c4e886c1a:50:1)
    at Object.<anonymous> (/app/build/development/webpack:/webpack/bootstrap 5a375fcb339c4e886c1a:50:1)
    at Module._compile (module.js:624:30)
    at Module._compile (/app/node_modules/pirates/lib/index.js:91:24)
    at Module._extensions..js (module.js:635:10)
```

**I found that you use `fork` for spinning up a script**

https://github.com/remy/nodemon/blob/33fa6f4970412a6bfa12ff357f44dfebf0ad63c7/lib/monitor/run.js#L68-L84

So i'm using `babel-node` and it automatically again transpile provided bundled server script (cause use `fork`). It spends time on this operation, and also break my server script with error.

**1. For what purpose do you use `childProcess.fork` instead of `childProcess.spawn`?**

**2. Can we add some option, to not use `childProcess.fork`?**

For now I solved this via following hack:
```js
  const opts = {
      execMap: {
        // js: 'node', // use `childProcess.fork` and it's bad, case transpile server.js via babel
        js: process.execPath, // use `childProcess.spawn` for running server.js
      },
      ...
  };
```

**Comment by remy** [comment]
Background reading to why fork exists is [here](https://github.com/remy/nodemon/issues/1025) (short version: fixed a lot of bugs).

I'm happy to take a PR that accepts a new argument `--spawn`, that forces the logic down the spawn pathway. You'll need to the following places (off the top of my head):

- https://github.com/remy/nodemon/blob/master/lib/cli/parse.js
- https://github.com/remy/nodemon/blob/master/doc/cli/options.txt (under Execution - note it's in alphabetical order)

…and then the run logic that you found would use (something like) `if (config.spawn)`.

How does that sound?
