### ISSUE TITLE
After updating the package I get an error.

### ISSUE THREAD

**Issue by Valeronlol** [remy/nodemon#1286]
Hey!
After being updated to the latest version(1.17.1) from 1.15.1 started to receive this error.
_"Cannot read property 'length' of undefined
   at  node_modules/nodemon/lib/config/load.js:74:60
   at callback (node_modules/nodemon/lib/config/load.js:174:5)
    at settings (node_modules/nodemon/lib/config/load.js:227:5)
    at callback (node_modules/nodemon/lib/config/load.js:174:5)
    at node_modules/nodemon/lib/config/load.js:214:5
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)"_

Node.js version - v8.9.4.
After rolling back to 1.15.1 everything works fine.
I use gulp-nodemon. (v2.2.1,)

**Comment by remy** [comment]
Regression here: https://github.com/remy/nodemon/commit/e41f3c3aad148b3b283df1c579ff9e99071ff49d#diff-9c0e28fe64a496221bd5abcc39da4b43R74
