### ISSUE TITLE
Error while requiring nodemon in the node repl

### ISSUE THREAD

**Issue by debuc** [remy/nodemon#1292]
- `nodemon -v`: 1.14.12
- `node -v`: 8.4.0
- Operating system/terminal environment: macOS / zsh
- Command you ran: require('nodemon')

### Expected behavior
It should require nodemon successfully

### Actual behavior
It was crashing with cannot read property 'index of' of null error

### Steps to reproduce
1. run node
2. require nodemon

###Output
TypeError: Cannot read property 'indexOf' of null
    at /Users/debarc/Projects/JavaScript/Step-Project/ludo-dvamps/node_modules/nodemon/lib/utils/index.js:27:21
    at Object.<anonymous> (/Users/debarc/Projects/JavaScript/Step-Project/ludo-dvamps/node_modules/nodemon/lib/utils/index.js:34:5)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/debarc/Projects/JavaScript/Step-Project/ludo-dvamps/node_modules/nodemon/lib/monitor/run.js:3:13)

**Comment by remy** [comment]
Can you replicate with latest nodemon@1.17.x?

**Comment by debuc** [comment]
Yeah sure

**Comment by debuc** [comment]
This bug is there in 1.17.2 also... I have updated it

**Comment by debuc** [comment]
This issue is still there in latest nodemon. Are you planning to fix it?

**Comment by remy** [comment]
Not sure about "planning", but yeah, I don't want open bugs. Your PR doesn't do anything, and doesn't even touch the line in question. Maybe update that instead and include a test?

**Comment by remy** [comment]
Okay, I've finally worked out that this **only** applies when you run node from the repl. Rather than from any require - which is why none of my tests broke.
