### ISSUE TITLE
systemd nodemon : [nodemon] unable to run executable: "node"

### ISSUE THREAD

**Issue by Rizary** [remy/nodemon#1324]
- `nodemon -v`: 1.17.1

- `node -v`: 6.12.3
- Operating system/terminal environment: nixos
- Command you ran: in the system, `ExecStart=nodemon app_hook.js`

### Expected behaviour
systemd works perfectly

### Actual behaviour
```
   Loaded: loaded (/nix/store/az5x204fxbwwwyzk83dfxv0081km3f2w-unit-qoeifs-server.service/qoeifs-server.service; linke
   Active: failed (Result: exit-code) since Sun 2018-04-29 14:27:32 UTC; 2s ago
  Process: 6993 ExecStart=/nix/store/h1nigz3ibf0lr3270jvm3v0y22y7glac-node-nodemon-1.17.1/bin/nodemon /nix/store/0sw5v
 Main PID: 6993 (code=exited, status=1/FAILURE)

Apr 29 14:27:32 qoeifs nodemon[6993]:     at emitOne (events.js:96:13)
Apr 29 14:27:32 qoeifs nodemon[6993]:     at ChildProcess.emit (events.js:188:7)
Apr 29 14:27:32 qoeifs nodemon[6993]:     at Process.ChildProcess._handle.onexit (internal/child_process.js:217:12)
Apr 29 14:27:32 qoeifs nodemon[6993]:     at onErrorNT (internal/child_process.js:376:16)
Apr 29 14:27:32 qoeifs nodemon[6993]:     at _combinedTickCallback (internal/process/next_tick.js:80:11)
Apr 29 14:27:32 qoeifs nodemon[6993]:     at process._tickCallback (internal/process/next_tick.js:104:9)
Apr 29 14:27:32 qoeifs nodemon[6993]: [nodemon] unable to run executable: "node"
Apr 29 14:27:32 qoeifs systemd[1]: qoeifs-server.service: Main process exited, code=exited, status=1/FAILURE
Apr 29 14:27:32 qoeifs systemd[1]: qoeifs-server.service: Unit entered failed state.
Apr 29 14:27:32 qoeifs systemd[1]: qoeifs-server.service: Failed with result 'exit-code'.
```

### Steps to reproduce
```
[Service]
Environment="LOCALE_ARCHIVE=/nix/store/5f1qgnx8rh4aqx9fpszk4kixaamlcwws-glibc-locales-2.25-123/lib/locale/locale-archive"
Environment="PATH=/nix/store/4bh7qhnrjk8cgd1bh7nr0glbga0aasdx-coreutils-8.28/bin:/nix/store/y936jxj0dl6rm9v6hrjz945361s73bcx-findutils-4.6.0/bin:/nix/store/h6vf6alpgnynlx1w9xwlaqhnjybjvy2x-gnugrep-3.1/bin:/nix/store/za5n7hg16pnkvdrnnh7fxy9hsx9pp2i6-gnused-4.4/bin:/nix/store/zabgyp18pf1gzq63fh1yzmzxdbgqx4y4-systemd-234/bin:/nix/store/4bh7qhnrjk8cgd1bh7nr0glbga0aasdx-coreutils-8.28/sbin:/nix/store/y936jxj0dl6rm9v6hrjz945361s73bcx-findutils-4.6.0/sbin:/nix/store/h6vf6alpgnynlx1w9xwlaqhnjybjvy2x-gnugrep-3.1/sbin:/nix/store/za5n7hg16pnkvdrnnh7fxy9hsx9pp2i6-gnused-4.4/sbin:/nix/store/zabgyp18pf1gzq63fh1yzmzxdbgqx4y4-systemd-234/sbin"
Environment="PORT=8080"
Environment="TZDIR=/nix/store/vcny1mg2zw2kl60k0kzxjd6gxggxjaw4-tzdata-2017c/share/zoneinfo"



ExecStart=/nix/store/h1nigz3ibf0lr3270jvm3v0y22y7glac-node-nodemon-1.17.1/bin/nodemon /nix/store/0sw5vb3pnavk1iyfw098hkwgqw7n7axp-qoeifs-app/prod/app_hook.js
User=root

```

start using `systemctl start app`

---

please note that if I run the above ExecStart manually, nodemon works well.

If applicable, please append the `--dump` flag on your command and include the output here **ensuring to remove any sensitive/personal details or tokens**.

**Comment by remy** [comment]
Going by the logs, it looks like your system can't find node. Going to close this as it's not a nodemon issue - just need to get the file paths right.
