### ISSUE TITLE
Crashes when started

### ISSUE THREAD

**Issue by Exeteres** [remy/nodemon#1372]
- `nodemon -v`: 1.17.5
- `node -v`: 8.11.3/9.0.0/10.5.0 (none of them works)
- Operating system:  kubuntu 18.04
- Desktop environment: kde plasma 5.12.5
- Terminal: konsole 17.12.3
- Command you ran: nodemon main.js

### Expected behaviour
Nodemon starts as before. Everything works great.

### Actual behaviour
Crashes with this stack trace
```
[nodemon] 1.17.5
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node main.js`
/usr/lib/node_modules/nodemon/lib/monitor/watch.js:128
      throw e;
      ^

TypeError: Cannot read property 'prev' of undefined
    at Compiler.<anonymous> (/usr/lib/node_modules/nodemon/node_modules/nanomatch/lib/compilers.js:213:25)
    at Compiler.visit (/usr/lib/node_modules/nodemon/node_modules/snapdragon/lib/compiler.js:129:15)
    at Compiler.mapVisit (/usr/lib/node_modules/nodemon/node_modules/snapdragon/lib/compiler.js:143:12)
    at Compiler.compile (/usr/lib/node_modules/nodemon/node_modules/snapdragon/lib/compiler.js:168:10)
    at Snapdragon.compile (/usr/lib/node_modules/nodemon/node_modules/snapdragon/index.js:156:32)
    at /usr/lib/node_modules/nodemon/node_modules/micromatch/index.js:786:23
    at memoize (/usr/lib/node_modules/nodemon/node_modules/micromatch/index.js:859:13)
    at Function.micromatch.compile (/usr/lib/node_modules/nodemon/node_modules/micromatch/index.js:783:10)
    at create (/usr/lib/node_modules/nodemon/node_modules/micromatch/index.js:686:25)
    at /usr/lib/node_modules/nodemon/node_modules/micromatch/index.js:695:16
```
### Steps to reproduce
I do not even know. On the previous system (linux mint 18) everything worked fine.

---

### -- dump
```
node: v10.5.0
nodemon: 1.17.5
command: /home/exeteres/.nvm/v10.5.0/bin/node /usr/bin/nodemon main.js --dump
cwd: /home/exeteres/Projects/admin
OS: linux x64
--------------
{ run: false,
  system: { cwd: '/home/exeteres/Projects/admin' },
  required: false,
  dirs: [ '/home/exeteres/Projects/admin' ],
  timeout: 1000,
  options:
   { dump: true,
     ignore:
      [ '**/.git/**',
        '**/.nyc_output/**',
        '**/.sass-cache/**',
        '**/bower_components/**',
        '**/coverage/**',
        '**/node_modules/**',
        re: /.*.*\/\.git\/.*.*|.*.*\/\.nyc_output\/.*.*|.*.*\/\.sass\-cache\/.*.*|.*.*\/bower_components\/.*.*|.*.*\/coverage\/.*.*|.*.*\/node_modules\/.*.*/ ],
     watch: [ '*.*', re: /.*\..*/ ],
     ignoreRoot:
      [ '**/.git/**',
        '**/.nyc_output/**',
        '**/.sass-cache/**',
        '**/bower_components/**',
        '**/coverage/**',
        '**/node_modules/**' ],
     restartable: 'rs',
     colours: true,
     execMap: { py: 'python', rb: 'ruby' },
     stdin: true,
     runOnChangeOnly: false,
     verbose: false,
     signal: 'SIGUSR2',
     stdout: true,
     watchOptions: {},
     execOptions:
      { script: 'main.js',
        exec: 'node',
        args: [],
        scriptPosition: 0,
        nodeArgs: undefined,
        execArgs: [],
        ext: 'js,mjs,json',
        env: {} },
     monitor:
      [ '*.*',
        '!**/.git/**',
        '!**/.nyc_output/**',
        '!**/.sass-cache/**',
        '!**/bower_components/**',
        '!**/coverage/**',
        '!**/node_modules/**' ] },
  load: [Function],
  reset: [Function: reset],
  lastStarted: 0,
  loaded: [],
  watchInterval: null,
  signal: 'SIGUSR2',
  command:
   { raw: { executable: 'node', args: [ 'main.js' ] },
     string: 'node main.js' } }
```

**Comment by Exeteres** [comment]
`nodemon -v`: 1.16.0
There is no such problem

**Comment by jonschlinkert** [comment]
This bug was right after it happened. Just reinstall to get the fix. See https://github.com/micromatch/nanomatch/issues/15 for more info.

**Comment by remy** [comment]
Thanks folks.
