### ISSUE TITLE
Error: Cannot find module 'use'

### ISSUE THREAD

**Issue by tamirvs** [remy/nodemon#1396]
- `nodemon -v`: 1.18.2
- `node -v`: 8.11.3
- Operating system/terminal environment: Ubuntu 14.04 on VirtualBox 5.2.12
- Command you ran: Everything

I installed nodemon: `npm install -g nodemon`
I got this error for every command (even `nodemon -h`):

```
module.js:549
    throw err;
    ^

Error: Cannot find module 'use'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/lib/node_modules/nodemon/node_modules/snapdragon/lib/compiler.js:3:11)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
```

I then tried installing version 1.13 and it worked without errors. I then started upgrading to 1.14, 1.15, etc. to see when the error re-appears but even the latest version worked fine.
I'm not sure what happened and if it's just me, so I wanted to let you know about this issue.

**Comment by remy** [comment]
I don't recognise the `snapdragon` dep there that's causing the problem. It's under nodemon's deps, so I suspect it's pulled in due to the OS … somehow? 

Do you have a package-lock.json file or a yarn.lock file that we might be able to understand what's pulling snapdragon in so we can debug it?

**Comment by tamirvs** [comment]
Is there a lock file for globally installed packages?

**Comment by icebob** [comment]
Similar issue after installed nodemon@1.18.3

```
Error: Cannot find module 'from'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (D:\Work\moleculer\moleculer-repl\node_modules\event-stream\index.js:10:12)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! moleculer-repl@0.5.0 dev: `nodemon examples/index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the moleculer-repl@0.5.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

But removed `node_modules`, `package-lock.json` & `npm i` solved the problem.
