### ISSUE TITLE
nodemon do not kill older process.

### ISSUE THREAD

**Issue by sandinocoelho** [remy/nodemon#1435]
- `nodemon -v`: 1.18.4
- `node -v`: 8.12.0
- Operating system/terminal environment: Ubuntu 18.04
- Command you ran: nodemon app.js

### Expected behaviour
When I make some changes to the code, the expected behaviour is that the node will kill the node process and create a new one.

### Actual behaviour
nodemon creates a new process but does not kill the old process and because of this, I have a conflict between ports.

### Steps to reproduce
$ nodemon app
> change some file in the project

Error Message:
```
[nodemon] restarting due to changes...
[nodemon] starting `node app`
consign v0.1.6 Initialized in /home/sandino/Projects/udemy_nodejs/Portal de Noticias
+ ./app/routes/admin.js
+ ./app/routes/home.js
+ ./app/routes/noticias.js
+ ./config/dbConnection.js
+ ./app/models/NoticiasDAO.js
+ ./app/controllers/admin.js
+ ./app/controllers/home.js
+ ./app/controllers/noticias.js
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::3002
    at Server.setupListenHandle [as _listen2] (net.js:1360:14)
    at listenInCluster (net.js:1401:12)
    at Server.listen (net.js:1485:7)
    at Function.listen (/home/sandino/Projects/udemy_nodejs/Portal de Noticias/node_modules/express/lib/application.js:618:24)
    at Object.<anonymous> (/home/sandino/Projects/udemy_nodejs/Portal de Noticias/app.js:4:5)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
[nodemon] app crashed - waiting for file changes before starting...
```
> Ctrl + C 

```
$ lsof -i :3002

COMMAND   PID    USER   FD   TYPE  DEVICE SIZE/OFF NODE NAME
node    21441 sandino   11u  IPv6 1327282      0t0  TCP *:3002 (LISTEN)
```

*This is the first time I write an issue. Forgive me if any information was missing.

**Comment by rveitch** [comment]
Also happening here:
`nodemon 1.18.4 node 8.11.1`

I'm not on `10.12.0`, so not sure it's that. I am on OSX.

```
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::3000
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at Server.setupListenHandle [as _listen2] (net.js:1367:14)
    at listenInCluster (net.js:1408:12)
    at Server.listen (net.js:1492:7)
    at Function.listen (/Users/ryanveitch/node-projects/shiplog/node_modules/express/lib/application.js:618:24)
    at Object.<anonymous> (/Users/ryanveitch/node-projects/shiplog/api/api.js:41:5)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/ryanveitch/node-projects/shiplog/server.js:1:75)
    at Module._compile (module.js:652:30)
[nodemon] app crashed - waiting for file changes before starting...

```

```
COMMAND   PID       USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
node    89098 ryanveitch   17u  IPv6 0x8f1a810130f91b85      0t0  TCP *:hbci (LISTEN)
```

**Comment by samuelopra** [comment]
I also have this issue Nodemon v1.18.4

**Comment by abdullahtariq1171** [comment]
Same issue with `"nodemon": "^1.18.6"`

**Comment by remy** [comment]
Um…no one has actually provided an app.js to replicate with. Without that, it can't be replicated and can't be debugged.

**Comment by ellefsen** [comment]
I have this example set up - https://codesandbox.io/s/o4wzoqk9o6
It runs fine in the sandbox, but if I download it and run it on my mac it will fail with `Error: listen EADDRINUSE :::8080`

Tried running in both my default environment and with the sandbox versions. Both fail.
Node v10.6.0|v8.11.2
NPM 6.1.0|5.6.0

Mac OS 10.13.6 - shell: zsh 5.3 (x86_64-apple-darwin17.0)

**Comment by zoman2000** [comment]
Same problem here.
Here is the sample "project" - https://gitlab.com/alexsmit/sample. Tried to create as smaller project as possible. I hope it will help.

(not expected): If you modify server index.js, save it you will get a mentioned above error. And event not captured :(
(expected): If you modify client code (react, excluded) works fine because it is excluded.

Environment: Linux, Node 8.11.4

**Comment by remy** [comment]
Fairly sure this is directly related to #1459 et al. nodemon@1.18.7 fixes it.

Please test with latest (currently being released) and let me know if it's not fixed (and please include tests and PR to contribute).

**Comment by zoman2000** [comment]
Working for me. Thanks !!!!

**Comment by zverbeta** [comment]
Working too. Thanks

**Comment by nicklasring** [comment]
`events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::8088
    at Server.setupListenHandle [as _listen2] (net.js:1270:14)`

Version 1.19.0 still not exiting correctly

**Comment by AndrewOdiit** [comment]
Having the same problem with version 1.19.4 
app.js
const PORT = process.env.PORT || 8000;

app.listen(PORT, () => {
  console.log(`Server started on port ${PORT}`);
});

**Comment by VladKomarov** [comment]
I figured out that after code change not only node process still running, but the parent nodemon process too. Try killing both nodemon parent and node proccesses and rerun nodemon. For now it helped me, but it happened not first time.

**Comment by denissabramovs** [comment]
same here in v2.0.4
