### ISSUE TITLE
Nodemon --watch + Express listening server cause nodemon crashes on restart

### ISSUE THREAD

**Issue by corinnekunze** [remy/nodemon#1479]
- `nodemon -v`:
1.18.7
- `node -v`:
v11.3.0
- Operating system/terminal environment: 
macOS high sierra 10.13.6 / ZSH

This package.json encapsulates the error on my dev machine:
```
{
  "name": "nodemon-issue",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "server": "nodemon index.js --watch"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "nodemon": "^1.18.7"
  },
  "dependencies": {
    "express": "^4.16.4"
  }
}
```
Basic index file to watch which causes the crash on changing the file:
```
const express = require('express');

const app = express();

const webPort = 3222;
app.listen(webPort, () => console.log(`App listening on port ${webPort}.`))

module.exports = app;
```

I have been experiencing this issue on two separate macOS machines - but near to identical dev environments.

### Expected Functionality
Restart on code change

### What actually happens
Crash on restart and this error:
```
/Users/corinnekunze/prof-dev/node/nodemon-issue/node_modules/pstree.remy/lib/tree.js:70
  ps.stdout.on('data', function(data) {
           ^

TypeError: Cannot read property 'on' of undefined
    at buildProcessTree (/Users/corinnekunze/prof-dev/node/nodemon-issue/node_modules/pstree.remy/lib/tree.js:70:12)
    at /Users/corinnekunze/prof-dev/node/nodemon-issue/node_modules/pstree.remy/lib/tree.js:91:7
    at Array.forEach (native)
    at ChildProcess.onClose (/Users/corinnekunze/prof-dev/node/nodemon-issue/node_modules/pstree.remy/lib/tree.js:86:27)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:921:16)
    at Socket.stream.socket.on (internal/child_process.js:348:11)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nodemon-issue@1.0.0 server: `nodemon index.js --watch`
npm ERR! Exit status 1
```
### More background info:
I have delved into `pstree.remy/lib/tree.js`a bit and noticed it's looping through the PIDs to define this event handler. Eventually the `stdout` method of on the `ps` variable is undefined and throws the exception.
```
var ps = spawnChildProcessesList(parentPid);
var allData = '';
# stdout is undefined after a certain number of iterations.
# are irrelevant PIDs being pushed here that should not be iterated on?
ps.stdout.on('data', function(data) {
    var data = data.toString('ascii');
    allData += data;
});
```

**Comment by remy** [comment]
Thank you for the detail (a refreshing change!), and I'll take a look at `pstree.remy` to see if there's anything I can do there.

I happen to be running the exact same environment as you (MacOS + node version, etc) - but I can't replicate. Are you able to replicate with your example code too?

If so I wonder if there's _anything_ else in your environment that might be messing with `ps` perhaps?

**Comment by remy** [comment]
Ah, actually, can you try running `which pgrep` (in the terminal) under the user you're running nodemon with - and post the result here.

**Comment by TooManyBees** [comment]
I also encountered this issue, so I checked pgrep. I was using version 0.4pre1 installed by Homebrew, which was apparently different than what MacOS ships with (does it have a `--version` flag? I couldn't find one). Uninstalling it resolved the crash on restart.

Though I should note, Homebrew indicated that its version of pgrep was installed 4 months ago, but I did not experience crashes on restart at that time.

**Comment by TooManyBees** [comment]
Out of idle curiosity, @corinnekunze, why did you have it installed through Homebrew in the first place? Because I can't think of any reason I would have installed it on my own, and Homebrew didn't indicate that it was a dependency of any other formula. 👻

**Comment by corinnekunze** [comment]
@TooManyBees The dev machine setup that my team uses installs proctools through brew in the set of 'essential' libraries when it sets up. 
This is probably just an unnecessary dependency now because it looks like pgrep and pkill commands are included in more modern versions of macOS.
