### ISSUE TITLE
App crashes with error "Error: ENOENT: no such file or directory, uv_cwd"

### ISSUE THREAD

**Issue by soubhikchatterjee** [remy/nodemon#1588]
- `nodemon -v`: 1.18.10
- `node -v`:12.4.0
- Operating system/terminal environment: MacOS with iTerm
- Using Docker? What image: node:12.4.0-alpine
- Command you ran: nodemon -L --delay 5 app.js

### Expected behaviour
Nodemon should restart the application without any error

### Actual behaviour
Nodemon is crashing

### Steps to reproduce
Often happens when a lot of files gets synced to the docker container that nodemon is watching

---

```
[nodemon] restarting due to changes...
[nodemon] starting `node app.js`
internal/process/main_thread_only.js:42
    cachedCwd = binding.cwd();
                        ^
Error: ENOENT: no such file or directory, uv_cwd
    at process.cwd (internal/process/main_thread_only.js:42:25)
    at Object.resolve (path.js:976:47)
    at patchProcessObject (internal/bootstrap/pre_execution.js:73:28)
    at prepareMainThreadExecution (internal/bootstrap/pre_execution.js:10:3)
    at internal/main/run_main_module.js:7:1 {
  errno: -2,
  code: 'ENOENT',
  syscall: 'uv_cwd'
}
[nodemon] app crashed - waiting for file changes before starting...
```

**Comment by remy** [comment]
Can you paste the same for `node app.js`

**Comment by soubhikchatterjee** [comment]
There you go

```
bash-4.4# node app.js
internal/process/main_thread_only.js:42
    cachedCwd = binding.cwd();
                        ^

Error: ENOENT: no such file or directory, uv_cwd
    at process.cwd (internal/process/main_thread_only.js:42:25)
    at Object.resolve (path.js:976:47)
    at patchProcessObject (internal/bootstrap/pre_execution.js:73:28)
    at prepareMainThreadExecution (internal/bootstrap/pre_execution.js:10:3)
    at internal/main/run_main_module.js:7:1 {
  errno: -2,
  code: 'ENOENT',
  syscall: 'uv_cwd'
}
```

**Comment by remy** [comment]
So this seems to be a problem either with the user code or node (in that
environment), since the bug occurs without nodemon.
