### ISSUE TITLE
Nodemon chrashes when file has an error

### ISSUE THREAD

**Issue by Paultje52** [remy/nodemon#1649]
- Nodemon version: `2.0.1`:
- NodeJS version: `10.16.0`:
- Operating system/terminal environment: Windows, standard command line
- Command you ran: `nodemon`

Nodemon.json:
```json
{
  "ignore": ["package.json", "package-lock.json", "node_modules/*", "configstore.json", "database.sqlite", "index.js"],
  "main": "bot.js"
}
```

### Expected behaviour
Nodemon logs that my app is crashed and is waiting for file changes.

### Actual behaviour
Nodemon crashed because of an error.

### Steps to reproduce
The crash happens when a SyntaxError: await is only valid in async function is thrown and the app restarted at least one time because of a change.

Open a project, start nodemon, be sure that the app stays running (with a web app for example) (be sure that there are no errors on startup), then remove an async environment (So NodeJS will throw a SyntaxError: await is only valid in async function error) and save that file so nodemon will restart because of a change.

The error that I get is this. (First the error of the await/async, then it gets interrupted by nodemon error)
```
  let done = await client.db.get("MorningSend_doneDates");
             ^^^^^

SyntaxError: await is only valid in async function
    at Module._compile (internal/modules/cjs/loader.js:721:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at results.forEach.result (C:\Users\Paul\Desktop\Privé\nodejs\node_modules\bananenbase\src\load.js:67:17)
    at Array.forEach (<anonymous>)
    at fsscanner.scan (C:\Users\Paul\Desktop\Privé\nodejs\node_modules\bananen[nodemon] app crashed - waiting for file changes before starting...
C:\Users\Paul\AppData\Roaming\npm\node_modules\nodemon\lib\monitor\run.js:149
      if (child.__nodemonRestart) { // this flag is set right before the kill
                ^

TypeError: Cannot read property '__nodemonRestart' of null
    at Socket.child.stderr.on.s (C:\Users\Paul\AppData\Roaming\npm\node_modules\nodemon\lib\monitor\run.js:149:17)
    at Socket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at Pipe.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
```

---

### Nodemon dump content
```js
--------------
node: v10.16.0
nodemon: 2.0.1
command: C:\Program Files\nodejs\node.exe C:\Users\Paul\AppData\Roaming\npm\node_modules\nodemon\bin\nodemon.js --dump
cwd: C:\Users\Paul\Desktop\Privé\nodejs\Bots\CN-Bot
OS: win32 x64
--------------
{ run: false,
  system:
   { cwd: 'C:\\Users\\Paul\\Desktop\\Privé\\nodejs\\Bots\\CN-Bot' },
  required: false,
  dirs: [ 'C:\\Users\\Paul\\Desktop\\Privé\\nodejs\\Bots\\CN-Bot' ],
  timeout: 1000,
  options:
   { dump: true,
     ignore:
      [ '**/.git/**',
        '**/.nyc_output/**',
        '**/.sass-cache/**',
        '**/bower_components/**',
        '**/coverage/**',
        '**/node_modules/**',
        'package.json',
        'package-lock.json',
        'node_modules/*',
        'configstore.json',
        'database.sqlite',
        'index.js',
        re: /.*.*\/\.git\/.*.*|.*.*\/\.nyc_output\/.*.*|.*.*\/\.sass\-cache\/.*.*|.*.*\/bower_components\/.*.*|.*.*\/coverage\/.*.*|.*.*\/node_modules\/.*.*|package\.json|package\-lock\.json|node_modules\/.*|configstore\.json|database\.sqlite|index\.js/ ],
     main: 'bot.js',
     watch: [ '*.*', re: /.*\..*/ ],
     ignoreRoot:
      [ '**/.git/**',
        '**/.nyc_output/**',
        '**/.sass-cache/**',
        '**/bower_components/**',
        '**/coverage/**',
        '**/node_modules/**' ],
     restartable: 'rs',
     colours: true,
     execMap: { py: 'python', rb: 'ruby', ts: 'ts-node' },
     stdin: true,
     runOnChangeOnly: false,
     verbose: false,
     signal: 'SIGUSR2',
     stdout: true,
     watchOptions: {},
     execArgs: [],
     execOptions:
      { script: 'index.js',
        exec: 'node',
        args: [],
        scriptPosition: null,
        nodeArgs: undefined,
        execArgs: [],
        ext: 'js,mjs,json',
        env: {} },
     monitor:
      [ '*.*',
        '!**/.git/**',
        '!**/.nyc_output/**',
        '!**/.sass-cache/**',
        '!**/bower_components/**',
        '!**/coverage/**',
        '!**/node_modules/**',
        '!package.json',
        '!package-lock.json',
        '!node_modules/**/*',
        '!configstore.json',
        '!database.sqlite',
        '!index.js' ] },
  load: [Function],
  reset: [Function: reset],
  lastStarted: 0,
  loaded:
   [ 'C:\\Users\\Paul\\Desktop\\Privé\\nodejs\\Bots\\CN-Bot\\nodemon.json' ],
  watchInterval: null,
  signal: 'SIGUSR2',
  command:
   { raw: { executable: 'node', args: [ 'index.js' ] },
     string: 'node index.js' } }```

**Comment by remy** [comment]
This should be fixed and live in nodemon@2.0.2.

Shall close happy reopen if it's still an issue.
