### ISSUE TITLE
port being ocupied error on change. 

### ISSUE THREAD

**Issue by dev-dushyant** [remy/nodemon#1659]
- `nodemon -v`:2.0.2
- `node -v`:12.4.0
- Operating system/terminal environment: Ubuntu 18.04(pop_os distro)
- Using Docker? What image: No 
- Command you ran: nodemon server.js --dump

### Expected behavior
It should kill the process running on port 5000 (in this particular case) before reassigning a new process on change. 

### Actual behavior
I'm assuming it is not clearing process trace on port 5000 before the restart on change

### Steps to reproduce

---

If applicable, please append the `--dump` flag on your command and include the output here **ensuring to remove any sensitive/personal details or tokens**.
[nodemon] restarting due to changes...
[nodemon] starting `node ./api/server.js --debug`
events.js:177
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::5000
    at Server.setupListenHandle [as _listen2] (net.js:1226:14)
    at listenInCluster (net.js:1274:12)
    at Server.listen (net.js:1362:7)
    at Function.listen (/home/dushyant/Apps/the_beast/node_modules/express/lib/application.js:618:24)
    at Object.<anonymous> (/home/dushyant/Apps/the_beast/api/server.js:29:5)
    at Module._compile (internal/modules/cjs/loader.js:774:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
    at Module.load (internal/modules/cjs/loader.js:641:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:837:10)
    at internal/main/run_main_module.js:17:11
Emitted 'error' event at:
    at emitErrorNT (net.js:1253:8)
    at processTicksAndRejections (internal/process/task_queues.js:84:9) {
  code: 'EADDRINUSE',
  errno: 'EADDRINUSE',
  syscall: 'listen',
  address: '::',
  port: 5000
}

**Comment by remy** [comment]
Can you replicate with a small and simple code example?

**Comment by dev-dushyant** [comment]
@remy  It was an issue with my webpack config.

**Comment by the21st** [comment]
@dev-dushyant hey there, I'm having the same issue on my project. Can you share how you solved this? What was the issue with your webpack config? Thanks!
