### ISSUE TITLE
constant EADDRINUSE error

### ISSUE THREAD

**Issue by bassamanator** [remy/nodemon#1778]
- `nodemon -v`: 2.0.4
- `node -v`: v12.18.4
- Operating system/terminal environment: Manjaro/Termination(terminal for Atom)
- Using Docker? What image: 
- Command you ran: nodemon server.js

### Expected behaviour
Server.js should continue to run until I save it, then nodemon should reload server.js

### Actual behaviour
The app crashes. I have to then find the PID and kill it via **ps ax | grep 'node server'** then **kill pid#**
```
[nodemon] starting `node server.js`
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::5000
    at Server.setupListenHandle [as _listen2] (net.js:1313:16)
    at listenInCluster (net.js:1361:12)

    at Server.listen (net.js:1447:7)
    at Function.listen (/home/bassam/devconnector/node_modules/express/lib/applicati
on.js:618:24)
    at Object.<anonymous> (/home/bassam/devconnector/server.js:44:5)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:
12)
    at internal/main/run_main_module.js:17:47
Emitted 'error' event on Server instance at:
    at emitErrorNT (net.js:1340:8)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  code: 'EADDRINUSE',
  errno: 'EADDRINUSE',
  syscall: 'listen',
  address: '::',
  port: 5000
}
[nodemon] app crashed - waiting for file changes before starting...
```

### Steps to reproduce
Just hit save while app is running in Atom terminal (Termination is the package name) and I get this address in use error.

---

If applicable, please append the `--dump` flag on your command and include the output here **ensuring to remove any sensitive/personal details or tokens**.

**Comment by remy** [comment]
Please provide server.js in it's minimal form otherwise there's nothing I can do to help as this can't be replicated.

**Comment by bassamanator** [comment]
Nodemon was installed globally and I wondered if this might be causing an issue. I uninstalled it and then installed it as a dev dependency. Problem appears to be solved because I haven't gotten that error in recent testing. I'll report back if it comes up again.

Thanks for this utility!

**Comment by Emsun0211** [comment]
I am facing this same issue right now, I am running my app using "node server.js"
