### ISSUE TITLE
User arguments treated as nodemon options if they match an existing nodemon option

### ISSUE THREAD

**Issue by jamesastound** [remy/nodemon#1811]
- `nodemon -v`: 2.0.6
- `node -v`: v10.23.0
- Operating system/terminal environment: Ubuntu 18.04.5 LTS
- Command you ran: `nodemon a.js -d`

### Expected behaviour
- Execute script with argument `-d` passed to user script
- Command help indicates user arguments belong after script name: `Usage: nodemon [options] [script.js] [args]`

### Actual behaviour
nodeman parseDelay() in lib/cli/parse.js treats as a nodemon option

```/usr/lib/node_modules/nodemon/lib/cli/parse.js:220
  if (value.match(/^\d*ms$/)) {
            ^

TypeError: Cannot read property 'match' of undefined
    at parseDelay (/usr/lib/node_modules/nodemon/lib/cli/parse.js:220:13)
    at nodemonOption (/usr/lib/node_modules/nodemon/lib/cli/parse.js:168:21)
    at parse (/usr/lib/node_modules/nodemon/lib/cli/parse.js:81:11)
    at Object.parse (/usr/lib/node_modules/nodemon/lib/cli/index.js:47:12)
    at Object.<anonymous> (/usr/lib/node_modules/nodemon/bin/nodemon.js:5:21)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
```

### Steps to reproduce
- Match a user argument to an existing nodemon option and provide an incorrect parameter.

---

Thoughts are to add some try/catches to internal options handling. Even if the user argument is the same as nodemon's options,  the argument's parameters may be different. Would also be an opportunity to provide better help when a nodemon internal options encounters unexpected parameters.

I would think, arguments after the script name should not be parsed as options for nodemon. Unless there is a use case I am unaware of.  Thank you.

**Comment by remy** [comment]
This shouldn't crash, but if you want to pass `-d` to your script, you need `nodemon -- -d`

**Comment by jamesastound** [comment]
Thanks, @remy. I could also just not use one of nodemon's options :).  Seems unlikely someone would require using nodemon with a script they can't change. So I'd think this is relatively low priority. Just wanted to note the behavior. Appreciate the response.
