### ISSUE TITLE
PORT Address already in use (bug)

### ISSUE THREAD

**Issue by damiantoczek** [remy/nodemon#1837]
- `nodemon -v`: 2.0.6
- `node -v`: 15.6.0
- Operating system/terminal environment: Arch Linux
- Using Docker? What image: -
- Command you ran: nodemon

### Expected behaviour
Nothing should happen and maybe an console log with "No changes detected".

### Actual behaviour
When saving the same file with no changes, it shows a port in use error (it still works) but the error is unnecessary.

### Steps to reproduce
I use VScodium.
Open your project folder in VScodium then type nodemon, it will run the server that is specified as the entry point in the package.json.
Then you go to the in my case index.js file and press CTRL+S.
It will trigger log the PORT is in use error.

---

If applicable, please append the `--dump` flag on your command and include the output here **ensuring to remove any sensitive/personal details or tokens**.
```
[nodemon] 2.0.6
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,mjs,json
--------------
node: v15.6.0
nodemon: 2.0.6
command: /usr/bin/node /home/damian/.npm-global/bin/nodemon --dump
cwd: /home/damian/Documents/buildpc.org/server
OS: linux x64
--------------
{
  run: false,
  system: { cwd: '/home/user/project/server' },
  required: false,
  dirs: [ '/home/user/project/server' ],
  timeout: 1000,
  options: {
    dump: true,
    ignore: [
      '**/.git/**',
      '**/.nyc_output/**',
      '**/.sass-cache/**',
      '**/bower_components/**',
      '**/coverage/**',
      '**/node_modules/**',
      re: /.*.*\/\.git\/.*.*|.*.*\/\.nyc_output\/.*.*|.*.*\/\.sass\-cache\/.*.*|.*.*\/bower_components\/.*.*|.*.*\/coverage\/.*.*|.*.*\/node_modules\/.*.*/
    ],
    watch: [ '*.*', re: /.*\..*/ ],
    monitor: [
      '*.*',
      '!**/.git/**',
      '!**/.nyc_output/**',
      '!**/.sass-cache/**',
      '!**/bower_components/**',
      '!**/coverage/**',
      '!**/node_modules/**'
    ],
    ignoreRoot: [
      '**/.git/**',
      '**/.nyc_output/**',
      '**/.sass-cache/**',
      '**/bower_components/**',
      '**/coverage/**',
      '**/node_modules/**'
    ],
    restartable: 'rs',
    colours: true,
    execMap: { py: 'python', rb: 'ruby', ts: 'ts-node' },
    stdin: true,
    runOnChangeOnly: false,
    verbose: false,
    signal: 'SIGUSR2',
    stdout: true,
    watchOptions: {},
    execArgs: [],
    execOptions: {
      script: 'index.js',
      exec: 'node',
      args: [],
      scriptPosition: null,
      nodeArgs: undefined,
      execArgs: [],
      ext: 'js,mjs,json',
      env: {}
    }
  },
  load: [Function (anonymous)],
  reset: [Function: reset],
  lastStarted: 0,
  loaded: [],
  watchInterval: null,
  signal: 'SIGUSR2',
  command: {
    raw: { executable: 'node', args: [ 'index.js' ] },
    string: 'node index.js'
  }
}
--------------
```

**Comment by remy** [comment]
Please provide pared down code to replicate with, otherwise no one will be able to debug or even be able to think about debugging. 

ie. `require('http').createServer((r, R) => R.end()).listen(8000)` and the confirm *you can replicate* with pared down code, then submit here.

**Comment by damiantoczek** [comment]
Mine would be something like this:
```
const express = require('express')
const MongoClient = require('mongodb')
const app = express()

;(async function main(){
    const dbc = new MongoClient(process.env.DB_URI, {useNewUrlParser: true, useUnifiedTopology: true})
    const conn = await dbc.connect()
    
    app.listen(8080, () => console.log('Listen on port 8080'))
})()
```

It might be because of the async main function.

**Comment by remy** [comment]
Can you confirm that you've run this locally and you are able to replicate? Not _something_ like this, but *actually* that code.

**Comment by Oktogazh** [comment]
Same problem using the MEVN-CLI (PWA configuration) [boilerplate](https://github.com/madlabsinc/mevn-cli).
Anytime I Ctrl+S with Atom on my Kubuntu 20.4 system, I get this:
```
[nodemon] restarting due to changes...
[nodemon] starting `node server.js`
Listening On http://localhost:9000/api
events.js:292
      throw er; // Unhandled 'error' event
      ^


Error: listen EADDRINUSE: address already in use :::9000
    at Server.setupListenHandle [as _listen2] (net.js:1318:16)
    at listenInCluster (net.js:1366:12)
    at Server.listen (net.js:1452:7)
    at Function.listen (/home/name/folder/source/server/node_modules/express/lib/application.js:618:24)
    at Object.<anonymous> (/home/name/folder/source/server/server.js:45:5)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47
Emitted 'error' event on Server instance at:
    at emitErrorNT (net.js:1345:8)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  code: 'EADDRINUSE',
  errno: -98,
  syscall: 'listen',
  address: '::',
  port: 9000
}
[nodemon] app crashed - waiting for file changes before starting...
```
I'd then need to kill manually the process, say with `fuser 9000/tcp -k`.
Note that the problem does not occur if I use `rs` when there has been no changes in the source directory (except of course, if I change the listening port), fwiw.
But of course running `rs` doesn't help after any changes have been saved, one still need to kill the process using the port.
In comparison, everything works fine with pm2.

**Comment by remy** [comment]
Ta - closing  👍
