### ISSUE TITLE
nodemon version not compatible with windows 7 32 bit. Following error being displayed

### ISSUE THREAD

**Issue by ashu24012001** [remy/nodemon#1887]
This version of C:\Users\S K M U\AppData\Roaming\npm\node_modules\nodemon\bin\windows-kill.exe is not compatible with the version of Windows you're running. Check your computer's system information to see whether you need a x86 (32-bit) or x64 (64-bit) version of the program, and then contact the software publisher.
(node:5508) UnhandledPromiseRejectionWarning: Error: Command failed: start "windows-kill" /min /wait "C:\Users\S K M U\AppData\Roaming\npm\node_modules\nodemon\bin\windows-kill.exe" -SIGINT 2284
This version of C:\Users\S K M U\AppData\Roaming\npm\node_modules\nodemon\bin\windows-kill.exe is not compatible with the version of Windows you're running. Check your computer's system information to see whether you need a x86 (32-bit) or x64 (64-bit) version of the program, and then contact the software publisher.

    at checkExecSyncError (child_process.js:611:11)
    at execSync (child_process.js:647:15)
    at kill (C:\Users\S K M U\AppData\Roaming\npm\node_modules\nodemon\lib\monitor\run.js:360:5)
    at Function.run.kill (C:\Users\S K M U\AppData\Roaming\npm\node_modules\nodemon\lib\monitor\run.js:425:7)
    at Bus.<anonymous> (C:\Users\S K M U\AppData\Roaming\npm\node_modules\nodemon\lib\monitor\run.js:495:7)
    at Bus.emit (events.js:333:22)
    at restartBus (C:\Users\S K M U\AppData\Roaming\npm\node_modules\nodemon\lib\monitor\watch.js:228:7)
    at FSWatcher.filterAndRestart (C:\Users\S K M U\AppData\Roaming\npm\node_modules\nodemon\lib\monitor\watch.js:212:16)
    at FSWatcher.emit (events.js:321:20)
    at FSWatcher.emitWithAll (C:\Users\S K M U\AppData\Roaming\npm\node_modules\nodemon\node_modules\chokidar\index.js:540:8)
(node:5508) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)

**Comment by remy** [comment]
Please test with nodemon@2.0.10 - releasing now - so give it a minute.

It should fix this error (I'm closing as I'm pretty sure - but please ping me if it needs reopening).
