### ISSUE TITLE
Nodemon version not compatible with windows 7 32 bit OS

### ISSUE THREAD

**Issue by ashu24012001** [remy/nodemon#1888]
Server started running on port 3000
[nodemon] restarting due to changes...
This version of C:\Users\S K M U\AppData\Roaming\npm\node_modules\nodemon\bin\windows-kill.exe is not compatible with the version of Windows you're running. Check your computer's system information to see whether you need a x86 (32-bit) or x64 (64-bit) version of the program, and then contact the software publisher.
(node:2640) UnhandledPromiseRejectionWarning: Error: Command failed: start "windows-kill" /min /wait "C:\Users\S K M U\AppData\Roaming\npm\node_modules\nodemon\bin\windows-kill.exe" -SIGINT 7804
This version of C:\Users\S K M U\AppData\Roaming\npm\node_modules\nodemon\bin\windows-kill.exe is not compatible with the version of Windows you're running. Check your computer's system information to see whether you need a x86 (32-bit) or x64 (64-bit) version of the program, and then contact the software publisher.

    at checkExecSyncError (child_process.js:611:11)
    at execSync (child_process.js:647:15)
    at kill (C:\Users\S K M U\AppData\Roaming\npm\node_modules\nodemon\lib\monitor\run.js:360:5)
    at Function.run.kill (C:\Users\S K M U\AppData\Roaming\npm\node_modules\nodemon\lib\monitor\run.js:425:7)
    at Bus.<anonymous> (C:\Users\S K M U\AppData\Roaming\npm\node_modules\nodemon\lib\monitor\run.js:495:7)
    at Bus.emit (events.js:333:22)
    at restartBus (C:\Users\S K M U\AppData\Roaming\npm\node_modules\nodemon\lib\monitor\watch.js:228:7)
    at FSWatcher.filterAndRestart (C:\Users\S K M U\AppData\Roaming\npm\node_modules\nodemon\lib\monitor\watch.js:212:16)
    at FSWatcher.emit (events.js:321:20)
    at FSWatcher.emitWithAll (C:\Users\S K M U\AppData\Roaming\npm\node_modules\nodemon\node_modules\chokidar\index.js:540:8)
(node:2640) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:2640) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by remy** [comment]
You've just re-posted the same issue without actually saying anything about versions, etc.

**Comment by ashu24012001** [comment]
nodemon -v: 2.0.9
node -v: v13.6.0
Operating system: Windows 7 professional 32-bit

**Comment by remy** [comment]
So as per my previous message, please upgrade to 2.0.10. This addresses the issue you're seeing (as I said already).
