### ISSUE TITLE
UnhandledPromiseRejectionWarning when restarting

### ISSUE THREAD

**Issue by joshuasorkin** [remy/nodemon#1892]
- Versions: node@v14.16.1,win32,10.0.19042
- `nodemon -v`: 2.0.12
- Operating system/terminal environment (powershell, gitshell, etc): VS Code Terminal
- Using Docker? What image: N/A
- Command you ran:  

1. `nodemon app.js`
2.  In app.js, changed ``console.log(`Listening on port ${port}`)`` to ``console.log(`XYZListening on port ${port}`)``
3.  Saved app.js

### Expected behaviour
```
Listening on port 4001
[nodemon] restarting due to changes...
XYZListening on port 4001
```

### Actual behaviour
```
Listening on port 4001
[nodemon] restarting due to changes...
(node:16176) UnhandledPromiseRejectionWarning: Error: Command failed: wmic process where (ParentProcessId=18448) get ProcessId 2> nul
    at checkExecSyncError (child_process.js:616:11)
    at execSync (child_process.js:652:15)
    at kill (C:\Users\myusername\AppData\Roaming\npm\node_modules\nodemon\lib\monitor\run.js:345:26)
    at Function.run.kill (C:\Users\myusername\AppData\Roaming\npm\node_modules\nodemon\lib\monitor\run.js:437:7)
    at Bus.<anonymous> (C:\Users\myusername\AppData\Roaming\npm\node_modules\nodemon\lib\monitor\run.js:507:7)
    at Bus.emit (events.js:327:22)
    at restartBus (C:\Users\myusername\AppData\Roaming\npm\node_modules\nodemon\lib\monitor\watch.js:228:7)
    at FSWatcher.filterAndRestart (C:\Users\myusername\AppData\Roaming\npm\node_modules\nodemon\lib\monitor\watch.js:212:16)
    at FSWatcher.emit (events.js:315:20)
    at FSWatcher.emitWithAll (C:\Users\myusername\AppData\Roaming\npm\node_modules\nodemon\node_modules\chokidar\index.js:540:8)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:16176) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:16176) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate 
the Node.js process with a non-zero exit code.
```

### Steps to reproduce
(see "Command you ran")

---

If applicable, please append the `--dump` flag on your command and include the output here **ensuring to remove any sensitive/personal details or tokens**.

```
[nodemon] 2.0.12
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,mjs,json
--------------
node: v14.16.1
nodemon: 2.0.12
command: C:\Program Files\nodejs\node.exe C:\Users\myusername\AppData\Roaming\npm\node_modules\nodemon\bin\nodemon.js app.js --dump
cwd: C:\Users\myusername\Documents\Node projects\socket-io-server
OS: win32 x64
--------------
{
  run: false,
  system: {
    cwd: 'C:\\Users\\myusername\\Documents\\Node projects\\socket-io-server'
  },
  required: false,
  dirs: [ 'C:\\Users\\myusername\\Documents\\Node projects\\socket-io-server' ],
  timeout: 1000,
  options: {
    dump: true,
    ignore: [
      '**/.git/**',
      '**/.nyc_output/**',
      '**/.sass-cache/**',
      '**/bower_components/**',
      '**/coverage/**',
      '**/node_modules/**',
      re: /.*.*\/\.git\/.*.*|.*.*\/\.nyc_output\/.*.*|.*.*\/\.sass\-cache\/.*.*|.*.*\/bower_components\/.*.*|.*.*\/coverage\/.*.*|.*.*\/node_modules\/.*.*/   
    ],
    watch: [ '*.*', re: /.*\..*/ ],
    monitor: [
      '*.*',
      '!**/.git/**',
      '!**/.nyc_output/**',
      '!**/.sass-cache/**',
      '!**/bower_components/**',
      '!**/coverage/**',
      '!**/node_modules/**'
    ],
    ignoreRoot: [
      '**/.git/**',
      '**/.nyc_output/**',
      '**/.sass-cache/**',
      '**/bower_components/**',
      '**/coverage/**',
      '**/node_modules/**'
    ],
    restartable: 'rs',
    colours: true,
    execMap: { py: 'python', rb: 'ruby', ts: 'ts-node' },
    stdin: true,
    runOnChangeOnly: false,
    verbose: false,
    signal: 'SIGUSR2',
    stdout: true,
    watchOptions: {},
    execOptions: {
      script: 'app.js',
      exec: 'node',
      args: [],
      scriptPosition: 0,
      nodeArgs: undefined,
      execArgs: [],
      ext: 'js,mjs,json',
      env: {}
    }
  },
  load: [Function (anonymous)],
  reset: [Function: reset],
  lastStarted: 0,
  loaded: [],
  watchInterval: null,
  signal: 'SIGUSR2',
  command: {
    raw: { executable: 'node', args: [ 'app.js' ] },
    string: 'node app.js'
  }
}
```

**Comment by remy** [comment]
I can't replicate this at all.

<img width="1648" alt="Screenshot 2021-07-14 at 13 11 16" src="https://user-images.githubusercontent.com/13700/125619824-174a0922-870c-4318-a3a1-2bdcfdd3cdb8.png">

Can you try taking a screenshot in the same way I have? There's got to be a difference that we can track down.

**Comment by HARSH419** [comment]
> I can't replicate this at all.
> 
> <img alt="Screenshot 2021-07-14 at 13 11 16" width="1648" src="https://user-images.githubusercontent.com/13700/125619824-174a0922-870c-4318-a3a1-2bdcfdd3cdb8.png">
> 
> Can you try taking a screenshot in the same way I have? There's got to be a difference that we can track down.

I have Same issue And I upload a Screenshoot Also Visit there- https://github.com/nodejs/help/issues/3470

**Comment by remy** [comment]
Can we try with `nodemon@2.0.13-alpha.1` aka `npm install -g nodemon@debug` - I've moved the try/catch to a different point.

**Comment by Bikramghimire** [comment]
![Screenshot (129)](https://user-images.githubusercontent.com/43429038/128013063-cdcf8134-1dde-4fb1-8287-28c408317c44.png)
@remy why nodemon gives this error, at very first request it works but after it doesnot resend the request...

**Comment by Bikramghimire** [comment]
![Screenshot (131)](https://user-images.githubusercontent.com/43429038/128014166-1e5be108-d383-4d9b-a396-8d9aa69e4edf.png)
@remy i have used npm install -g nodemon@debug it doesn`t show error but still cannot refresh the content.....

**Comment by remy** [comment]
If you're still tracking this, can you replicate _outside_ of VS Code. It's not clear which terminal you're actually running, whether it's cmd, PS, git bash etc - and if I can't replicate (and since no one else is offering), I can't fix it.
