### ISSUE TITLE
EADDRINUSE in 2.0.12 version

### ISSUE THREAD

**Issue by DzenDyn** [remy/nodemon#1893]
Nodemon version 2.0.12 
run nodemon after change or rs i have error:
Error: listen EADDRINUSE: address already in use :::3007

`events.js:291
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::3007
    at Server.setupListenHandle [as _listen2] (net.js:1316:16)
    at listenInCluster (net.js:1364:12)
    at Server.listen (net.js:1450:7)
    at Object.<anonymous> (C:\Users\Nikiforov.Evgeny\Documents\projects\passport\bin\app.js:35:15)
    at Module._compile (internal/modules/cjs/loader.js:1256:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1277:10)
    at Module.load (internal/modules/cjs/loader.js:1105:32)
    at Function.Module._load (internal/modules/cjs/loader.js:967:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47
Emitted 'error' event on Server instance at:
    at emitErrorNT (net.js:1343:8)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  code: 'EADDRINUSE',
  errno: -4091,
  syscall: 'listen',
  address: '::',
  port: 3007
}
`

When i rollback to version 2.0.7 - i have no errors.

**Comment by remy** [comment]
Can you add in the prerequisite details in the initial issue - so I know what versions, etc (not the nodemon version).

**Comment by DzenDyn** [comment]
My package.json dependencies:
"dependencies": {
    "@babel/node": "^7.13.13",
    "body-parser": "^1.19.0",
    "connect": "^3.7.0",
    "cors": "^2.8.5",
    "dotenv": "^8.2.0",
    "express": "^4.17.1",
    "express-openapi-validator": "^4.12.6",
    "mongoose": "^5.12.2",
    "morgan": "^1.10.0",
    "swagger-routes-express": "^3.3.0",
    "swagger-ui-express": "^4.1.6",
    "uuid": "^8.3.2",
    "validator": "^13.5.2",
    "yamljs": "^0.3.0"
  },
  "devDependencies": {
    "@babel/cli": "^7.13.14",
    "@babel/core": "^7.13.14",
    "@babel/preset-env": "^7.13.12",
    "eslint": "^7.23.0",
    "eslint-config-airbnb-base": "^14.2.1",
    "eslint-config-prettier": "^8.1.0",
    "eslint-plugin-import": "^2.22.1",
    "eslint-plugin-prettier": "^3.3.1",
    "nodemon": "^2.0.12",
    "npm-run-all": "^4.1.5",
    "prettier": "^2.2.1",
    "rimraf": "^3.0.2"
    
    In that repo https://github.com/DzenDyn/hpt you can clone it and try with hpt-backend.
    With version 2.0.7 all ok, with 2.0.12 – error after rs or change in files.

**Comment by remy** [comment]
You're going to need to pare that down. Plus, I've not idea what hpt-backend is.

Also, I don't know what version of Windows or node you're using. Or what shell...

**Comment by DzenDyn** [comment]
Ok. I need some time to reproduce it in new clean project.

I have Node.js v14.7.0.
Windows 10 Version 1903 (Build 18362.239)

**Comment by DzenDyn** [comment]
I did it again.
app.js:
`import express from 'express';
const server = express();

server.use(express.urlencoded({ extended: true }));
server.use(express.json());

module.exports = server;


server.listen(3007, () => {
    console.info(
        'Listening on http://localhost\nOpen http://localhost/v1/api-docs for documentation'
    );
});
`
package.json: 
`  "dependencies": {
    "@babel/node": "^7.13.13",
    "express": "^4.17.1"
  },
  "devDependencies": {
    "@babel/cli": "^7.13.14",
    "@babel/core": "^7.13.14",
    "@babel/preset-env": "^7.13.12",
    "nodemon": "^2.0.12",
    "npm-run-all": "^4.1.5",
    "prettier": "^2.2.1",
    "rimraf": "^3.0.2"
  },
  "babel": {
    "presets": [
      "@babel/preset-env"
    ]
  },
  "scripts": {
    "transpile": "babel ./src --out-dir bin --copy-files",
    "clean": "rimraf bin",
    "build": "npm-run-all clean transpile",
    "server": "node ./bin/app.js",
    "dev": "npm-run-all build server",
    "start": "yarn dev",
    "watch": "nodemon"
  }`
  
  nodemon.json: 
  `{ 
    "watch": ["src/*"],
    "ext": "js, json, yaml",
    "exec": "yarn run dev"
}`
 
Steps to reproduce:
1. yarn watch
2. wait while server run
3. type rs and press enter or add some comment to app.js

**Comment by DzenDyn** [comment]
Simplified code and package.json to a minimum (1 post updated) and still run into error.

**Comment by remy** [comment]
Yeah, I can replicate now, but I strongly suspect it's because you've got nodemon on top of about 5 or 6 so nested processes. I'm just reworking the package undo that...

**Comment by DzenDyn** [comment]
Im clean and delete all of scripts and still run into error. Check 1 post – i edited it.

**Comment by DzenDyn** [comment]
Looks like it is windows only error. Cant reproduce it on ubuntu 20.04 and node version 16.5.0. Will try to update node on windows to 16.5.0 and test it again.

**Comment by remy** [comment]
ACK - will check with updated info 👍

**Comment by DzenDyn** [comment]
Checked windows 10, node 16.5.0 - same issue. Looks like its Windows only issue.

**Comment by HaeusslerAdrian** [comment]
I have a similar problem, but it exists since Version 2.0.8, and every following version. Did these versions work fine for you? @DzenDyn 
My problem also exists only on windows, my colleagues on linux & mac don't have that issue. (I'm trying to figure out if we have the same error or if I should create a new github-issue)

**Comment by DzenDyn** [comment]
> I have a similar problem, but it exists since Version 2.0.8, and every following version. Did these versions work fine for you? @DzenDyn
> My problem also exists only on windows, my colleagues on linux & mac don't have that issue. (I'm trying to figure out if we have the same error or if I should create a new github-issue)

Yes it started from 2.0.8. Looks like same issue

**Comment by levirs565** [comment]
You can fix this issue by downgrading nodemon to version 2.0.7.

**Comment by Aareksio** [comment]
Minimum reproduction (via npm) in repo for convenience: https://github.com/Aareksio/nodemon-bug-2.0.8

This is degradation between 2.0.7 and 2.0.8 (probably 500c1b06e8f3bbb2d407306e5f5411be9b09b9af).
Only breaks when launching script through middleman process (tested with npm, yarn, ts-node)

**Comment by DzenDyn** [comment]
@Aareksio one of solutions – migrate to wsl2, and run project into linux enviroment with latest nodemon, or downgrade to 2.0.7.
Looks like there is no security issue in 2.0.7

**Comment by remy** [comment]
Can we try with `nodemon@2.0.13-alpha.1` aka `npm install -g nodemon@debug` - I've moved the try/catch to a different point.

**Comment by DzenDyn** [comment]
@remy hello! Just tried. Ran into same error.

Node.js v16.5.0
express ^4.17.1
nodemon 2.0.13-alpha.1

![2 0 13-alpha 1](https://user-images.githubusercontent.com/5627754/127146385-e905ccbd-b84b-4fde-8152-bcb0a77a1ecf.png)

**Comment by remy** [comment]
@DzenDyn for my own sanity, can you strip yarn from the process and run only `nodemon app.js` (assuming you're testing with the example code)?

**Comment by Aareksio** [comment]
@remy https://github.com/Aareksio/nodemon-bug-2.0.8

#### 1. npm run dev -> nodemon
![image](https://user-images.githubusercontent.com/11166786/127201449-f5fd793f-1020-4ea1-8764-3190117940d0.png)

#### 2. npx nodemon index.js
![image](https://user-images.githubusercontent.com/11166786/127201823-cf5dfce9-a79c-43dd-84fa-7d37dcdfb2ea.png)

#### 3. nodemon index.js
![image](https://user-images.githubusercontent.com/11166786/127202311-c6f28618-92af-4e6c-8982-d176ca3c7a20.png)

**Comment by DzenDyn** [comment]
> @DzenDyn for my own sanity, can you strip yarn from the process and run only `nodemon app.js` (assuming you're testing with the example code)?

@remy i did it. And it works. 
But why? It worked with startup scripts earlier =\

**Comment by remy** [comment]
Okay, we're making some progress then. The "fix" that was put in place in 2.0.8 was specifically to handle spawned sub-processes, but it looks like in the cases you're seeing it's not actually stopping the process.

This is good though, it helps narrow the issue.

**Comment by remy** [comment]
Okay, I can finally replicate.

For the moment, can you both: @DzenDyn and @Aareksio test by removing the `exec` prop in your `nodemon.json` files - I think that's what is at play here.

**Comment by Aareksio** [comment]
@remy Yes, removing "exec" prop **does** work in the minimalistic example. It does not work on complex application though. Please consider `ts-node` for example.

**Comment by DzenDyn** [comment]
> @remy Yes, removing "exec" prop **does** work in the minimalistic example. What if we need more complex "exec" command though? For example we want to add `-r dotenv/config`.

@remy I confirm.

**Comment by remy** [comment]
> @remy Yes, removing "exec" prop **does** work in the minimalistic example. What if we need more complex "exec" command though? For example we want to add `-r dotenv/config`.

You can pass `-r` directly to nodemon, but that's not the point - now I know where to look for the issue and how to confirm any fixes.

**Comment by phibersoft** [comment]
I'm getting same error on V2.0.7 too.
Methods like "kill-port" work to get rid of this problem, but I'm happy to use the V1.19.4 for now.

**Comment by bennycode** [comment]
I recently upgraded nodemon from v2.0.7 (which worked just fine!) to v2.0.12. 

Now (with v2.0.12) I am seeing a lot of errors on Windows 10 when nodemon restarts my server:

```
Started server on port "3000".
Error: listen EADDRINUSE: address already in use 127.0.0.1:3000
    at Server.setupListenHandle [as _listen2] (node:net:1315:16)
    at listenInCluster (node:net:1363:12)
    at doListen (node:net:1501:7)
    at processTicksAndRejections (node:internal/process/task_queues:84:21) {
  code: 'EADDRINUSE',
  errno: -4091,
  syscall: 'listen',
  address: '127.0.0.1',
  port: 3000
}
```

Here is what my `nodemon.json` config looks like:

```json
{
  "exec": "yarn start:server",
  "ext": "ts",
  "signal": "SIGHUP"
}
```

And this is my `yarn start:server` command: 

```
"start:server": "ts-node src/start/startServer.ts"
```

The `startServer.ts` script does the following:

```ts
import 'dotenv-defaults/config';
import 'reflect-metadata';
import {NestServer} from '../server/NestServer';

async function start(): Promise<void> {
  const server = new NestServer();
  await server.start();
}

start().catch(error => {
  console.error(error);
  process.exit(1);
});
```

**Comment by cckelly** [comment]
I'm getting this on OSX too so I don't think it's exclusively Windows. Any update here?

**Comment by remy** [comment]
@cckelly this is not an OSX issue, see the history on the ticket - you're seeing similar result, but different reason.

**Comment by tindoescode** [comment]
> @remy [Aareksio/nodemon-bug-2.0.8](https://github.com/Aareksio/nodemon-bug-2.0.8)
> 
> The issue **is** with running the node script through proxy (such as npm, yarn or ts-node). It works well when calling `nodemon app.js` directly.
> 
> #### 1. npm run dev -> nodemon
> ![image](https://user-images.githubusercontent.com/11166786/127201449-f5fd793f-1020-4ea1-8764-3190117940d0.png)
> 
> #### 2. npx nodemon index.js
> ![image](https://user-images.githubusercontent.com/11166786/127202582-8c585d6a-ac0e-4a15-9343-e6c95a8bc89e.png)
> 
> The problem is in [this code](https://github.com/remy/nodemon/blob/main/lib/monitor/run.js?rgh-link-date=2021-07-27T17%3A44%3A22Z#L340-L353) finding proxy process - the **first** child, not the main script.

Solved my issue with:

```
"start": "nodemon app/index.js --exec babel-node app/index.js"
```

https://stackoverflow.com/questions/52674608/babel-transpiler-failing-to-run-with-nodemon
