### ISSUE TITLE
npm run dev issue

### ISSUE THREAD

**Issue by LinaAbuAlHassan-99** [remy/nodemon#1901]
npm run dev

> web-server@1.0.0 dev
> nodemon src/app.js -e js,hbs

exception in nodemon killing node
ReferenceError: primordials is not defined
    at fs.js:47:5
    at req_ (C:\Users\labualhassan\Desktop\NodeJS\Section-7_vedio9\query-strings\web-server\node_modules\natives\index.js:143:24)
    at Object.req [as require] (C:\Users\labualhassan\Desktop\NodeJS\Section-7_vedio9\query-strings\web-server\node_modules\natives\index.js:55:10)
    at Object.<anonymous> (C:\Users\labualhassan\Desktop\NodeJS\Section-7_vedio9\query-strings\web-server\node_modules\graceful-fs\fs.js:1:37)
    at Module._compile (node:internal/modules/cjs/loader:1109:14)
    at require (node:internal/modules/cjs/helpers:93:18)

----------------------------------------------------------
If appropriate, please file an error with the output from:
$ C:\Program Files\nodejs\node.exe C:\Users\labualhassan\Desktop\NodeJS\Section-7_vedio9\query-strings\web-server\node_modules\nodemon\bin\nodemon.js src/app.js -e js,hbs --dump
At http://github.com/remy/nodemon/issues/new
----------------------------------------------------------

**Comment by remy** [comment]
This is in your code, primordials is not part of nodemon.
