### ISSUE TITLE
Logical OR-Assignment-Operator not supported.

### ISSUE THREAD

**Issue by zwingliernst** [remy/nodemon#1929]
- Versions: node@v14.7.0, win32@10.0.19043
- `nodemon -v`: 2.0.13
- Operating system/terminal environment (powershell, gitshell, etc): Windows, VS Code, Node via package.json-Script 
- Using Docker? What image:  No
- Command you ran: "nodemon ./server/server.ts"

### Expected behaviour
Logical OR-Assignment operator to be supported by nodemon
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Logical_OR_assignment

### Actual behaviour
testobject.child ||= [];

at Module._compile (internal/modules/cjs/loader.js:1220:27)
    at Module.m._compile (\node_modules\ts-node\src\index.ts:814:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1277:10)
    at Object.require.extensions.<computed> [as .ts] (\node_modules\ts-node\src\index.ts:817:12)                                                    
    at Module.load (internal/modules/cjs/loader.js:1105:32)
    at Function.Module._load (internal/modules/cjs/loader.js:967:14)
    at Module.require (internal/modules/cjs/loader.js:1145:19)
    at require (internal/modules/cjs/helpers.js:75:18)
    at Object.<anonymous> (\server\server.ts:7:1)  

### Steps to reproduce
Have any function, that uses the logical OR-Assignment-Operator in Typescript

---

If applicable, please append the `--dump` flag on your command and include the output here **ensuring to remove any sensitive/personal details or tokens**.

**Comment by remy** [comment]
That's your code not in nodemon.

**Comment by zwingliernst** [comment]
> That's your code not in nodemon.

My code runs. The problem is only, that nodemon doesn't compile it.
