### ISSUE TITLE
primordials (poor example of issue report)

### ISSUE THREAD

**Issue by HadiScript** [remy/nodemon#2046]
primordials is not defined
    at fs.js:40:5
    at req_ (C:\Users\computer lab\Desktop\tickets\node_modules\natives\index.js:143:24)
    at Object.req [as require] (C:\Users\computer lab\Desktop\tickets\node_modules\natives\index.js:55:10)
    at Object.<anonymous> (C:\Users\computer lab\Desktop\tickets\node_modules\graceful-fs\fs.js:1:37)     
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)

**Comment by remy** [comment]
Provide code or repo.
