### ISSUE TITLE
tty.isatty returns false in the new version on nodemon

### ISSUE THREAD

**Issue by simonexmachina** [remy/nodemon#284]
The debug module uses `tty.isatty(2)` to choose whether to print coloured output. In the 1.0 version of nodemon this returns false.

**Comment by MehdiSaffar** [comment]
I am using `nodemon` 2.0.3 and I am trying to refresh a CLI tool I am building on changes. I am using `PyInquirer` for interactive console prompt. Launching the script with python causes no problems while launching with `nodemon` causes 

```
[nodemon] 2.0.3
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: py,json
[nodemon] starting `python ./try.py`
Traceback (most recent call last):
  File "./try.py", line 52, in <module>
    prompt(questions)
  File "/home/user/anaconda3/envs/ox/lib/python3.8/site-packages/PyInquirer/prompt.py", line 69, in prompt
    answer = run_application(
  File "/home/user/anaconda3/envs/ox/lib/python3.8/site-packages/prompt_toolkit/shortcuts.py", line 573, in run_application
    cli = CommandLineInterface(
  File "/home/user/anaconda3/envs/ox/lib/python3.8/site-packages/prompt_toolkit/interface.py", line 81, in __init__
    self.input = input or StdinInput(sys.stdin)
  File "/home/user/anaconda3/envs/ox/lib/python3.8/site-packages/prompt_toolkit/input.py", line 67, in __init__
    assert self.stdin.isatty()
AssertionError
[nodemon] app crashed - waiting for file changes before starting...
```

any idea how to solve this?
