### ISSUE TITLE
exception in nodemon killing node

### ISSUE THREAD

**Issue by abhishekverma3189** [remy/nodemon#302]
Error: read ECONNRESET
    at errnoException (net.js:904:11)
    at Pipe.onread (net.js:558:19)

**Comment by kittrCZ** [comment]
I'm seeing the same issue. Here is my dump:
```
8 May 14:16:18 - [nodemon] v1.3.7
8 May 14:16:18 - [nodemon] to restart at any time, enter `rs`
8 May 14:16:18 - [nodemon] watching: *.*
--------------
node: v0.12.2
nodemon: v1.3.7
command: node /home/hertus/.nvm/versions/node/v0.12.2/bin/nodemon --dump
cwd: /home/hertus/Gears/OAuth-Test/oauth-test
OS: linux ia32
--------------
{ run: false,
  system: 
   { cwd: '/home/hertus/Gears/OAuth-Test/oauth-test',
     useFind: true,
     useWatch: false,
     useWatchFile: false },
  required: false,
  dirs: [ '/home/hertus/Gears/OAuth-Test/oauth-test' ],
  timeout: 1000,
  options: 
   { dump: true,
     ignore: 
      [ '.git',
        'node_modules',
        'bower_components',
        '.sass-cache',
        re: /\.git|node_modules|bower_components|\.sass\-cache/ ],
     watch: [ '*.*', re: /.*\..*/ ],
     restartable: 'rs',
     execMap: { py: 'python', rb: 'ruby' },
     stdin: true,
     verbose: false,
     stdout: true,
     execOptions: 
      { script: './bin/www',
        exec: 'node',
        args: [],
        scriptPosition: 0,
        nodeArgs: undefined,
        ext: 'js',
        env: {},
        execArgs: [] },
     monitor: 
      [ '*.*',
        '!.git',
        '!/home/hertus/Gears/OAuth-Test/oauth-test/node_modules/**/*',
        '!bower_components',
        '!.sass-cache' ] },
  load: [Function],
  reset: [Function: reset],
  lastStarted: 0,
  loaded: [],
  command: 
   { raw: { executable: 'node', args: [ './bin/www' ] },
     string: 'node ./bin/www' },
  offset: 0 }
--------------
```
