### ISSUE TITLE
Occasional error "exception in nodemon killing node"

### ISSUE THREAD

**Issue by tillda** [remy/nodemon#356]
I occasionally get this weird error. It usually happens when I Ctrl+C a process and then start it right again. Sadly I can't trigger it on purepose to point to a failing case.

```
  exception in nodemon killing node
  TypeError: Cannot read property 'update' of null
      at Object.Configstore.get (/usr/local/lib/node_modules/nodemon/node_modules/update-notifier/node_modules/configstore/configstore.js:85:17)
      at UpdateNotifier.check (/usr/local/lib/node_modules/nodemon/node_modules/update-notifier/lib/update-notifier.js:50:28)
      at module.exports (/usr/local/lib/node_modules/nodemon/node_modules/update-notifier/lib/update-notifier.js:148:17)
      at Object.<anonymous> (/usr/local/lib/node_modules/nodemon/bin/nodemon.js:7:16)
      at Module._compile (module.js:456:26)
      at Object.Module._extensions..js (module.js:474:10)
      at Module.load (module.js:356:32)
      at Function.Module._load (module.js:312:12)
      at Function.Module.runMain (module.js:497:10)
      at startup (node.js:119:16)
```

The dump of the `node /usr/local/bin/nodemon --debug -w . -e js -- apiserver.js -p 6401 -e development --dump` command is below, though I had to move the `--dump` command to the beginning to make it work... (otherewise it says "error: unknown option `--dump'")

```
--------------
node: v0.10.28
nodemon: v1.2.0
command: node /usr/local/bin/nodemon --dump --debug -w . -e js -- apiserver.js -p 6401 -e development
cwd: /Users/michal/Projects/Monaco/apiserver
OS: darwin x64
--------------
{ run: false,
  system:
   { cwd: '/Users/michal/Projects/Monaco/apiserver',
     useFind: true,
     useWatch: false,
     useWatchFile: false },
  required: false,
  dirs: [ '/Users/michal/Projects/Monaco/apiserver' ],
  timeout: 1000,
  options:
   { scriptPosition: 1,
     dump: true,
     watch: [ '.', re: /\./ ],
     ext: 'js',
     script: 'apiserver.js',
     args: [ '--debug', '-p', '6401', '-e', 'development' ],
     ignore:
      [ '.git',
        'node_modules',
        'bower_components',
        '.sass-cache',
        re: /\.git|node_modules|bower_components|\.sass\-cache/ ],
     restartable: 'rs',
     execMap: { py: 'python', rb: 'ruby' },
     stdin: true,
     verbose: false,
     stdout: true,
     execOptions:
      { script: 'apiserver.js',
        exec: 'node',
        args: [ '--debug', '-p', '6401', '-e', 'development' ],
        nodeArgs: undefined,
        ext: 'js',
        env: {},
        execArgs: [] },
     monitor:
      [ '*.*',
        '!.git',
        '!/Users/michal/Projects/Monaco/apiserver/node_modules/**/*',
        '!bower_components',
        '!.sass-cache' ] },
  load: [Function],
  reset: [Function: reset],
  lastStarted: 0,
  loaded: [],
  command:
   { raw:
      { executable: 'node',
        args: [ '--debug', 'apiserver.js', '-p', '6401', '-e', 'development' ] },
     string: 'node --debug apiserver.js -p 6401 -e development' } }
```

**Comment by mateatslc** [comment]
Same here.

**Comment by mateatslc** [comment]
Just upgraded to v1.3.2, was on v1.2.1 till now. Will report back if errors persist.

**Comment by mateatslc** [comment]
Here is how I sorted it:
- installed the dev version with 'npm install -g nodemon@dev'
- refactored my code so to not trigger the same '--exec' statement by concurrent nodemons

Not sure if both needed though.
