### ISSUE TITLE
Problem installing nodemon

### ISSUE THREAD

**Issue by samholmes** [remy/nodemon#359]
I saw this message when running nodemon:

```
-----------------------------------------
Update available: 1.2.0 (current: 1.0.17)
Run npm update -g nodemon to update
-----------------------------------------
```

So I ran the command and got this:

```
npm WARN package.json exterminate@1.3.0 No repository field.
npm http GET https://registry.npmjs.org/nodemon
npm WARN package.json jsdom@0.5.1 No repository field.
npm WARN package.json jsdom@0.5.1 'repositories' (plural) Not supported.
npm WARN package.json Please pick one as the 'repository' field
npm WARN package.json connect-mongo@0.1.9 No repository field.
npm WARN package.json string@1.1.0 homepage field must be a string url. Deleted.
npm WARN package.json uglify-js@2.2.5 No repository field.
npm WARN package.json uglify-js@2.2.5 'repositories' (plural) Not supported.
npm WARN package.json Please pick one as the 'repository' field
npm WARN package.json sprintf@0.1.1 No repository field.
npm WARN package.json send@0.0.2 No repository field.
npm http 200 https://registry.npmjs.org/nodemon
npm WARN package.json fresh@0.0.1 No repository field.
npm WARN package.json formidable@1.0.11 No repository field.
npm WARN package.json range-parser@0.0.4 No repository field.
npm WARN package.json bytes@0.0.1 No repository field.
npm WARN package.json policyfile@0.0.4 No repository field.
npm WARN package.json policyfile@0.0.4 'repositories' (plural) Not supported.
npm WARN package.json Please pick one as the 'repository' field
npm WARN package.json fresh@0.1.0 No repository field.
npm WARN package.json send@0.1.0 No repository field.
npm WARN package.json methods@0.0.1 No repository field.
npm WARN package.json amdefine@0.0.4 No repository field.
npm WARN package.json JSV@4.0.2 No repository field.
npm WARN package.json JSV@4.0.2 'repositories' (plural) Not supported.
npm WARN package.json Please pick one as the 'repository' field
npm WARN package.json cookie-signature@1.0.1 No repository field.
npm WARN package.json eyes@0.1.8 No repository field.
npm WARN package.json github-url-from-git@1.1.1 No repository field.
npm WARN package.json callsite@1.0.0 No repository field.
npm WARN package.json rbytes@0.0.2 No repository field.
npm WARN package.json faye-websocket@0.4.0 No repository field.
npm WARN package.json faye-websocket@0.4.0 'repositories' (plural) Not supported.
npm WARN package.json Please pick one as the 'repository' field
npm WARN package.json hiredis@0.1.15 No repository field.
npm WARN package.json send@0.0.4 No repository field.
npm WARN package.json pause@0.0.1 No repository field.
npm WARN package.json bytes@0.1.0 No repository field.
npm WARN package.json bytes@0.2.1 No repository field.
npm WARN package.json uid2@0.0.3 No repository field.
npm WARN package.json batch@0.5.0 No repository field.
npm WARN package.json ctype@0.5.2 No repository field.
npm WARN package.json assert-plus@0.1.2 No repository field.
npm WARN package.json eventemitter2@0.4.11 'repositories' (plural) Not supported.
npm WARN package.json Please pick one as the 'repository' field
npm http GET https://registry.npmjs.org/nodemon/-/nodemon-1.2.0.tgz
npm http 200 https://registry.npmjs.org/nodemon/-/nodemon-1.2.0.tgz
npm http GET https://registry.npmjs.org/nodemon/1.2.0
npm http 200 https://registry.npmjs.org/nodemon/1.2.0
npm http GET https://registry.npmjs.org/nodemon/-/nodemon-1.2.0.tgz
npm http 200 https://registry.npmjs.org/nodemon/-/nodemon-1.2.0.tgz
npm ERR! error rolling back Error: EACCES, unlink '/usr/local/lib/node_modules/nodemon'
npm ERR! error rolling back  nodemon@1.2.0 { [Error: EACCES, unlink '/usr/local/lib/node_modules/nodemon']
npm ERR! error rolling back   errno: 3,
npm ERR! error rolling back   code: 'EACCES',
npm ERR! error rolling back   path: '/usr/local/lib/node_modules/nodemon' }
npm ERR! Error: EACCES, unlink '/usr/local/lib/node_modules/nodemon'
npm ERR!  { [Error: EACCES, unlink '/usr/local/lib/node_modules/nodemon']
npm ERR!   errno: 3,
npm ERR!   code: 'EACCES',
npm ERR!   path: '/usr/local/lib/node_modules/nodemon' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! System Darwin 13.2.0
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "update" "-g" "nodemon"
npm ERR! cwd /Users/holmes/Code/Foobar/backend
npm ERR! node -v v0.10.26
npm ERR! npm -v 1.2.32
npm ERR! path /usr/local/lib/node_modules/nodemon
npm ERR! code EACCES
npm ERR! errno 3
npm ERR! stack Error: EACCES, unlink '/usr/local/lib/node_modules/nodemon'
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/holmes/Code/Foobar/backend/npm-debug.log
npm ERR! not ok code 0
```

So then I tried it with `sudo`:

```
npm WARN package.json exterminate@1.3.0 No repository field.
npm WARN package.json connect-mongo@0.1.9 No repository field.
npm WARN package.json string@1.1.0 homepage field must be a string url. Deleted.
npm WARN package.json uglify-js@2.2.5 No repository field.
npm WARN package.json uglify-js@2.2.5 'repositories' (plural) Not supported.
npm WARN package.json Please pick one as the 'repository' field
npm WARN package.json send@0.0.2 No repository field.
npm WARN package.json jsdom@0.5.1 No repository field.
npm WARN package.json jsdom@0.5.1 'repositories' (plural) Not supported.
npm WARN package.json Please pick one as the 'repository' field
npm WARN package.json sprintf@0.1.1 No repository field.
npm http GET https://registry.npmjs.org/nodemon
npm WARN package.json bytes@0.0.1 No repository field.
npm WARN package.json formidable@1.0.11 No repository field.
npm WARN package.json fresh@0.0.1 No repository field.
npm WARN package.json range-parser@0.0.4 No repository field.
npm WARN package.json fresh@0.1.0 No repository field.
npm WARN package.json methods@0.0.1 No repository field.
npm WARN package.json send@0.1.0 No repository field.
npm WARN package.json policyfile@0.0.4 No repository field.
npm WARN package.json policyfile@0.0.4 'repositories' (plural) Not supported.
npm WARN package.json Please pick one as the 'repository' field
npm WARN package.json JSV@4.0.2 No repository field.
npm WARN package.json JSV@4.0.2 'repositories' (plural) Not supported.
npm WARN package.json Please pick one as the 'repository' field
npm WARN package.json amdefine@0.0.4 No repository field.
npm WARN package.json cookie-signature@1.0.1 No repository field.
npm WARN package.json eyes@0.1.8 No repository field.
npm WARN package.json github-url-from-git@1.1.1 No repository field.
npm WARN package.json bytes@0.1.0 No repository field.
npm WARN package.json pause@0.0.1 No repository field.
npm WARN package.json send@0.0.4 No repository field.
npm WARN package.json hiredis@0.1.15 No repository field.
npm WARN package.json callsite@1.0.0 No repository field.
npm WARN package.json assert-plus@0.1.2 No repository field.
npm WARN package.json ctype@0.5.2 No repository field.
npm WARN package.json eventemitter2@0.4.11 'repositories' (plural) Not supported.
npm WARN package.json Please pick one as the 'repository' field
npm WARN package.json faye-websocket@0.4.0 No repository field.
npm WARN package.json faye-websocket@0.4.0 'repositories' (plural) Not supported.
npm WARN package.json Please pick one as the 'repository' field
npm WARN package.json rbytes@0.0.2 No repository field.
npm WARN package.json batch@0.5.0 No repository field.
npm WARN package.json bytes@0.2.1 No repository field.
npm WARN package.json uid2@0.0.3 No repository field.
npm http 304 https://registry.npmjs.org/nodemon
npm http GET https://registry.npmjs.org/nodemon/1.2.0
npm http 304 https://registry.npmjs.org/nodemon/1.2.0
npm http GET https://registry.npmjs.org/update-notifier
npm http GET https://registry.npmjs.org/ps-tree
npm http GET https://registry.npmjs.org/minimatch
npm http 200 https://registry.npmjs.org/ps-tree
npm http GET https://registry.npmjs.org/ps-tree/-/ps-tree-0.0.3.tgz
npm http 200 https://registry.npmjs.org/minimatch
npm http 200 https://registry.npmjs.org/update-notifier
npm http GET https://registry.npmjs.org/update-notifier/-/update-notifier-0.1.10.tgz
npm http 200 https://registry.npmjs.org/ps-tree/-/ps-tree-0.0.3.tgz
npm http 200 https://registry.npmjs.org/update-notifier/-/update-notifier-0.1.10.tgz
npm http GET https://registry.npmjs.org/event-stream
npm http GET https://registry.npmjs.org/configstore
npm http GET https://registry.npmjs.org/semver
npm http GET https://registry.npmjs.org/chalk
npm http GET https://registry.npmjs.org/request
npm http GET https://registry.npmjs.org/lru-cache
npm http GET https://registry.npmjs.org/sigmund
npm http 200 https://registry.npmjs.org/configstore
npm ERR! Error: No compatible version found: configstore@'^0.3.0'
npm ERR! Valid install targets:
npm ERR! ["0.1.0","0.1.1","0.1.2","0.1.3","0.1.4","0.1.5","0.1.6","0.1.7","0.2.0","0.2.1","0.2.2","0.2.3","0.3.0","0.3.1"]
npm ERR!     at installTargetsError (/usr/local/lib/node_modules/npm/lib/cache.js:719:10)
npm ERR!     at /usr/local/lib/node_modules/npm/lib/cache.js:641:10
npm ERR!     at saved (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/get.js:138:7)
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Darwin 13.2.0
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "update" "-g" "nodemon"
npm ERR! cwd /Users/holmes/Code/Foobar/backend
npm ERR! node -v v0.10.26
npm ERR! npm -v 1.2.32
npm http 200 https://registry.npmjs.org/chalk
npm http 200 https://registry.npmjs.org/semver
npm http 304 https://registry.npmjs.org/lru-cache
npm http 304 https://registry.npmjs.org/sigmund
npm http 200 https://registry.npmjs.org/event-stream
npm http GET https://registry.npmjs.org/event-stream/-/event-stream-0.5.3.tgz
npm WARN package.json Foobar-backend@0.0.0 No repository field.
npm WARN package.json Foobar-backend@0.0.0 No readme data.
npm http 200 https://registry.npmjs.org/request
npm http 200 https://registry.npmjs.org/event-stream/-/event-stream-0.5.3.tgz
npm http GET https://registry.npmjs.org/optimist
npm http 200 https://registry.npmjs.org/optimist
npm http GET https://registry.npmjs.org/optimist/-/optimist-0.2.8.tgz
npm http 200 https://registry.npmjs.org/optimist/-/optimist-0.2.8.tgz
npm http GET https://registry.npmjs.org/wordwrap
npm http 304 https://registry.npmjs.org/wordwrap
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/holmes/Code/Foobar/backend/npm-debug.log
npm ERR! not ok code 0
```

It looks like a dependency issue. Would you know what this means @remy ?

**Comment by remy** [comment]
Did you get any further with this?

**Comment by samholmes** [comment]
I don't recall whether it was the patches you made that fixed this (I believe it was). But I'm running version 1.2.0 now of nodemon just fine! :+1: 

PS: While writing this I also was able to update to 1.3.2
