### ISSUE TITLE
when nodemon restart app, docker exit

### ISSUE THREAD

**Issue by prugel** [remy/nodemon#385]
docker nodejs with nodemon.
when some file change nodemon restart 
then docker exit. 

nodemon version 1.2.1

with docker (just change app.js, no error)

```
29 Aug 02:08:06 - [nodemon] restarting due to changes...
exception in nodemon killing node
Error: spawn ENOENT
    at errnoException (child_process.js:1001:11)
    at Process.ChildProcess._handle.onexit (child_process.js:792:34)

----------------------------------------------------------
module.js:340
    throw err;
          ^
Error: Cannot find module '/usr/local/bin/nodemon'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3
----------------------------------------------------------
```

without docker (just change, no error)

```
29 Aug 11:12:05 - [nodemon] restarting due to changes...
29 Aug 11:12:06 - [nodemon] starting `node app.js -L`
js-bson: Failed to load c++ bson extension, using pure JS version
Server started at: http://localhost:8080
 - Mongodb is connected
```

**Comment by WooDzu** [comment]
I'm having the same issue. My base image is `debian:wheezy`

```shell
api_1   | 28 Mar 08:15:19 - [nodemon] v1.3.7
api_1   | 28 Mar 08:15:19 - [nodemon] to restart at any time, enter `rs`
api_1   | 28 Mar 08:15:19 - [nodemon] watching: *.*
api_1   | 28 Mar 08:15:19 - [nodemon] starting `node index.js`
api_1   | [Error: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.14' not found (required by /api/node_modules/mongoose/node_modules/mongodb/node_modules/bson/build/Release/bson.node)]
api_1   | js-bson: Failed to load c++ bson extension, using pure JS version
```

After updating a file:

```shell
api_1   | 28 Mar 08:15:47 - [nodemon] restarting due to changes...
```
It does not restart and no further `restarting due to changes..` notifications appear.
I mount the whole application via volume. My docker-compose.yml

```yml
api:
  build: api
  volumes:
    - ./api:/api
  working_dir: /api/
  command: "node node_modules/nodemon/bin/nodemon"
```

**Comment by remy** [comment]
Do you have `kill -SIGHUP` on the system? I've noticed dockers that are so
cut down don't include the kill signals so you can't actually restart. Its
a weird edge case, but I hit it with the node:slim docker.

**Comment by WooDzu** [comment]
> Do you have `kill -SIGHUP` on the system?
Yes

I've also just noticed that it does work as expected unless I run additional linked container, which include the same base distro image with ember-cli tool - this runs it's own fs watcher with life reload. 

Although both containers use different volumes there must be some kind of conflict between these two which is behind my understanding. But will keep digging

**Comment by creativelikeadog** [comment]
Same here,

```
[nodemon] v1.2.1
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: /usr/src/app/**/*
[nodemon] starting `node main.js`
App server listening on port 8000
[nodemon] restarting due to changes...
Fatal error: spawn ENOENT
```

**Comment by WooDzu** [comment]
Hi @creativelikeadog
What's your Dockerfile (or docker-compose.yml)?

**Comment by creativelikeadog** [comment]
nodemon.json
```
{
  "restartable": "rs",
  "ignore": [
    ".git",
    "node_modules/**/node_modules"
  ],
  "verbose": true,
  "execMap": {
    "js": "node --harmony"
  },
  "watch": [
    "*.*"
  ],
  "env": {
    "NODE_ENV": "development"
  },
  "ext": "js json"
}
```
Dockerfile
```
FROM google/debian:wheezy

RUN apt-get update -y && apt-get install --no-install-recommends -y -q curl python build-essential git ca-certificates
RUN mkdir /nodejs && curl http://nodejs.org/dist/v0.10.25/node-v0.10.25-linux-x64.tar.gz | tar xvzf - -C /nodejs --strip-components=1

ENV PATH $PATH:/nodejs/bin

WORKDIR /usr/src/app/

RUN npm install -g grunt grunt-cli nodemon --unsafe-perm

EXPOSE 8000

COPY ./entrypoint.sh /
ENTRYPOINT ["/entrypoint.sh"]
CMD [ "nodemon", "main.js" ]
```

docker-compose.yml
```
node:
 build: '.'
 ports:
  - '8000:8000'
 volumes:
  - /etc/localtime:/etc/localtime:ro
  - ./src/:/usr/src/app/
```

**Comment by WooDzu** [comment]
After some more digging I figured what was missing:

`apt-get install -y procps`

apparently `ps` is required by `ps-tree` but it isn't shipped with wheezy by default.

**Comment by creativelikeadog** [comment]
@WooDzu Wow thnxs a lot i'll try
