### ISSUE TITLE
exception in nodemon killing node

### ISSUE THREAD

**Issue by ilijamt** [remy/nodemon#390]
After a while of running it crashes with

```
exception in nodemon killing node
TypeError: Cannot read property 'pid' of null
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/nodemon/lib/monitor/run.js:135:46)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:755:16)
    at Process.ChildProcess._handle.onexit (child_process.js:822:5)
```

$ node /usr/local/bin/nodemon worker.js --dump
```
18 Sep 19:32:42 - [nodemon] v1.2.1
18 Sep 19:32:42 - [nodemon] to restart at any time, enter `rs`
18 Sep 19:32:42 - [nodemon] watching: *.*
--------------
node: v0.10.29
nodemon: v1.2.1
command: node /usr/local/bin/nodemon worker.js --dump
cwd: /home/user/workspace/static/hub
OS: linux x64
--------------
{ run: false,
  system: 
   { cwd: '/home/user/workspace/static/hub',
     useFind: false,
     useWatch: true,
     useWatchFile: false },
  required: false,
  dirs: [ '/home/user/workspace/static/hub' ],
  timeout: 1000,
  options: 
   { scriptPosition: 0,
     dump: true,
     script: 'worker.js',
     args: [],
     verbose: false,
     ext: 'js',
     ignore: 
      [ '*.test.js',
        'public/*',
        'node_modules/*',
        'gulp/*',
        '.git',
        '.git/*',
        '.idea/*',
        'tools/*',
        'compile/*',
        'configuration/*',
        'keys/*',
        re: /.*\.test\.js|public/.*|node_modules/.*|gulp/.*|\.git|\.git/.*|\.idea/.*|tools/.*|compile/.*|configuration/.*|keys/.*/ ],
     watch: [ '*.*', re: /.*\..*/ ],
     restartable: 'rs',
     execMap: { py: 'python', rb: 'ruby' },
     stdin: true,
     stdout: true,
     execOptions: 
      { script: 'worker.js',
        exec: 'node',
        args: [],
        nodeArgs: undefined,
        ext: 'js',
        env: {},
        execArgs: [] },
     monitor: 
      [ '*.*',
        '!*.test.js',
        '!public/**/*',
        '!node_modules/**/*',
        '!gulp/**/*',
        '!/home/user/workspace/static/hub/.git/**/*',
        '!.git/**/*',
        '!.idea/**/*',
        '!tools/**/*',
        '!compile/**/*',
        '!configuration/**/*',
        '!keys/**/*' ] },
  load: [Function],
  reset: [Function: reset],
  lastStarted: 0,
  loaded: [ '/home/user/workspace/static/hub/nodemon.json' ],
  command: 
   { raw: { executable: 'node', args: [ 'worker.js' ] },
     string: 'node worker.js' } }
--------------
```

**Comment by edi9999** [comment]
Same thing happens to me after a while, seems to be random, I don't know when it is started

**Comment by remy** [comment]
Can you bump to `npm install -g nodemon@latest` this issue has been fixed (it was trying to look up the pid from `null`).
