### ISSUE TITLE
run nodemon on linux failed

### ISSUE THREAD

**Issue by wcccode** [remy/nodemon#391]
exception in nodemon killing node
Error: watch ENOSYS
    at errnoException (fs.js:1030:11)
    at FSWatcher.start (fs.js:1062:11)
    at Object.fs.watch (fs.js:1087:11)
    at Function.check (/usr/local/lib/node_modules/nodemon/lib/config/watchable.js:39:6)
    at alternativeCheck (/usr/local/lib/node_modules/nodemon/lib/config/checkWatchSupport.js:33:15)
    at checkWatchSupport (/usr/local/lib/node_modules/nodemon/lib/config/checkWatchSupport.js:62:5)
    at /usr/local/lib/node_modules/nodemon/lib/config/index.js:74:5
    at normaliseRules (/usr/local/lib/node_modules/nodemon/lib/config/load.js:119:3)
    at ready (/usr/local/lib/node_modules/nodemon/lib/config/load.js:60:9)
    at /usr/local/lib/node_modules/nodemon/lib/config/load.js:72:13

**Comment by remy** [comment]
Can you give this another test with the lastest version of nodemon 1.3.x?

**Comment by remy** [comment]
Closing - idle.
