### ISSUE TITLE
Nodemon throws ECONNRESET exception when entering rs

### ISSUE THREAD

**Issue by bobbysciacchitano** [remy/nodemon#397]
I'm running Nodemon on Vagrant and when I hit RS, I get the following errors:

```
vagrant@homestead:~/herenowaway$ nodemon server.js 
30 Sep 12:14:28 - [nodemon] v1.2.1
30 Sep 12:14:28 - [nodemon] to restart at any time, enter `rs`
30 Sep 12:14:28 - [nodemon] watching: *.*
30 Sep 12:14:28 - [nodemon] starting `node server.js`
Listening on port 3000

rs
exception in nodemon killing node
Error: read ECONNRESET
    at errnoException (net.js:904:11)
    at Pipe.onread (net.js:558:19)

----------------------------------------------------------
If appropriate, please file an error with the output from:
$ node /usr/bin/nodemon server.js --dump
At http://github.com/remy/nodemon/issues/new
----------------------------------------------------------
vagrant@homestead:~/herenowaway$ node /usr/bin/nodemon server.js --dump
30 Sep 12:14:39 - [nodemon] v1.2.1
30 Sep 12:14:39 - [nodemon] to restart at any time, enter `rs`
30 Sep 12:14:39 - [nodemon] watching: *.*
--------------
node: v0.10.29
nodemon: v1.2.1
command: node /usr/bin/nodemon server.js --dump
cwd: /home/vagrant/herenowaway
OS: linux x64
--------------
{ run: false,
  system: 
   { cwd: '/home/vagrant/herenowaway',
     useFind: false,
     useWatch: true,
     useWatchFile: false },
  required: false,
  dirs: [ '/home/vagrant/herenowaway' ],
  timeout: 1000,
  options: 
   { scriptPosition: 0,
     dump: true,
     script: 'server.js',
     args: [],
     ignore: 
      [ '.git',
        'node_modules',
        'bower_components',
        '.sass-cache',
        re: /\.git|node_modules|bower_components|\.sass\-cache/ ],
     watch: [ '*.*', re: /.*\..*/ ],
     restartable: 'rs',
     execMap: { py: 'python', rb: 'ruby' },
     stdin: true,
     verbose: false,
     stdout: true,
     execOptions: 
      { script: 'server.js',
        exec: 'node',
        args: [],
        nodeArgs: undefined,
        ext: 'js',
        env: {},
        execArgs: [] },
     ext: 'js',
     monitor: 
      [ '*.*',
        '!/home/vagrant/herenowaway/.git/**/*',
        '!/home/vagrant/herenowaway/node_modules/**/*',
        '!bower_components',
        '!.sass-cache' ] },
  load: [Function],
  reset: [Function: reset],
  lastStarted: 0,
  loaded: [],
  command: 
   { raw: { executable: 'node', args: [ 'server.js' ] },
     string: 'node server.js' } }
--------------
```

**Comment by AlgoTrader** [comment]
The same

Express server listening on port 3000
rs
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: read ECONNRESET
    at exports._errnoException (util.js:742:11)
    at Pipe.onread (net.js:535:26)

Any ideas?

**Comment by remy** [comment]
@AlgoTrader are you also running inside of Vagrant?

**Comment by AlgoTrader** [comment]
Nope. It's linode virtual machine, they use XEN I think. The bug is not stable - sometimes rs works, sometimes not

**Comment by archgrove** [comment]
I'm also having this problem, inside a Vagrant box. Inside the box, it fails:

    16 Jan 15:18:46 - [nodemon] starting `node server.js`
    rs
    exception in nodemon killing node
    Error: read ECONNRESET
        at errnoException (net.js:904:11)
        at Pipe.onread (net.js:558:19)

Outside the box, everything's fine.

**Comment by GongT** [comment]
+1

I use nodemon in a bash script like:

> init A
init B
blabla...
**nodemon --config ./nodemon.json -x /usr/local/bin/node -- dist/server.js**

nodemon.json:
```json
{
	"restartable": "rs",
	"ignore": [
		".git",
		".idea",
		".jsonenv",
		"logs",
		"node_modules",
		"jspm_packages",
		".npm",
		"typings"
	],
	"verbose": false,
	"execMap": {
		"js": "node --harmony"
	},
	"events": {
		"restart": "echo -e '\\n-------------------restart-------------------\\n'"
	},
	"ext": "js json"
}
```
