### ISSUE TITLE
exception in nodemon killing node

### ISSUE THREAD

**Issue by VikramTiwari** [remy/nodemon#403]
```
exception in nodemon killing node
Error: watch EMFILE
    at errnoException (fs.js:1019:11)
    at FSWatcher.start (fs.js:1051:11)
    at Object.fs.watch (fs.js:1076:11)
    at Function.check (/usr/lib/node_modules/nodemon/lib/config/watchable.js:39:6)
    at alternativeCheck (/usr/lib/node_modules/nodemon/lib/config/checkWatchSupport.js:33:15)
    at checkWatchSupport (/usr/lib/node_modules/nodemon/lib/config/checkWatchSupport.js:62:5)
    at /usr/lib/node_modules/nodemon/lib/config/index.js:74:5
    at normaliseRules (/usr/lib/node_modules/nodemon/lib/config/load.js:119:3)
    at ready (/usr/lib/node_modules/nodemon/lib/config/load.js:60:9)
    at /usr/lib/node_modules/nodemon/lib/config/load.js:72:13

----------------------------------------------------------
If appropriate, please file an error with the output from:
$ node /usr/bin/nodemon --debug ./server.js --dump
At http://github.com/remy/nodemon/issues/new
----------------------------------------------------------

27 Oct 11:03:36 - [nodemon] v1.2.1
27 Oct 11:03:36 - [nodemon] to restart at any time, enter `rs`
27 Oct 11:03:36 - [nodemon] watching: *.*
--------------
node: v0.10.28
nodemon: v1.2.1
command: node /usr/bin/nodemon --debug ./server.js --dump
cwd: /home/ubuntu/xxx/yyy
OS: linux x64
--------------
{ run: false,
  system:
   { cwd: '/home/ubuntu/xxx/yyy',
     useFind: false,
     useWatch: false,
     useWatchFile: true },
  required: false,
  dirs: [ '/home/ubuntu/xxx/yyy' ],
  timeout: 1000,
  options:
   { scriptPosition: 1,
     dump: true,
     script: './server.js',
     args: [ '--debug' ],
     ignore:
      [ '.git',
        'node_modules',
        'bower_components',
        '.sass-cache',
        re: /\.git|node_modules|bower_components|\.sass\-cache/ ],
     watch: [ '*.*', re: /.*\..*/ ],
     restartable: 'rs',
     execMap: { py: 'python', rb: 'ruby' },
     stdin: true,
     verbose: false,
     stdout: true,
     execOptions:
      { script: './server.js',
        exec: 'node',
        args: [ '--debug' ],
        nodeArgs: undefined,
        ext: 'js',
        env: {},
        execArgs: [] },
     ext: 'js',
     monitor:
      [ '*.*',
        '!.git',
        '!/home/ubuntu/xxx/yyy/node_modules/**/*',
        '!bower_components',
        '!.sass-cache' ] },
  load: [Function],
  reset: [Function: reset],
  lastStarted: 0,
  loaded: [],
  command:
   { raw: { executable: 'node', args: [ '--debug', './server.js' ] },
     string: 'node --debug ./server.js' } }
--------------
```

PS: There are no nodemon processes currently running.

**Comment by remy** [comment]
This is all released to stable now at 1.3.x so feel free to install `npm install -g nodemon@latest` now.

**Comment by tomekwi** [comment]
I had a similar issue with 1.3.7 – what helped was robooting.

Is it possible that it had something to do with too high PIDs of new processes? I noticed they were well over 30000 after my computer had been on for a couple of days.

**Comment by tomekwi** [comment]
I've just realized that [webpack-dev-server](#https://github.com/webpack/webpack-dev-server) – another project which watches the filesystem for changes – also failed to spot any changes back then. Rebooting fixed that issue as well.
