### ISSUE TITLE
Error: ENOENT, no such file or directory 'C:\Python27\Lib\nodemonCheckFsWatch12cd5def4f8eb8cb3ccc280ab6ffa38f'

### ISSUE THREAD

**Issue by AayushShrestha** [remy/nodemon#442]
haven't been able to run nodemon on windows. It crashes everytime with the following message

```
exception in nodemon killing node
Error: ENOENT, no such file or directory 'C:\Users\Aayush\AppData\Local\Temp;C:\
Python27;C:\Python27\Lib\nodemonCheckFsWatch12cd5def4f8eb8cb3ccc280ab6ffa38f'
    at Object.fs.openSync (fs.js:438:18)
    at Function.check (C:\Users\Aayush\AppData\Roaming\npm\node_modules\nodemon\
lib\config\watchable.js:33:18)
    at alternativeCheck (C:\Users\Aayush\AppData\Roaming\npm\node_modules\nodemo
n\lib\config\checkWatchSupport.js:33:15)
    at checkWatchSupport (C:\Users\Aayush\AppData\Roaming\npm\node_modules\nodem
on\lib\config\checkWatchSupport.js:62:5)
    at C:\Users\Aayush\AppData\Roaming\npm\node_modules\nodemon\lib\config\index
.js:74:5
    at normaliseRules (C:\Users\Aayush\AppData\Roaming\npm\node_modules\nodemon\
lib\config\load.js:119:3)
    at ready (C:\Users\Aayush\AppData\Roaming\npm\node_modules\nodemon\lib\confi
g\load.js:60:9)
    at C:\Users\Aayush\AppData\Roaming\npm\node_modules\nodemon\lib\config\load.
js:72:13
    at C:\Users\Aayush\AppData\Roaming\npm\node_modules\nodemon\lib\config\load.
js:103:7
    at Object.cb [as oncomplete] (fs.js:168:19)
```

I tried uninstalling and reinstalling. Clearing cache and everything. Nothing seems to work.

**Comment by lostPixels** [comment]
Just wondering what you changed, cause I am getting this error too!

**Comment by AayushShrestha** [comment]
@lostPixels  I had a non existing folder set in my TEMP environment variable. Fixing that solved the issue.
