### ISSUE TITLE
Nodemon not starting lcm for locomotive 

### ISSUE THREAD

**Issue by crispen-smith** [remy/nodemon#480]
While I'm still a little confused about exactly what I'm experiencing as I've seen some automatic restarts on prior runs I keep seeing an error message and am getting inconsistent watch states.  

Here's dump from shell on the last run.

```
Crispens-MacBook-Pro:site crispensmith$ sudo nodemon node_modules/locomotive/bin/lcm server
24 Jan 13:04:40 - [nodemon] v1.3.2
24 Jan 13:04:40 - [nodemon] to restart at any time, enter `rs`
24 Jan 13:04:40 - [nodemon] watching: *.*
24 Jan 13:04:40 - [nodemon] starting `node_modules/locomotive/bin/lcm node_modules/locomotive/bin/lcm server server`
sh: node_modules/locomotive/bin/lcm: No such file or directory
[nodemon] failed to start process, "node_modules/locomotive/bin/lcm" exec not found
exception in nodemon killing node
TypeError: Uncaught, unspecified "error" event.
    at TypeError (<anonymous>)
    at emit (events.js:74:15)
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/nodemon/lib/monitor/run.js:112:11)
    at ChildProcess.emit (events.js:98:17)
    at Process.ChildProcess._handle.onexit (child_process.js:810:12)

----------------------------------------------------------
If appropriate, please file an error with the output from:
$ node /usr/local/bin/nodemon node_modules/locomotive/bin/lcm server --dump
At http://github.com/remy/nodemon/issues/new
----------------------------------------------------------

Crispens-MacBook-Pro:site crispensmith$ sudo node /usr/local/bin/nodemon node_modules/locomotive/bin/lcm server --dump
24 Jan 13:04:51 - [nodemon] v1.3.2
24 Jan 13:04:51 - [nodemon] to restart at any time, enter `rs`
24 Jan 13:04:51 - [nodemon] watching: *.*
--------------
node: v0.10.30
nodemon: v1.3.2
command: node /usr/local/bin/nodemon node_modules/locomotive/bin/lcm server --dump
cwd: /Users/crispensmith/Documents/cinchedStore/Site
OS: darwin x64
--------------
{ run: false,
  system: 
   { cwd: '/Users/crispensmith/Documents/cinchedStore/Site',
     useFind: true,
     useWatch: false,
     useWatchFile: false },
  required: false,
  dirs: [ '/Users/crispensmith/Documents/cinchedStore/Site' ],
  timeout: 1000,
  options: 
   { dump: true,
     ignore: 
      [ '.git',
        'node_modules',
        'bower_components',
        '.sass-cache',
        re: /\.git|node_modules|bower_components|\.sass\-cache/ ],
     watch: [ '*.*', re: /.*\..*/ ],
     restartable: 'rs',
     execMap: { py: 'python', rb: 'ruby' },
     stdin: true,
     verbose: false,
     stdout: true,
     execOptions: 
      { script: 'server',
        exec: 'node_modules/locomotive/bin/lcm',
        args: [ 'node_modules/locomotive/bin/lcm', 'server' ],
        scriptPosition: 2,
        nodeArgs: undefined,
        ext: 'js',
        env: {},
        execArgs: [] },
     monitor: 
      [ '*.*',
        '!.git',
        '!/Users/crispensmith/Documents/cinchedStore/Site/node_modules/**/*',
        '!bower_components',
        '!.sass-cache' ] },
  load: [Function],
  reset: [Function: reset],
  lastStarted: 0,
  loaded: [],
  command: 
   { raw: 
      { executable: 'node_modules/locomotive/bin/lcm',
        args: [ 'node_modules/locomotive/bin/lcm', 'server', 'server' ] },
     string: 'node_modules/locomotive/bin/lcm node_modules/locomotive/bin/lcm server server' } }
--------------

Crispens-MacBook-Pro:site crispensmith$ 
Crispens-MacBook-Pro:site crispensmith$ sudo node node_modules/locomotive/bin/lcm server
CLI ENV: development
Locomotive 0.4.2 application starting in development on http://0.0.0.0:3000
HTTP server listening on 0.0.0.0:3000
```

WHat's really confusing to me is that the final sudo node... was generated by recalling the original nodemon command from shell history and deleting the "mon" portion of nodemon.  

Is there a config setup that avoids this?

**Comment by remy** [comment]
Okay, I can see what's going wrong here, but I'm not 100% sure why. I'll see if I can replicate using a simplified test and get a fix up.

**Comment by remy** [comment]
Hmm. I'm struggling to replicate this. I installed `lcm` and ran their [hello world](http://locomotivejs.org/guide/get-started/) demo but it runs:

```bash
» sudo nodemon node_modules/.bin/lcm server
28 Jan 12:08:54 - [nodemon] v1.3.2
28 Jan 12:08:54 - [nodemon] to restart at any time, enter `rs`
28 Jan 12:08:54 - [nodemon] watching: *.*
28 Jan 12:08:54 - [nodemon] starting `node node_modules/.bin/lcm server`
CLI ENV: development
Locomotive 0.4.2 application starting in development on http://0.0.0.0:3000
connect deprecated multipart: use parser (multiparty, busboy, formidable) npm module instead node_modules/express/node_modules/connect/lib/middleware/bodyParser.js:56:20
connect deprecated limit: Restrict request size at location of read node_modules/express/node_modules/connect/lib/middleware/multipart.js:86:15
connect deprecated methodOverride: use method-override npm module instead config/initializers/30_middleware.js:16:20
HTTP server listening on 0.0.0.0:3000
```

Can you give it a try with the hello world example? I'm running on a mac, but it shouldn't really make a difference.

I can see in your dump that for some reason it's doubling up the executable and the argument, but I can't see why.

**Comment by crispen-smith** [comment]
Let me try that and see.
I agree that it isn't consistent as I was originally thrilled that it was working (even with my app) as expected, and this was a huge win for my dev process.

**Comment by crispen-smith** [comment]
Going to a global build seems to have resolved it.  I primarilly use a local build for final install to my PaaS but I'm very comfortable with global if it allows for nodemon.
