### ISSUE TITLE
Exception in nodemon kiling node

### ISSUE THREAD

**Issue by Ugarz** [remy/nodemon#481]
Hi,
I've started a project and set up nodemon with my app.js.
For a week all was good, but now it's throw me an error :
```
╭─ugo@pilpoual  ~/dev/workspace/jecologie  ‹master*› 
╰─$ node /usr/bin/nodemon --dump                                         1 ↵
exception in nodemon killing node
Error: EROFS, read-only file system '/home/ugo/.config/configstore/update-notifier-nodemon.yml'
    at Object.fs.openSync (evalmachine.<anonymous>:438:18)
    at Object.fs.writeFileSync (evalmachine.<anonymous>:977:15)
    at Object.create.all.set (/usr/lib/node_modules/nodemon/node_modules/update-notifier/node_modules/configstore/index.js:64:8)
    at Object.Configstore (/usr/lib/node_modules/nodemon/node_modules/update-notifier/node_modules/configstore/index.js:27:11)
    at new UpdateNotifier (/usr/lib/node_modules/nodemon/node_modules/update-notifier/lib/update-notifier.js:33:17)
    at module.exports (/usr/lib/node_modules/nodemon/node_modules/update-notifier/lib/update-notifier.js:146:23)
    at Object.<anonymous> (/usr/lib/node_modules/nodemon/bin/nodemon.js:7:16)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)

----------------------------------------------------------
If appropriate, please file an error with the output from:
$ node /usr/bin/nodemon --dump
At http://github.com/remy/nodemon/issues/new
----------------------------------------------------------
```
Anyone have an idea ? what about a right issue ? I see : read-only file system '/home/ugo/.config/configstore/update-notifier-nodemon.yml'.

**Comment by remy** [comment]
This might be fixed in update-notifier 0.3.0 - currently nodemon is using 0.1.10 - so I'll bump it and push out a release.

**Comment by remy** [comment]
I've pushed an update with nodemon@1.3.5 - can you give that a test?

**Comment by Ugarz** [comment]
Since the last update of nodemon, all works just great !
Problem solved ! :+1:
