### ISSUE TITLE
Cannot read property 'stdout' of undefined

### ISSUE THREAD

**Issue by micahlmartin** [remy/nodemon#509]
I'm trying to move over to io.js 1.2.0 and I'm running into an issue. Nodemon will start fine but whenever a file changes it chokes trying to restart. Here's the output:

```
18 Feb 20:55:29 - [nodemon] files triggering change check: app/policies/canAccessUserRoles.js
18 Feb 20:55:29 - [nodemon] matched rule: **/*.*
18 Feb 20:55:29 - [nodemon] changes after filters (before/after): 1/1
18 Feb 20:55:29 - [nodemon] restarting due to changes...
18 Feb 20:55:29 - [nodemon] app/policies/canAccessUserRoles.js

exception in nodemon killing node
TypeError: Cannot read property 'stdout' of undefined
    at spawn (/Users/micah/trackr/app/node_modules/nodemon/lib/spawn.js:13:21)
    at spawn (/Users/micah/trackr/app/node_modules/nodemon/lib/spawn.js:47:13)
    at null.<anonymous> (/Users/micah/trackr/app/node_modules/nodemon/lib/nodemon.js:179:15)
    at emitOne (events.js:80:20)
    at emit (events.js:150:7)
    at restartBus (/Users/micah/trackr/app/node_modules/nodemon/lib/monitor/watch.js:240:7)
    at filterAndRestart (/Users/micah/trackr/app/node_modules/nodemon/lib/monitor/watch.js:273:16)
    at /Users/micah/trackr/app/node_modules/nodemon/lib/monitor/watch.js:291:9
    at /Users/micah/trackr/app/node_modules/nodemon/lib/monitor/watch.js:100:9
    at ChildProcess.exithandler (child_process.js:707:7)
```

Here's the output from the dump:

```
--------------
node: v1.2.0
nodemon: v1.3.7
command: node /Users/micah/trackr/app/node_modules/nodemon/bin/nodemon.js ./bin/nuts s --dump
cwd: /Users/micah/trackr/app
OS: darwin x64
--------------
{ run: false,
  system:
   { cwd: '/Users/micah/trackr/app',
     useFind: true,
     useWatch: false,
     useWatchFile: false },
  required: false,
  dirs: [ '/Users/micah/trackr/app' ],
  timeout: 1000,
  options:
   { dump: true,
     restartable: 'rs',
     verbose: true,
     ignore:
      [ '.git',
        'public/',
        'node_modules/',
        'prerender/',
        'bower_components/',
        'stats.generated.json',
        re: /\.git|public\/|node_modules\/|prerender\/|bower_components\/|stats\.generated\.json/ ],
     events: { restart: 'osascript -e \'display notification "App restarted due to:\n\'$FILENAME\'" with title "nodemon"\'' },
     watch: [ '*.*', re: /.*\..*/ ],
     execMap: { py: 'python', rb: 'ruby' },
     stdin: true,
     stdout: true,
     execOptions:
      { script: './bin/nuts',
        exec: 'node',
        args: [ 's' ],
        scriptPosition: 0,
        nodeArgs: undefined,
        ext: 'js,json,yml,template',
        env: {},
        execArgs: [] },
     monitor:
      [ '*.*',
        '!/Users/micah/trackr/app/.git/**/*',
        '!/Users/micah/trackr/app/public/**/*',
        '!/Users/micah/trackr/app/node_modules/**/*',
        '!/Users/micah/trackr/app/prerender/**/*',
        '!bower_components/**/*',
        '!stats.generated.json' ] },
  load: [Function],
  reset: [Function: reset],
  lastStarted: 0,
  loaded: [ '/Users/micah/trackr/app/nodemon.json' ],
  command:
   { raw: { executable: 'node', args: [ './bin/nuts', 's' ] },
     string: 'node ./bin/nuts s' },
  offset: 0 }
--------------
18 Feb 20:55:53 - [nodemon] exiting
```

**Comment by jeffbski** [comment]
+1 I have same problem trying to use iojs 1.7.1

**Comment by remy** [comment]
Anyone able to debug this? I'm not an io.js user, so I don't have this to
hand.

**Comment by janders223** [comment]
It would appear to be in [spawn.js](https://github.com/remy/nodemon/blob/6f6d7ae4965715db782d7ee4f2084268500ccb2d/lib/spawn.js#L40) and how the node version is calculated as I commented almost a month ago. It is being asserted that node major versions greater than 8, so v0.8.0 and higher can use `child_process.spawn`. As io.js has embraced semver they are currently on v1.7.1 which is failing this check and appears to be recursively calling itself. It looks as though we need a better way to calculate the node version so that it passes for 1.x and >= 0.8.x.

**Comment by remy** [comment]
Damnit, I think I've caught this issue before because the actual process spawning doesn't happen in there - it happens [here](https://github.com/remy/nodemon/blob/master/lib/monitor/run.js#L68).

Does anyone want to take a run at either:

* (Optionally) making run.js use spawn.js (though I'm not 100% sure that's the right thing to do, because run.js has more jobs to do)
* Update and test (on io.js) the change to spawn.js to use the same version checking logic that run.js has

Thank you!

**Comment by FrankPaul1** [comment]
maybe you can try delete this line :  "events: { restart: 'osascript -e \'display notification "App restarted due to:\n\'$FILENAME\'" with title "nodemon"\'' }," , I meet the same problem, and it's OK after delete the line.
