### ISSUE TITLE
exception in nodemon killing node in Archlinux

### ISSUE THREAD

**Issue by Ugarz** [remy/nodemon#512]
Hello,
I'm using nodemon v1.3.7 with node v0.10.36 on Archlinux 64bits.
Nothing to declare but all used to work fine until now when I try to launch nodemon in two windows and diffrents port.
```
exception in nodemon killing node
Error: watch ENOSPC
    at errnoException (fs.js:1031:11)
    at FSWatcher.start (fs.js:1063:11)
    at Object.fs.watch (fs.js:1088:11)
    at Function.check (/usr/lib/node_modules/nodemon/lib/config/watchable.js:39:6)
    at alternativeCheck (/usr/lib/node_modules/nodemon/lib/config/checkWatchSupport.js:33:15)
    at /usr/lib/node_modules/nodemon/lib/config/checkWatchSupport.js:57:11
    at ChildProcess.exithandler (child_process.js:662:7)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:766:16)
    at Socket.<anonymous> (child_process.js:979:11)
```
Jarvis says me to do a $ node /usr/bin/nodemon --dump
```
--------------
node: v0.10.36
nodemon: v1.3.7
command: node /usr/bin/nodemon --dump
cwd: /home/ugo/dev/workspace/ILOVE
OS: linux x64
--------------
{ run: false,
  system: 
   { cwd: '/home/ugo/dev/workspace/ILOVE',
     useFind: false,
     useWatch: false,
     useWatchFile: true },
  required: false,
  dirs: [ '/home/ugo/dev/workspace/ILOVE' ],
  timeout: 1000,
  options: 
   { dump: true,
     ignore: 
      [ '.tmp/*',
        'views/*',
        'assets/*',
        re: /\.tmp/.*|views/.*|assets/.*/ ],
     watch: [ '*.*', re: /.*\..*/ ],
     restartable: 'rs',
     execMap: { py: 'python', rb: 'ruby' },
     stdin: true,
     verbose: false,
     stdout: true,
     execOptions: 
      { script: 'app.js',
        exec: 'node',
        args: [],
        scriptPosition: 0,
        nodeArgs: undefined,
        ext: 'js',
        env: {},
        execArgs: [] },
     monitor: [ '*.*', '!.tmp/**/*', '!views/**/*', '!assets/**/*' ] },
  load: [Function],
  reset: [Function: reset],
  lastStarted: 0,
  loaded: [],
  command: 
   { raw: { executable: 'node', args: [ 'app.js' ] },
     string: 'node app.js' },
  offset: 0 }

```
Any Idea ?

**Comment by Ugarz** [comment]
Hint : before launching nodemon I was connected in ssh.
Reboot had closed this session and after this, I can launch my nodemon on port 1337 and 1338 without any trouble.

**Comment by Ugarz** [comment]
Still in trouble.
But today I'm logged in, launching my server and itt doesn't work.

**Comment by Khyati-jajal** [comment]
I got the solution of this error 
there is problem of rights of file.
this command help you
sudo  chmod -R 771 your projectfolder/name
