### ISSUE TITLE
rs / exception in nodemon killing node / Error: write after end

### ISSUE THREAD

**Issue by KoltesDigital** [remy/nodemon#524]
I already had this error twice when I type `rs`.

```
rs
exception in nodemon killing node
Error: write after end
    at writeAfterEnd (_stream_writable.js:167:12)
    at Socket.Writable.write (_stream_writable.js:214:5)
    at Socket.write (net.js:625:40)
    at ReadStream.ondata (_stream_readable.js:540:20)
    at ReadStream.emit (events.js:129:20)
    at readableAddChunk (_stream_readable.js:163:16)
    at ReadStream.Readable.push (_stream_readable.js:126:10)
    at TTY.onread (net.js:529:20)
```

.../nodemon.js --dump

```
--------------
node: v0.12.0
nodemon: v1.2.1
command: node C:\Users\XXX\AppData\Roaming\npm\node_modules\nodemon\bin\nodemon.js --dump
cwd: C:\XXX
OS: win32 x64
--------------
{ run: false,
  system:
   { cwd: 'C:\\XXX',
     useFind: false,
     useWatch: false,
     useWatchFile: true },
  required: false,
  dirs: [ 'C:\\XXX' ],
  timeout: 1000,
  options:
   { scriptPosition: 0,
     dump: true,
     script: 'app.js',
     args: [],
     ignore:
      [ '.git',
        'node_modules',
        'bower_components',
        '.sass-cache',
        re: /\.git|node_modules|bower_components|\.sass\-cache/ ],
     watch: [ '*.*', re: /.*\..*/ ],
     restartable: 'rs',
     execMap: { py: 'python', rb: 'ruby' },
     stdin: true,
     verbose: false,
     stdout: true,
     execOptions:
      { script: 'app.js',
        exec: 'node',
        args: [],
        nodeArgs: undefined,
        ext: 'js',
        env: {},
        execArgs: [] },
     ext: 'js',
     monitor:
      [ '*.*',
        '!.git',
        '!C:\\XXX\\node_modules/**/*',
        '!bower_components',
        '!.sass-cache' ] },
  load: [Function],
  reset: [Function: reset],
  lastStarted: 0,
  loaded: [],
  command:
   { raw: { executable: 'node', args: [ 'app.js' ] },
     string: 'node app.js' } }
```

**Comment by remy** [comment]
I appreciate it was a while ago, but can you try with nodemon@1.6.1 - I've pushed a fix to `rs`.

**Comment by KoltesDigital** [comment]
I have no occurrences for months, I close this issue.
