### ISSUE TITLE
exception in nodemon killing node

### ISSUE THREAD

**Issue by akhar** [remy/nodemon#549]
```
exception in nodemon killing node
Error: watch ENOSPC
    at exports._errnoException (util.js:746:11)
    at FSWatcher.start (fs.js:1176:11)
    at Object.fs.watch (fs.js:1202:11)
    at Function.check (/home/akha/.nvm/versions/node/v0.12.1/lib/node_modules/nodemon/lib/config/watchable.js:39:6)
    at alternativeCheck (/home/akha/.nvm/versions/node/v0.12.1/lib/node_modules/nodemon/lib/config/checkWatchSupport.js:33:15)
    at /home/akha/.nvm/versions/node/v0.12.1/lib/node_modules/nodemon/lib/config/checkWatchSupport.js:57:11
    at ChildProcess.exithandler (child_process.js:751:5)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1008:16)
    at Socket.<anonymous> (child_process.js:1176:11)

----------------------------------------------------------
If appropriate, please file an error with the output from:
$ node /home/akha/.nvm/versions/node/v0.12.1/bin/nodemon keystone --dump
At http://github.com/remy/nodemon/issues/new
----------------------------------------------------------

12 May 11:57:57 - [nodemon] v1.3.7
12 May 11:57:57 - [nodemon] to restart at any time, enter `rs`
12 May 11:57:57 - [nodemon] watching: *.*
--------------
node: v0.12.1
nodemon: v1.3.7
command: node /home/akha/.nvm/versions/node/v0.12.1/bin/nodemon keystone --dump
cwd: /home/akha/heroku/leg-r
OS: linux x64
--------------
{ run: false,
  system: 
   { cwd: '/home/akha/heroku/leg-r',
     useFind: false,
     useWatch: false,
     useWatchFile: true },
  required: false,
  dirs: [ '/home/akha/heroku/leg-r' ],
  timeout: 1000,
  options: 
   { dump: true,
     ignore: 
      [ '.git',
        'node_modules',
        'bower_components',
        '.sass-cache',
        re: /\.git|node_modules|bower_components|\.sass\-cache/ ],
     watch: [ '*.*', re: /.*\..*/ ],
     restartable: 'rs',
     execMap: { py: 'python', rb: 'ruby' },
     stdin: true,
     verbose: false,
     stdout: true,
     execOptions: 
      { script: 'keystone',
        exec: 'node',
        args: [],
        scriptPosition: 0,
        nodeArgs: undefined,
        ext: 'js',
        env: {},
        execArgs: [] },
     monitor: 
      [ '*.*',
        '!/home/akha/heroku/leg-r/.git/**/*',
        '!/home/akha/heroku/leg-r/node_modules/**/*',
        '!bower_components',
        '!.sass-cache' ] },
  load: [Function],
  reset: [Function: reset],
  lastStarted: 0,
  loaded: [],
  command: 
   { raw: { executable: 'node', args: [ 'keystone' ] },
     string: 'node keystone' },
  offset: 0 }

```

**Comment by hynnot** [comment]
I have the same problem with node v0.10.38
