### ISSUE TITLE
nodemon breaks with npm 2.11.x

### ISSUE THREAD

**Issue by kyrylkov** [remy/nodemon#559]
https://github.com/nodejs/io.js/issues/1849
https://github.com/npm/npm/issues/8419

```
C:\Users\Dev>nodemon
exception in nodemon killing node
Error: Cannot find module 'wrappy'
    at Function.Module._resolveFilename (module.js:332:15)
    at Function.Module._load (module.js:282:25)
    at Module.require (module.js:361:17)
    at require (module.js:380:17)
    at Object.<anonymous> (C:\Users\Sergiy Kyrylkov\AppData\Roaming\npm\node_modules\nodemon\node_modules\update-notifier\node_modules\latest-version\node_modules\package-json\node_modules\got\node_modules\duplexify\node_modules\end-of-stream\node_modules\once\once.js:1:76)
    at Module._compile (module.js:426:26)
    at Object.Module._extensions..js (module.js:444:10)
    at Module.load (module.js:351:32)
    at Function.Module._load (module.js:306:12)
    at Module.require (module.js:361:17)
    at require (module.js:380:17)
```

**Comment by kyrylkov** [comment]
https://github.com/npm/npm/issues/8419

**Comment by kyrylkov** [comment]
The workaround is to edit `npmrc` to use a shorter path for global modules:

```
# prefix=${APPDATA}\npm
prefix=C:\npm
```
