### ISSUE TITLE
Crashing Nodemon while changing tests

### ISSUE THREAD

**Issue by spruce** [remy/nodemon#560]
Hey,
I was changing some of my tests running nodemon ./api/tests --watch ./api 
Then it created an error:
```
[nodemon] failed to start process, possible issue with exec arguments
exception in nodemon killing node
Error: Uncaught, unspecified "error" event.
    at emit (events.js:143:13)
    at ChildProcess.<anonymous> (/usr/local/var/nvm/versions/io.js/v2.0.1/lib/node_modules/nodemon/lib/monitor/run.js:126:11)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:169:7)
    at Process.ChildProcess._handle.onexit (child_process.js:1009:12)


```

Contents of the command which I was instructed to run:
```
/usr/local/var/nvm/versions/io.js/v2.0.1/bin/iojs /usr/local/var/nvm/versions/io.js/v2.0.1/bin/nodemon ./api/tests --watch ./api --dump
31 May 17:09:22 - [nodemon] v1.3.7
31 May 17:09:22 - [nodemon] to restart at any time, enter `rs`
31 May 17:09:22 - [nodemon] watching: /Users/spruce/Sites/project/api/**/*
--------------
node: v2.0.1
nodemon: v1.3.7
command: /usr/local/var/nvm/versions/io.js/v2.0.1/bin/iojs /usr/local/var/nvm/versions/io.js/v2.0.1/bin/nodemon ./api/tests --watch ./api --dump
cwd: /Users/spruce/Sites/project
OS: darwin x64
--------------
{ run: false,
  system: 
   { cwd: '/Users/spruce/Sites/project',
     useFind: true,
     useWatch: false,
     useWatchFile: false },
  required: false,
  dirs: [ '/Users/spruce/Sites/project/api' ],
  timeout: 1000,
  options: 
   { watch: [ './api', re: /\.\/api/ ],
     dump: true,
     ignore: 
      [ '.git',
        'node_modules',
        'bower_components',
        '.sass-cache',
        re: /\.git|node_modules|bower_components|\.sass\-cache/ ],
     restartable: 'rs',
     execMap: { py: 'python', rb: 'ruby' },
     stdin: true,
     verbose: false,
     stdout: true,
     execOptions: 
      { script: './api/tests',
        exec: 'node',
        args: [],
        scriptPosition: 0,
        nodeArgs: undefined,
        ext: 'js',
        env: {},
        execArgs: [] },
     monitor: 
      [ '/Users/spruce/Sites/project/api/**/*',
        '!/Users/spruce/Sites/project/.git/**/*',
        '!/Users/spruce/Sites/project/node_modules/**/*',
        '!/Users/spruce/Sites/project/bower_components/**/*',
        '!.sass-cache' ] },
  load: [Function],
  reset: [Function: reset],
  lastStarted: 0,
  loaded: [],
  command: 
   { raw: { executable: 'node', args: [ './api/tests' ] },
     string: 'node ./api/tests' },
  offset: 0 }
--------------
```

I don't know what is failing nodemon ...

after fixing one of the failing tests it now works again ...

**Comment by alexbepple** [comment]
Is this the same as #496?

**Comment by spruce** [comment]
I think so.
