### ISSUE TITLE
nodemon not restarting

### ISSUE THREAD

**Issue by kevinawoo** [remy/nodemon#576]
nodemon isn't restarting correctly after a file is changed. Here's the `--dump`, `--verbose`, and `npm test` results:

--dump:
```
$ nodemon --dump -x './.bin/test_in_dev.sh' -- -b --test-only
30 Jun 13:47:21 - [nodemon] v1.3.7
30 Jun 13:47:21 - [nodemon] to restart at any time, enter `rs`
30 Jun 13:47:21 - [nodemon] watching: /Users/kevin/repo/modules/**/* /Users/kevin/repo/db/**/* /Users/kevin/repo/config/**/* /Users/kevin/repo/scripts/**/* /Users/kevin/repo/work/**/*
--------------
node: v0.10.32
nodemon: v1.3.7
command: node /Users/kevin/.nvm/v0.10.32/bin/nodemon --dump -x ./.bin/test_in_dev.sh -- -b --test-only
cwd: /Users/kevin/repo
OS: darwin x64
--------------
{ run: false,
  system:
   { cwd: '/Users/kevin/repo',
     useFind: false,
     useWatch: true,
     useWatchFile: false },
  required: false,
  dirs: [ '/Users/kevin/repo' ],
  timeout: 1000,
  options:
   { dump: true,
     exec: './.bin/test_in_dev.sh',
     watch:
      [ 'modules',
        'db',
        'config',
        'scripts',
        'work',
        re: /modules|db|config|scripts|work/ ],
     ignore:
      [ 'coverage',
        'node_modules',
        '.bin',
        '.git',
        '.idea',
        'npm-debug.json',
        'tmp',
        re: /coverage|node_modules|\.bin|\.git|\.idea|npm\-debug\.json|tmp/ ],
     restartable: 'rs',
     execMap: { py: 'python', rb: 'ruby' },
     stdin: true,
     verbose: false,
     stdout: true,
     execOptions:
      { script: null,
        exec: './.bin/test_in_dev.sh',
        args: [ '-b', '--test-only' ],
        scriptPosition: null,
        nodeArgs: undefined,
        ext: [ 'json', 'js', 'sql', '.gitignore' ],
        env: {},
        execArgs: [] },
     monitor:
      [ '/Users/kevin/repo/modules/**/*',
        '/Users/kevin/repo/db/**/*',
        '/Users/kevin/repo/config/**/*',
        '/Users/kevin/repo/scripts/**/*',
        '/Users/kevin/repo/work/**/*',
        '!/Users/kevin/repo/coverage/**/*',
        '!/Users/kevin/repo/node_modules/**/*',
        '!/Users/kevin/repo/.bin/**/*',
        '!/Users/kevin/repo/.git/**/*',
        '!/Users/kevin/repo/.idea/**/*',
        '!npm-debug.json',
        '!/Users/kevin/repo/tmp/**/*' ] },
  load: [Function],
  reset: [Function: reset],
  lastStarted: 0,
  loaded: [ '/Users/kevin/repo/nodemon.json' ],
  command:
   { raw:
      { executable: './.bin/test_in_dev.sh',
        args: [ '-b', '--test-only' ] },
     string: './.bin/test_in_dev.sh -b --test-only' },
  offset: 0 }
--------------
```

--verbose:
```
$ nodemon --verbose -x './.bin/test_in_dev.sh' -- -b --test-only
30 Jun 13:46:29 - [nodemon] v1.3.7
30 Jun 13:46:29 - [nodemon] reading config /Users/kevin/repo/nodemon.json
30 Jun 13:46:29 - [nodemon] to restart at any time, enter `rs`
30 Jun 13:46:29 - [nodemon] ignoring: /Users/kevin/repo/coverage/**/* /Users/kevin/repo/node_modules/**/* /Users/kevin/repo/.bin/**/* /Users/kevin/repo/.git/**/* /Users/kevin/repo/.idea/**/* npm-debug.json /Users/kevin/repo/tmp/**/*
30 Jun 13:46:29 - [nodemon] watching: /Users/kevin/repo/modules/**/* /Users/kevin/repo/db/**/* /Users/kevin/repo/config/**/* /Users/kevin/repo/scripts/**/* /Users/kevin/repo/work/**/*
30 Jun 13:46:29 - [nodemon] watching extensions: json,js,sql,.gitignore
30 Jun 13:46:29 - [nodemon] starting `./.bin/test_in_dev.sh -b --test-only`
30 Jun 13:46:29 - [nodemon] child pid: 2653
30 Jun 13:46:30 - [nodemon] watching 963 files
30 Jun 13:46:30 - [nodemon] files triggering change check: .nodemon-offset
30 Jun 13:46:30 - [nodemon] changes after filters (before/after): 1/0
Using 2 x hasMany to represent N:M relations has been deprecated. Please use belongsToMany instead
belongsToMany: not defining through or defining through as true has been deprecated, please provide a string or a model


  Subscription
    Admin
undefined
      1) should be able to create


  0 passing (456ms)
  1 failing

  1) Subscription Admin should be able to create:
     TypeError: Object #<Test> has no method 'exepct'
      at Context.<anonymous> (modules/controllers/__tests__/SubscriptionController-test.js:9:1667)



=============================================================================
Writing coverage object [/Users/kevin/repo/coverage/coverage.json]
Writing coverage reports at [/Users/kevin/repo/coverage]
=============================================================================

=============================== Coverage summary ===============================
Statements   : 33.85% ( 5752/16991 )
Branches     : 3.23% ( 140/4331 )
Functions    : 11.03% ( 450/4081 )
Lines        : 33.97% ( 5752/16934 )
================================================================================
30 Jun 13:46:38 - [nodemon] clean exit - waiting for changes before restart
30 Jun 13:46:43 - [nodemon] files triggering change check: modules/controllers/__tests__/SubscriptionController-test.js___jb_bak___
30 Jun 13:46:43 - [nodemon] matched rule: **/Users/kevin/repo/modules/**/*
30 Jun 13:46:43 - [nodemon] changes after filters (before/after): 1/0
30 Jun 13:46:43 - [nodemon] files triggering change check: modules/controllers/__tests__/SubscriptionController-test.js
30 Jun 13:46:43 - [nodemon] matched rule: **/Users/kevin/repo/modules/**/*
30 Jun 13:46:43 - [nodemon] changes after filters (before/after): 1/0
30 Jun 13:46:43 - [nodemon] files triggering change check: modules/controllers/__tests__/SubscriptionController-test.js___jb_old___
30 Jun 13:46:43 - [nodemon] matched rule: **/Users/kevin/repo/modules/**/*
30 Jun 13:46:43 - [nodemon] changes after filters (before/after): 1/0
^Cexception in nodemon killing node
TypeError: Object #<Object> has no method 'removeListener'
    at g (events.js:176:10)
    at /Users/kevin/.nvm/v0.10.32/lib/node_modules/nodemon/lib/monitor/run.js:278:11
    at Array.forEach (native)
    at exit (/Users/kevin/.nvm/v0.10.32/lib/node_modules/nodemon/lib/monitor/run.js:276:29)
    at onQuit (/Users/kevin/.nvm/v0.10.32/lib/node_modules/nodemon/lib/monitor/run.js:303:5)
    at emit (events.js:117:20)
    at process.module.exports (/Users/kevin/.nvm/v0.10.32/lib/node_modules/nodemon/lib/monitor/run.js:323:9)
    at process.g (events.js:180:16)
    at process.emit (events.js:92:17)
    at Signal.wrap.onsignal (node.js:761:46)

----------------------------------------------------------
If appropriate, please file an error with the output from:
$ node /Users/kevin/.nvm/v0.10.32/bin/nodemon --verbose -x ./.bin/test_in_dev.sh -- -b --test-only --dump
At http://github.com/remy/nodemon/issues/new
----------------------------------------------------------

30 Jun 13:46:45 - [nodemon] exiting
```

Tests
```
$ npm test

> nodemon@1.3.7 test /Users/kevin/.nvm/v0.10.32/lib/node_modules/nodemon
> for FILE in test/**/*.test.js; do echo $FILE; ./node_modules/.bin/mocha --timeout 30000 $FILE; if [ $? -ne 0 ]; then exit 1; fi; sleep 1; done

test/cli/exec.test.js


  nodemon exec
    ✓ should default to node
    ✓ should support --debug
    ✓ should support --debug=XXXX
    ✓ should support multiple extensions
    ✓ should replace {{filename}}
    ✓ should not split on spaces in {{filename}}
    ✓ should support extension maps
    ✓ should support input from argv#parse
    ✓ should use coffeescript on .coffee
    ✓ should support coffeescript in debug mode
    ✓ should support custom execs
    ✓ should support custom executables with arguments
    ✓ should support an array of exec arguments


  13 passing (11ms)

test/cli/parse.test.js


  nodemon CLI parser
    ✓ should support --debug with script detect via package
    ✓ should replace {{filename}}
    ✓ should parse the help examples #1
    ✓ should parse the help examples #2
    ✓ should parse the help examples #3
    ✓ should parse the help examples #4
    ✓ should parse the help examples #5
    ✓ should put the script at the end if found in package.main
    ✓ should support default express4 format
    ✓ should support package.scripts.start with args
    ✓ should support spaces
    ✓ should support quotes around arguments
    ✓ should keep eating arguments that are for nodemon after the script.js
    ✓ should allow -- to appear anywhere, and still find user script
    ✓ should support arguments from the cli
    ✓ should support stand alone `nodemon` command
    ✓ should put --debug in the right place with coffescript
    ✓ should support period path
    ✓ should parse `nodemon lib/index.js`
    ✓ should parse `nodemon test/fixtures/app.coffee`
    ✓ should parse `nodemon --watch src/ -e js,coffee test/fixtures/app.js`
    ✓ should pass --debug to node
    ✓ should pass --harmony to node

  nodemon argument parser
    ✓ support strings
    ✓ should support short versions of flags
    ✓ should support long versions of flags

  nodemon respects custom "ext" and "execMap"
    ✓ should support "ext" and "execMap" for same extension

  nodemon with CoffeeScript
    ✓ should not add --nodejs by default
    ✓ should not add --nodejs with app arguments
    ✓ groups exec argument into a single --nodejs argument
    ✓ should add --nodejs when used with --debug
    ✓ should add --nodejs when used with --debug-brk

  nodemon --delay argument
    ✓ should support an integer value
    ✓ should support a float value
    ✓ should support a value with a time specifier for seconds (s)
    ✓ should support a value with a time specifier for milliseconds (ms)


  36 passing (19ms)

test/config/env.test.js


  when nodemon runs (1)
    ✓ should pass through environment values (331ms)


  1 passing (337ms)

test/config/load.test.js


  config load
    ✓ should remove ignore defaults if user provides their own (1292ms)
    ✓ should support old .nodemonignore
    ✓ should read global config
    ✓ should give local files preference
    ✓ should give user specified settings preference
    ✓ should give user specified exec preference over package.scripts.start
    ✓ should put the script at the end if found in package.scripts.start
    ✓ should support "ext" with "execMap"


  8 passing (1s)

test/config/watchable.test.js


  watchable tests
    ✓ should return whether watch is supported (257ms)


  1 passing (262ms)

test/events/complete.test.js


  events should follow normal flow on user triggered change
    ✓ start (272ms)
    ✓ config:update
    1) exit
    2) quit
    ✓ stdout
    3) restart


  3 passing (2m)
  3 failing

  1) events should follow normal flow on user triggered change exit:
     Error: timeout of 30000ms exceeded. Ensure the done() callback is being called in this test.


  2) events should follow normal flow on user triggered change quit:
     Error: timeout of 30000ms exceeded. Ensure the done() callback is being called in this test.


  3) events should follow normal flow on user triggered change restart:
     Error: timeout of 30000ms exceeded. Ensure the done() callback is being called in this test.




npm ERR! Test failed.  See above for more details.
npm ERR! not ok code 0
```

**Comment by romikzo** [comment]
+
```
node: v0.10.38
nodemon: v1.3.7
command: node /usr/bin/nodemon server.js --dump
cwd: /var/www/kmz
OS: linux x64
--------------
{ run: false,
  system: 
   { cwd: '/var/www/kmz',
     useFind: false,
     useWatch: true,
     useWatchFile: false },
  required: false,
  dirs: [ '/var/www/kmz' ],
  timeout: 1000,
  options: 
   { dump: true,
     ignore: 
      [ '.git',
        'node_modules',
        'bower_components',
        '.sass-cache',
        re: /\.git|node_modules|bower_components|\.sass\-cache/ ],
     watch: [ '*.*', re: /.*\..*/ ],
     restartable: 'rs',
     execMap: { py: 'python', rb: 'ruby' },
     stdin: true,
     verbose: false,
     stdout: true,
     execOptions: 
      { script: 'server.js',
        exec: 'node',
        args: [],
        scriptPosition: 0,
        nodeArgs: undefined,
        ext: 'js',
        env: {},
        execArgs: [] },
     monitor: 
      [ '*.*',
        '!.git',
        '!/var/www/kmz/node_modules/**/*',
        '!bower_components',
        '!.sass-cache' ] },
  load: [Function],
  reset: [Function: reset],
  lastStarted: 0,
  loaded: [],
  command: 
   { raw: { executable: 'node', args: [ 'server.js' ] },
     string: 'node server.js' },
  offset: 0 }
```

**Comment by kevinawoo** [comment]
**RESOLVED MY ISSUE**
it was improper usage of the config file.
bad config: `"ext": ["js", "json", "sql"]`
acceptable: `"ext": "js json sql"`
acceptable:  `"ext": "json,js,sql"`

**Comment by kevinawoo** [comment]
@romikzo can you post your nodemon.json or the cli?
I can double check your configs.

**Comment by gilesbutler** [comment]
I'm having the same issue. Changing the config file didn't make any difference though:
 
    {
      "ext": "js",
      "ignore" : [
        "assets/"
      ],
      "watch": [
          "api/",
          "views/",
          "config/"
        ]
    }

**Comment by ronxjansen** [comment]
Same for me. I'm using vagrant (ubuntu/trusty64), node@4, nodemon@1.5-alpha4 (also tried using 1.5 stable). Even without configuration file or in legacy mode is nodemon not restarting.

**Comment by kevinawoo** [comment]
@gilesbutler @ronxjansen can you add your the `--dump` and `--verbose` output? 

Also, what is the file path(s) that should trigger the restarts?

**Comment by kevinawoo** [comment]
@romikzo the dump looks fine, what files paths are suppose to be trigging it?

**Comment by remy** [comment]
I'd also recommend updating to the latest nodemon in all cases, as there's been a major refactor.

**Comment by ronxjansen** [comment]
@remy i've updated to the latest version, but unfortunately that did not make a difference.

**Comment by remy** [comment]
@ronxjansen can you share any info about your environment. OS, container? Maybe run `DEBUG=nodemon nodemon --dump` and share the output?

**Comment by ronxjansen** [comment]
@remy please find below the output 

```--------------
node: v4.0.0
nodemon: v1.5.1
command: /usr/local/bin/node /usr/local/bin/nodemon --dump
cwd: /home/deploy/api/current
OS: linux x64
--------------
{ run: false,
  system: { cwd: '/home/deploy/api/current' },
  required: false,
  dirs: 
   [ '/home/deploy/api/current/app',
     '/home/deploy/api/current/config',
     '/home/deploy/api/current/libs' ],
  timeout: 1000,
  options: 
   { dump: true,
     watch: [ 'app', 'config', 'libs', re: /app|config|libs/ ],
     env: 
      { NODE_ENV: 'development',
        AWS_ACCESS_KEY_ID: '********************',
        AWS_SECRET_ACCESS_KEY: '********************',
        AWS_SESSION_TOKEN: '' },
     ignore: 
      [ '.git',
        'node_modules',
        'bower_components',
        '.sass-cache',
        re: /\.git|node_modules|bower_components|\.sass\-cache/ ],
     restartable: 'rs',
     execMap: { py: 'python', rb: 'ruby' },
     stdin: true,
     runOnChangeOnly: false,
     verbose: false,
     stdout: true,
     execOptions: 
      { script: 'config/server.js',
        exec: 'node',
        args: [],
        scriptPosition: 0,
        nodeArgs: undefined,
        ext: 'js,jsx',
        env: 
         { NODE_ENV: 'development',
           AWS_ACCESS_KEY_ID: '********************',
           AWS_SECRET_ACCESS_KEY: '********************',
           AWS_SESSION_TOKEN: '' },
        execArgs: [] },
     monitor: 
      [ '/home/deploy/api/current/app/**/*',
        '/home/deploy/api/current/config/**/*',
        '/home/deploy/api/current/libs/**/*',
        '!/home/deploy/api/current/.git/**/*',
        '!/home/deploy/api/current/node_modules/**/*',
        '!bower_components',
        '!/home/deploy/api/current/.sass-cache/**/*' ] },
  load: [Function],
  reset: [Function: reset],
  lastStarted: 0,
  loaded: [ '/home/deploy/api/current/nodemon.json' ],
  watchInterval: null,
  command: 
   { raw: { executable: 'node', args: [ 'config/server.js' ] },
     string: 'node config/server.js' } }
--------------```

**Comment by remy** [comment]
@ronxjansen you're inside of vagrant, right? Can you also check `ps` and `kill -SIGUSR2 0` (might bail your terminal) works?

**Comment by remy** [comment]
nodemon@1.6 supports `-L` legacy watch mode (again), but it will tell Chokidar to use it's polling technique.

Can you give it a try?

**Comment by vijayviji** [comment]
'-L' mode works. There seems to be a bug in watching the Virtual Box shared folder (mounted inside).

**Comment by TroyWorks** [comment]
'-L' mode fixed an issue on VMWare with shared folders (mounted inside) docker and Ubuntu 15.05 +  IO.JS 3.3.1 NVM.

Weirdly prior version  was working on boot2docker/VirtualBox without this flag, mentioned above.

**Comment by remy** [comment]
The internal watch mechanism changed which might explain why.

**Comment by ronxjansen** [comment]
@remy sorry for the late reply. All works when using nodemon 1.7.0!

**Comment by remy** [comment]
Cheers all!
