### ISSUE TITLE
exception in nodemon killing node TypeError: Cannot read property 'stdout' of undefined

### ISSUE THREAD

**Issue by TroyWorks** [remy/nodemon#587]
exception in nodemon killing node
TypeError: Cannot read property 'stdout' of undefined
    at spawn (/root/.nvm/versions/io.js/v2.3.4/lib/node_modules/nodemon/lib/spaw                                                                   n.js:13:21)
    at spawn (/root/.nvm/versions/io.js/v2.3.4/lib/node_modules/nodemon/lib/spaw                                                                   n.js:47:13)
    at null.<anonymous> (/root/.nvm/versions/io.js/v2.3.4/lib/node_modules/nodem                                                                   on/lib/nodemon.js:179:15)
    at emitOne (events.js:82:20)
    at emit (events.js:169:7)
    at restartBus (/root/.nvm/versions/io.js/v2.3.4/lib/node_modules/nodemon/lib                                                                   /monitor/watch.js:240:7)
    at filterAndRestart (/root/.nvm/versions/io.js/v2.3.4/lib/node_modules/nodem                                                                   on/lib/monitor/watch.js:273:16)
    at /root/.nvm/versions/io.js/v2.3.4/lib/node_modules/nodemon/lib/monitor/wat                                                                   ch.js:291:9
    at /root/.nvm/versions/io.js/v2.3.4/lib/node_modules/nodemon/lib/monitor/wat                                                                   ch.js:100:9
    at ChildProcess.exithandler (child_process.js:188:7)

$ /root/.nvm/versions/io.js/v2.3.4/bin/iojs /root/.nvm/versions/io.js/v2.3.4/bin                      /nodemon --use_strict --harmony_arrow_functions --debug=5859 /projectA/bin/www --dump

**Comment by TroyWorks** [comment]
removing in nodemon.json this line fixes it.

  "events": {
    "restart": "osascript -e 'display notification \"App restarted due to:\n'$FILENAME'\" with title \"nodemon\"'"
  },

**Comment by remy** [comment]
iojs supported in nodemon 1.4.2 and upwards (so - fixed!)
