### ISSUE TITLE
TypeError: Cannot read property 'addListener' of undefined

### ISSUE THREAD

**Issue by OmgImAlexis** [remy/nodemon#593]
I got this from running ``loadtest http://localhost:3000/ -t 20 -c 10 --rps 1000``.

The error I got.
````
exception in nodemon killing node
TypeError: Cannot read property 'addListener' of undefined
    at Object.exports.execFile (child_process.js:234:15)
    at exports.exec (child_process.js:103:18)
    at changeFunction (/Users/xo/.nvm/versions/io.js/v2.3.3/lib/node_modules/nodemon/lib/monitor/watch.js:93:7)
    at module.exports [as _onTimeout] (/Users/xo/.nvm/versions/io.js/v2.3.3/lib/node_modules/nodemon/lib/monitor/watch.js:293:5)
    at Timer.listOnTimeout (timers.js:89:15)
````

Here's the dump
````
--------------
node: v2.3.3
nodemon: v1.3.8
command: /Users/xo/.nvm/versions/io.js/v2.3.3/bin/iojs /Users/xo/.nvm/versions/io.js/v2.3.3/bin/nodemon app.js --dump
cwd: /Users/xo/node/tv
OS: darwin x64
--------------
{ run: false,
  system: 
   { cwd: '/Users/xo/node/tv',
     useFind: true,
     useWatch: false,
     useWatchFile: false },
  required: false,
  dirs: [ '/Users/xo/node/tv' ],
  timeout: 1000,
  options: 
   { dump: true,
     ignore: 
      [ '.git',
        'node_modules',
        'bower_components',
        '.sass-cache',
        re: /\.git|node_modules|bower_components|\.sass\-cache/ ],
     watch: [ '*.*', re: /.*\..*/ ],
     restartable: 'rs',
     execMap: { py: 'python', rb: 'ruby' },
     stdin: true,
     verbose: false,
     stdout: true,
     execOptions: 
      { script: 'app.js',
        exec: 'node',
        args: [],
        scriptPosition: 0,
        nodeArgs: undefined,
        ext: 'js',
        env: {},
        execArgs: [] },
     monitor: 
      [ '*.*',
        '!/Users/xo/node/tv/.git/**/*',
        '!/Users/xo/node/tv/node_modules/**/*',
        '!bower_components',
        '!.sass-cache' ] },
  load: [Function],
  reset: [Function: reset],
  lastStarted: 0,
  loaded: [],
  command: 
   { raw: { executable: 'node', args: [ 'app.js' ] },
     string: 'node app.js' },
  offset: 0 }
--------------
````

**Comment by remy** [comment]
Needs iojs developers to help.

**Comment by remy** [comment]
This is/should be supported now in the latest release.
