### ISSUE TITLE
env values in npm.start not handled correctly

### ISSUE THREAD

**Issue by ORESoftware** [remy/nodemon#615]
Something must have changed with the nodemon module itself since my same package.json settings suddenly began to error out, as you can see from this command:

![image](https://cloud.githubusercontent.com/assets/11139560/9422357/522d72c6-4845-11e5-8b6c-6b3bf727e2e4.png)

looks like in your library you are setting the NODE_ENV variable the unix way, but that doesn't work on windows, you need to use ```set NODE_ENV=```

**Comment by remy** [comment]
... Between what versions?

**Comment by ORESoftware** [comment]
let me check

**Comment by ORESoftware** [comment]
this problems stared happening about 2 weeks ago, so if there was a recent version change that was it. And it happens for me on both Windows and Mac OSX.

```
$ NODE_ENV=development nodemon ./bin/www
24 Aug 15:55:06 - [nodemon] v1.4.1
24 Aug 15:55:06 - [nodemon] to restart at any time, enter `rs`
24 Aug 15:55:06 - [nodemon] watching: *.*
24 Aug 15:55:06 - [nodemon] starting `NODE_ENV=production ./bin/www "node ./bin/www"`
sh: ./bin/www: No such file or directory
util.error: Use console.error instead
[nodemon] failed to start process, "NODE_ENV=production" exec not found
exception in nodemon killing node
Error: Uncaught, unspecified "error" event.
    at Error (native)
    at emit (events.js:87:13)
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/nodemon/lib/monitor/run.js:114:11)
    at ChildProcess.emit (events.js:110:17)
    at Process.ChildProcess._handle.onexit (child_process.js:1074:12)

----------------------------------------------------------
If appropriate, please file an error with the output from:
$ node /usr/local/bin/nodemon ./bin/www --dump
At http://github.com/remy/nodemon/issues/new
----------------------------------------------------------

CACSVML-13295:sc-admin-ui-express amills001c$ node /usr/local/bin/nodemon ./bin/www --dump
24 Aug 15:55:40 - [nodemon] v1.4.1
24 Aug 15:55:40 - [nodemon] to restart at any time, enter `rs`
24 Aug 15:55:40 - [nodemon] watching: *.*
--------------
node: v0.12.7
nodemon: v1.4.1
command: node /usr/local/bin/nodemon ./bin/www --dump
cwd: /Users/amills001c/WebstormProjects/ORESoftware/sc-admin-ui-express
OS: darwin x64
--------------
{ run: false,
  system: 
   { cwd: '/Users/amills001c/WebstormProjects/ORESoftware/sc-admin-ui-express',
     useFind: true,
     useWatch: false,
     useWatchFile: false },
  required: false,
  dirs: [ '/Users/amills001c/WebstormProjects/ORESoftware/sc-admin-ui-express' ],
  timeout: 1000,
  options: 
   { dump: true,
     ignore: 
      [ '.git',
        'node_modules',
        'bower_components',
        '.sass-cache',
        re: /\.git|node_modules|bower_components|\.sass\-cache/ ],
     watch: [ '*.*', re: /.*\..*/ ],
     restartable: 'rs',
     execMap: { py: 'python', rb: 'ruby' },
     stdin: true,
     runOnChangeOnly: false,
     verbose: false,
     stdout: true,
     execOptions: 
      { script: 'node ./bin/www',
        exec: 'NODE_ENV=production',
        args: [ './bin/www' ],
        scriptPosition: 1,
        nodeArgs: undefined,
        ext: 'js',
        env: {},
        execArgs: [] },
     monitor: 
      [ '*.*',
        '!/Users/amills001c/WebstormProjects/ORESoftware/sc-admin-ui-express/.git/**/*',
        '!/Users/amills001c/WebstormProjects/ORESoftware/sc-admin-ui-express/node_modules/**/*',
        '!/Users/amills001c/WebstormProjects/ORESoftware/sc-admin-ui-express/bower_components/**/*',
        '!.sass-cache' ] },
  load: [Function],
  reset: [Function: reset],
  lastStarted: 0,
  loaded: [],
  command: 
   { raw: 
      { executable: 'NODE_ENV=production',
        args: [ './bin/www', 'node ./bin/www' ] },
     string: 'NODE_ENV=production ./bin/www "node ./bin/www"' },
  offset: 0 }
--------------
```

**Comment by ORESoftware** [comment]
somehow nodemon is turning this:

```
$ NODE_ENV=development nodemon ./bin/www
```
into this 
```
24 Aug 15:55:06 - [nodemon] starting `NODE_ENV=production ./bin/www "node ./bin/www"`
```

this is dreadful, I cannot use nodemon and I need it! like I said this problem is occuring on both Windows and Mac...

**Comment by ORESoftware** [comment]
I hope I am not right, but it looks like something is really wrong right now with your lib

**Comment by ORESoftware** [comment]
that dump was from OSX, but in the screenshot at the very top, the same exact thing happens on Windows
