### ISSUE TITLE
exception in nodemon killing node - Running nodemon on Windows 10

### ISSUE THREAD

**Issue by giacomorebonato** [remy/nodemon#616]
I am trying to execute nodemon on Windows 10
```sh
$ > node-debug server.js
> nodemon server.js
23 Aug 10:01:12 - [nodemon] v1.4.1
23 Aug 10:01:12 - [nodemon] to restart at any time, enter `rs`
23 Aug 10:01:12 - [nodemon] watching: *.*
23 Aug 10:01:12 - [nodemon] starting `node server.js`
exception in nodemon killing node
Error: spawn cmd ENOENT
    at exports._errnoException (util.js:746:11)
    at Process.ChildProcess._handle.onexit (child_process.js:1053:32)
    at child_process.js:1144:20
    at process._tickCallback (node.js:355:11)

----------------------------------------------------------
If appropriate, please file an error with the output from:
$ node C:\Users\Admin\AppData\Roaming\npm\node_modules\nodemon\bin\nodemon.js server.js --dump
At http://github.com/remy/nodemon/issues/new
----------------------------------------------------------
```
And this is the dump
```sh
23 Aug 10:02:51 - [nodemon] v1.4.1
23 Aug 10:02:51 - [nodemon] to restart at any time, enter `rs`
23 Aug 10:02:51 - [nodemon] watching: *.*
--------------
node: v0.12.7
nodemon: v1.4.1
command: node C:\Users\Admin\AppData\Roaming\npm\node_modules\nodemon\bin\nodemon.js server.js --dump
cwd: C:\Users\Admin\Dev\mino_api_boilerplate\lib
OS: win32 x64
--------------
{ run: false,
  system:
   { cwd: 'C:\\Users\\Admin\\Dev\\mino_api_boilerplate\\lib',
     useFind: false,
     useWatch: true,
     useWatchFile: false },
  required: false,
  dirs: [ 'C:\\Users\\Admin\\Dev\\mino_api_boilerplate\\lib' ],
  timeout: 1000,
  options:
   { dump: true,
     ignore:
      [ '.git',
        'node_modules',
        'bower_components',
        '.sass-cache',
        re: /\.git|node_modules|bower_components|\.sass\-cache/ ],
     watch: [ '*.*', re: /.*\..*/ ],
     restartable: 'rs',
     execMap: { py: 'python', rb: 'ruby' },
     stdin: true,
     runOnChangeOnly: false,
     verbose: false,
     stdout: true,
     execOptions:
      { script: 'server.js',
        exec: 'node',
        args: [],
        scriptPosition: 0,
        nodeArgs: undefined,
        ext: 'js',
        env: {},
        execArgs: [] },
     monitor:
      [ '*.*',
        '!.git',
        '!node_modules',
        '!bower_components',
        '!.sass-cache' ] },
  load: [Function],
  reset: [Function: reset],
  lastStarted: 0,
  loaded: [],
  command:
   { raw: { executable: 'node', args: [ 'server.js' ] },
     string: 'node server.js' },
  offset: 0 }
--------------

```

```sh

**Comment by giacomorebonato** [comment]
it was missing C:\Windows\System32\  in the PATH.
Problem solved.

**Comment by shubh3794** [comment]
I am having this issue on windows, how to work around it

**Comment by RifeWang** [comment]
@giacomorebonato I still understand how to solve this problem.

**Comment by RifeWang** [comment]
@giacomorebonato  I solved this problem. update path and then restart my computer.

**Comment by Mohammad-Quanit** [comment]
Can anyone tell me how to update path?

**Comment by marquizzo** [comment]
@Mohammad-Quanit 

**Windows 10:**
Control Panel > All Control Panel Items > System > Advanced system settings [on left bar]
Advanced Tab > Environment Variables Button
Select `PATH` variable, click Edit...
Click `New` button, and it'll allow you to add a new location to your PATH. Make sure you don't remove existing lines, or you'll break other programs that need it!
