### ISSUE TITLE
Nodemon always fails to restart with EADDRINUSE

### ISSUE THREAD

**Issue by optikalefx** [remy/nodemon#623]
My output

```
30 Aug 23:01:02 - [nodemon] starting `babel-node --harmony --optional es7.decorators --optional es7.classProperties index.js 8787`
factsumo-api running in environment development
factsumo-api connected to mongo server
factsumo-api listening on http://localhost:3000
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: listen EADDRINUSE
    at exports._errnoException (util.js:746:11)
    at Server._listen2 (net.js:1156:14)
    at listen (net.js:1182:10)
    at Server.listen (net.js:1267:5)
    at Application.app.listen (/Applications/MAMP/htdocs/factsumo-api/node_modules/koa/lib/application.js:70:24)
    at /Applications/MAMP/htdocs/factsumo-api/index.js:164:6
    at /Applications/MAMP/htdocs/factsumo-api/node_modules/mongodb/lib/mongo_client.js:418:15
    at process._tickDomainCallback (node.js:381:11)
30 Aug 23:01:03 - [nodemon] app crashed
30 Aug 23:01:03 - [nodemon] exiting
```

it works fine on my buddies machine, so its something up with mine. My version is 0.7.10

**Comment by remy** [comment]
Your version of *what* is 0.7.10?

**Comment by optikalefx** [comment]
nodemon -v
0.7.10

Thanks!

**Comment by optikalefx** [comment]
While we're at it

node -v
v0.12.5

**Comment by remy** [comment]
You know nodemon is on and over 1.0, right?

Either install latest, or try the dev build with `npm install -g nodemon@dev` ref #625

**Comment by optikalefx** [comment]
Not sure why I didn't check that. Fixed. Thanks.
