### ISSUE TITLE
Error: watch EINVAL

### ISSUE THREAD

**Issue by Landen13** [remy/nodemon#629]
Hello. I am beginner and just got a strange error.
I have test.js with one line:
```
console.log(1);
```

    $ nodemon test.js
    13 Sep 23:00:59 - [nodemon] v1.5.0
    13 Sep 23:00:59 - [nodemon] to restart at any time, enter `rs`
    13 Sep 23:00:59 - [nodemon] watching: *.*
    13 Sep 23:00:59 - [nodemon] starting `node test.js`
    events.js:85
          throw er; // Unhandled 'error' event
                ^
    Error: watch EINVAL
    at exports._errnoException (util.js:746:11)
    at FSWatcher.start (fs.js:1172:11)
    at Object.fs.watch (fs.js:1198:11)
    at createFsWatchInstance (C:\Program Files\nodejs\node_modules\nodemon\node_modules\chokidar\lib\nodefs-handler.js:37:15)
    at setFsWatchListener (C:\Program Files\nodejs\node_modules\nodemon\node_modules\chokidar\lib\nodefs-handler.js:80:15)
    at EventEmitter.NodeFsHandler._watchWithNodeFs (C:\Program Files\nodejs\node_modules\nodemon\node_modules\chokidar\lib\nodefs-handler.js:228:14)
    at EventEmitter.NodeFsHandler._handleFile (C:\Program Files\nodejs\node_modules\nodemon\node_modules\chokidar\lib\nodefs-handler.js:255:21)
    at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\nodemon\node_modules\chokidar\lib\nodefs-handler.js:468:21)
    at FSReqWrap.oncomplete (fs.js:95:15)

Node -v0.12.3
NPM 3.2.2

What's wrong with nodefs-handler.js?

**Comment by remy** [comment]
Can you re-run but add an environment variable of `DEBUG=nodemon` and paste
the output here (I don't know how you set env values on windows, but if
you're using something like the git shell, just put that statement in front
of the nodemon command).

**Comment by Landen13** [comment]
@remy Did you mean --debug flag? If yes, then output is the same as above.

**Comment by remy** [comment]
No, I didn't meant the debug flag, I meant exactly as I said above. It'll
yield further debug to help diagnose the issue.

**Comment by Landen13** [comment]
$ NODE_ENV=debug

    $ nodemon test.js
      nodemon bus new listener: reset (0) +0ms
      nodemon bus new listener: reset (0) +4ms
      nodemon bus new listener: quit (0) +11ms
      nodemon bus new listener: quit (0) +0ms
      nodemon bus new listener: restart (0) +1ms
      nodemon bus new listener: restart (0) +0ms
      nodemon bus new listener: reset (2) +6ms
      nodemon bus emit: reset +2ms
      nodemon reset +1ms
      nodemon final rules +168ms { ignore:
       [ '.git',
         'node_modules',
         'bower_components',
         '.sass-cache',
         re: /\.git|node_modules|bower_components|\.sass\-cache/ ],
      watch: [ '*.*', re: /.*\..*/ ],
      restartable: 'rs',
      execMap: { py: 'python', rb: 'ruby' },
      stdin: true,
      runOnChangeOnly: false,
      verbose: false,
      stdout: true,
      execOptions:
       { script: 'test.js',
         exec: 'node',
         args: [],
         scriptPosition: 0,
         nodeArgs: undefined,
         ext: 'js',
         env: {},
         execArgs: [] } }
      nodemon config: dirs +6ms [ 'd:\\' ]
    14 Sep 10:52:01 - [nodemon] v1.5.0
    14 Sep 10:52:01 - [nodemon] to restart at any time, enter `rs`
    14 Sep 10:52:01 - [nodemon] watching: *.*
    14 Sep 10:52:01 - [nodemon] starting `node test.js`
      nodemon bus new listener: exit (0) +9ms
      nodemon bus new listener: exit (0) +1ms
      nodemon about to watch +0ms
      nodemon start watch on: d:\ +1ms
      nodemon ignore dirs regex(/\.git|node_modules|bower_components|\.sass\-cache/)
     +0ms
    events.js:85
          throw er; // Unhandled 'error' event
                ^
    Error: watch EINVAL
        at exports._errnoException (util.js:746:11)
        at FSWatcher.start (fs.js:1172:11)
        at Object.fs.watch (fs.js:1198:11)
        at createFsWatchInstance (c:\Program Files\nodejs\node_modules\nodemon\node_
    modules\chokidar\lib\nodefs-handler.js:37:15)
        at setFsWatchListener (c:\Program Files\nodejs\node_modules\nodemon\node_mod
    ules\chokidar\lib\nodefs-handler.js:80:15)
        at EventEmitter.NodeFsHandler._watchWithNodeFs (c:\Program Files\nodejs\node
    _modules\nodemon\node_modules\chokidar\lib\nodefs-handler.js:228:14)
        at EventEmitter.NodeFsHandler._handleFile (c:\Program Files\nodejs\node_modu
    les\nodemon\node_modules\chokidar\lib\nodefs-handler.js:255:21)
        at EventEmitter.<anonymous> (c:\Program Files\nodejs\node_modules\nodemon\no
    de_modules\chokidar\lib\nodefs-handler.js:468:21)
        at FSReqWrap.oncomplete (fs.js:95:15)

**Comment by remy** [comment]
Oh, sorry, can you use `DEBUG=nodemon,nodemon:watch` and repeat?

Sorry, I forgot I filtered out the super-detail to `nodemon:watch`.

**Comment by Landen13** [comment]
@remy 
I moved test.js to a separate folder and the error dissappeared.
Do siblings of the specified file affect the nodemon? There were some folders and files.

**Comment by remy** [comment]
I suspect you were hitting an internal limit in Chokidar (the 3rd party module that does the monitoring). Linked to this: https://github.com/paulmillr/chokidar/issues/229

**Comment by remy** [comment]
I've now spotted that you were running from the root directory, so this explains that it was trying to read *every* js file on your `d:\` drive. I think there's two action points (for the nodemon project here):

1. Handle the `Error: watch EINVAL` to offer a useful message
2. Maybe check to see if we're working from a root of a drive, and if so, *only* monitor the file given, and not directories.

**Comment by remy** [comment]
Fixed in 1.6.0

**Comment by remy** [comment]
Well...not fixed, it just echos a real (useful) error message.
