### ISSUE TITLE
Latest update failed to build optional dependency fsevents.o on my system

### ISSUE THREAD

**Issue by granteagon** [remy/nodemon#636]
Still works, but here's the output with stack trace:
```
-
> fsevents@0.3.8 install /usr/local/lib/node_modules/nodemon/node_modules/chokidar/node_modules/fsevents
> node-gyp rebuild

child_process: customFds option is deprecated, use stdio instead.
  SOLINK_MODULE(target) Release/.node
  SOLINK_MODULE(target) Release/.node: Finished
  CXX(target) Release/obj.target/fse/fsevents.o
In file included from ../fsevents.cc:6:
../node_modules/nan/nan.h:447:32: error: no member named 'SetCounterFunction' in 'v8::Isolate'
    v8::Isolate::GetCurrent()->SetCounterFunction(cb);
    ~~~~~~~~~~~~~~~~~~~~~~~~~  ^
../node_modules/nan/nan.h:452:32: error: no member named 'SetCreateHistogramFunction' in 'v8::Isolate'
    v8::Isolate::GetCurrent()->SetCreateHistogramFunction(cb);
    ~~~~~~~~~~~~~~~~~~~~~~~~~  ^
../node_modules/nan/nan.h:457:32: error: no member named 'SetAddHistogramSampleFunction' in 'v8::Isolate'
    v8::Isolate::GetCurrent()->SetAddHistogramSampleFunction(cb);
    ~~~~~~~~~~~~~~~~~~~~~~~~~  ^
../node_modules/nan/nan.h:468:39: error: no member named 'IdleNotification' in 'v8::Isolate'
    return v8::Isolate::GetCurrent()->IdleNotification(idle_time_in_ms);
           ~~~~~~~~~~~~~~~~~~~~~~~~~  ^
../node_modules/nan/nan.h:473:32: error: no member named 'LowMemoryNotification' in 'v8::Isolate'
    v8::Isolate::GetCurrent()->LowMemoryNotification();
    ~~~~~~~~~~~~~~~~~~~~~~~~~  ^
../node_modules/nan/nan.h:477:32: error: no member named 'ContextDisposedNotification' in 'v8::Isolate'
    v8::Isolate::GetCurrent()->ContextDisposedNotification();
    ~~~~~~~~~~~~~~~~~~~~~~~~~  ^
6 errors generated.
make: *** [Release/obj.target/fse/fsevents.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1059:12)
gyp ERR! System Darwin 14.3.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/nodemon/node_modules/chokidar/node_modules/fsevents
gyp ERR! node -v v0.11.14
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok
npm WARN optional dep failed, continuing fsevents@0.3.8
/usr/local/bin/nodemon -> /usr/local/lib/node_modules/nodemon/bin/nodemon.js
npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/realize-package-specifier requires dezalgo@'^1.0.1' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/dezalgo,
npm WARN unmet dependency which is version 1.0.0
npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/realize-package-specifier requires npm-package-arg@'^2.1.3' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/npm-package-arg,
npm WARN unmet dependency which is version 2.1.2
npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/read-package-json/node_modules/normalize-package-data requires github-url-from-username-repo@'^0.1.0' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/github-url-from-username-repo,
npm WARN unmet dependency which is version 1.0.2
npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/read-package-json/node_modules/normalize-package-data requires semver@'2' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/semver,
npm WARN unmet dependency which is version 4.0.0
nodemon@1.5.1 /usr/local/lib/node_modules/nodemon
├── undefsafe@0.0.3
├── es6-promise@3.0.2
├── debug@2.2.0 (ms@0.7.1)
├── minimatch@0.3.0 (sigmund@1.0.1, lru-cache@2.7.0)
├── touch@1.0.0 (nopt@1.0.10)
├── lodash.defaults@3.1.2 (lodash.restparam@3.6.1, lodash.assign@3.2.0)
├── ps-tree@0.0.3 (event-stream@0.5.3)
├── update-notifier@0.5.0 (is-npm@1.0.0, string-length@1.0.1, repeating@1.1.3, chalk@1.1.1, semver-diff@2.0.0, configstore@1.2.1, latest-version@1.0.1)
└── chokidar@1.0.5 (arrify@1.0.0, path-is-absolute@1.0.0, is-glob@1.1.3, glob-parent@1.2.0, async-each@0.1.6, is-binary-path@1.0.1, readdirp@1.4.0, anymatch@1.3.0)
```

**Comment by remy** [comment]
Yeah, that's fine `optional dep failed` - obviously looks scary, but it installed and works.
