### ISSUE TITLE
Installation failed since Xcode command line tools version updated

### ISSUE THREAD

**Issue by mickey9801** [remy/nodemon#646]
I have tried to reinstall nodemon today on my Mac but it failed. There are some error message when trying to rebuild node-gyp as below:

```
> node-gyp rebuild

build:update-notifier     ▐ ╢███████████████████████████████████

Agreeing to the Xcode/iOS license requires admin privileges, please re-run as root via sudo.

Agreeing to the Xcode/iOS license requires admin privileges, please re-run as root via sudo.

gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 69
gyp ERR! stack     at ChildProcess.onExit (/Users/████/.nvm/versions/node/v4.1.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "/Users/████/.nvm/versions/node/v4.1.0/bin/node" "/Users/████/.nvm/versions/node/v4.1.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/████/.nvm/versions/node/v4.1.0/lib/node_modules/nodemon/node_modules/fsevents
gyp ERR! node -v v4.1.0
gyp ERR! node-gyp -v v3.0.1
gyp ERR! not ok
build:update-notifier     ▐ ╢███████████████████████████████████build → rollbackFailedOpt ▐ ╢██████████████████████████████████build → rollbackFailedOpt ▄ ╢██████████████████████████████████runTopLevelLifecycles     ▐ ╢███████████████████████████████████npm ERR! Darwin 14.5.0
npm ERR! argv "/Users/████/.nvm/versions/node/v4.1.0/bin/node" "/Users/████/.nvm/versions/node/v4.1.0/bin/npm" "install" "-g" "nodemon"
npm ERR! node v4.1.0
npm ERR! npm  v3.3.3
npm ERR! code ELIFECYCLE

npm ERR! fsevents@0.3.8 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the fsevents@0.3.8 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the fsevents package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls fsevents
npm ERR! There is likely additional logging output above.
```

I have tried to install node-gyp, update-notifier and fsevents alone and they goes well, but all of their version are different from nodemon using. Since I have recently updated command line tools for Xcode to version 7 and changed to use nvm to install node v4.1.0, I wonder if there are any incompatible with new version.

My system spec. is as below:
* OSX Yosemite
* Xcode v7.0 with Command line tools
* Node.js v4.1.0
* nvm v0.26.1
* npm v3.3.3
* node-gyp v3.0.3

**Comment by mickey9801** [comment]
Sorry I found the problem. It was my mistake that I have not open Xcode once after update. It is OK now.
