### ISSUE TITLE
Nodemon detects a file change but won't restart  /  'rs' command not working either

### ISSUE THREAD

**Issue by 1400883** [remy/nodemon#652]
##### System specs:
- Windows XP SP3
- nodejs 0.12.7
- nodemon 1.7.0

Command: `G:\_AMK\WebDevelopment\wormgame>nodemon -V server.js`

```
23 Sep 20:12:11 - [nodemon] v1.7.0
23 Sep 20:12:11 - [nodemon] to restart at any time, enter `rs`
23 Sep 20:12:11 - [nodemon] ignoring: .git G:\_AMK\WebDevelopment\wormgame\node_modules/**/* bower_components .sass-cache
23 Sep 20:12:11 - [nodemon] watching: *.*
23 Sep 20:12:11 - [nodemon] watching extensions: js
23 Sep 20:12:11 - [nodemon] starting `node server.js`
23 Sep 20:12:11 - [nodemon] child pid: 2260
23 Sep 20:12:11 - [nodemon] watching 16 files
Waiting for clients in port 3000...
23 Sep 20:12:22 - [nodemon] files triggering change check: server.js
23 Sep 20:12:22 - [nodemon] matched rule: **\*.*
23 Sep 20:12:22 - [nodemon] changes after filters (before/after): 1/1
23 Sep 20:12:22 - [nodemon] restarting due to changes...
23 Sep 20:12:22 - [nodemon] server.js
```

and then - nothing. If I input rs command in the prompt and press enter, all I get is a linefeed and the command prompt won't receive any more keyboard input. Interestingly, if the file attached to nodemon either causes nodejs to crash right away or does a clean exit, nodemon successfully restarts on file change.

Finally, nodemon dump:

```
G:\_AMK\WebDevelopment\wormgame>nodemon --dump
23 Sep 20:32:33 - [nodemon] v1.7.0
23 Sep 20:32:33 - [nodemon] to restart at any time, enter `rs`
23 Sep 20:32:33 - [nodemon] watching: *.*
--------------
node: v0.12.7
nodemon: v1.7.0
command: node C:\Documents and Settings\MyFirstName\Application Data\npm\node_modules
\nodemon\bin\nodemon.js --dump
cwd: G:\_AMK\WebDevelopment\wormgame
OS: win32 ia32
--------------
{ run: false,
  system: { cwd: 'G:\\_AMK\\WebDevelopment\\wormgame' },
  required: false,
  dirs: [ 'G:\\_AMK\\WebDevelopment\\wormgame' ],
  timeout: 1000,
  options:
   { dump: true,
     ignore:
      [ '.git',
        'node_modules',
        'bower_components',
        '.sass-cache',
        re: /\.git|node_modules|bower_components|\.sass\-cache/ ],
     watch: [ '*.*', re: /.*\..*/ ],
     ignoreRoot: [ '.git', 'node_modules', 'bower_components', '.sass-cache' ],
     restartable: 'rs',
     colours: true,
     execMap: { py: 'python', rb: 'ruby' },
     stdin: true,
     runOnChangeOnly: false,
     verbose: false,
     stdout: true,
     execOptions:
      { script: 'register.js',
        exec: 'node',
        args: [],
        scriptPosition: 0,
        nodeArgs: undefined,
        ext: 'js',
        env: {},
        execArgs: [] },
     monitor:
      [ '*.*',
        '!.git',
        '!G:\\_AMK\\WebDevelopment\\wormgame\\node_modules/**/*',
        '!bower_components',
        '!.sass-cache' ] },
  load: [Function],
  reset: [Function: reset],
  lastStarted: 0,
  loaded: [],
  watchInterval: null,
  command:
   { raw: { executable: 'node', args: [ 'register.js' ] },
     string: 'node register.js' } }
--------------
```

**Comment by remy** [comment]
Bump to 1.7.1 this issues is fixed.

**Comment by 1400883** [comment]
Now using 1.7.1, still not working.

**Comment by remy** [comment]
I can't tsst windows XP, so I'm going to need you to debug it for me.

The rs listener is in lib/nodemon.js can you add debugging to work out whether the signals are getting in?

**Comment by 1400883** [comment]
Thanks to your hint about where to start, I managed to track down the issue.

```js
lib\monitor\run.js:
251:   if (utils.isWindows) {
252:     // When using CoffeeScript under Windows, child's process is not node.exe
253:     // Instead coffee.cmd is launched, which launches cmd.exe, which starts
254:     // node.exe as a child process child.kill() would only kill cmd.exe, not
255:     // node.exe
256:     // Therefore we use the Windows taskkill utility to kill the process and all
257:     // its children (/T for tree).
258:     // Force kill (/F) the whole child tree (/T) by PID (/PID 123)
259:     exec('taskkill /pid ' + child.pid + ' /T /F');
260:     callback();
```
Windows XP Home Edition did not ship with [**taskkill**](https://www.microsoft.com/resources/documentation/windows/xp/all/proddocs/en-us/taskkill.mspx?mfr=true) (included since XP Pro), only with more limited [**tskill**](https://www.microsoft.com/resources/documentation/windows/xp/all/proddocs/en-us/ts_cmd_tskill.mspx?mfr=true).

It's easy one to catch but **tskill** doesn't have options for either killing the entire child tree or killing forcefully. I quickly tried Sysinternal's [PsKill.exe](https://technet.microsoft.com/en-us/sysinternals/bb896683.aspx) with the code below and it appeared to work. I had to dismiss the EULA gui on the first execution, though.
```js
exec('taskkill /?', function (err) {
  if (err) {
    exec('pskill -t ' + child.pid);
  } else {
    exec('taskkill /pid ' + child.pid + ' /T /F');
  }
});
```
Perhaps implement the fallback mechanism and add a note to README.md for Windows 2000 / Xp Home users about additional download?

**Comment by junejie** [comment]
Im having same issue in my Mac.

here is my directory structure
```
dev/mock
├── index.html
├── server.js
└── file.yml
```

When i change the server.js the it triggers the restart. But changes in file.yml is not calling the restart.

```
[nodemon] 1.10.2
[nodemon] to restart at any time, enter `rs`
[nodemon] ignoring: .git /Users/currentUser/Downloads/move/project/SuperProject/apps/frontend/.nyc_output/**/* .sass-cache bower_components /Users/currentUser/Downloads/move/project/SuperProject/apps/frontend/coverage/**/* /Users/currentUser/Downloads/move/project/SuperProject/apps/frontend/node_modules/**/*
[nodemon] watching: /Users/currentUser/Downloads/move/project/SuperProject/apps/frontend/dev/**/* /Users/currentUser/Downloads/move/project/SuperProject/apps/frontend/src/static/**/*
[nodemon] watching extensions: js,json
--------------
node: v4.4.7
nodemon: 1.10.2
command: /Users/currentUser/.nvm/versions/node/v4.4.7/bin/node /Users/currentUser/Downloads/move/project/SuperProject/apps/frontend/node_modules/.bin/nodemon -V -L --debug --watch dev --watch src/static dev/mock/server.js --dump
cwd: /Users/currentUser/Downloads/move/project/SuperProject/apps/frontend
OS: darwin x64
--------------
{ run: false,
  system: { cwd: '/Users/currentUser/Downloads/move/project/SuperProject/apps/frontend' },
  required: false,
  dirs:
   [ '/Users/currentUser/Downloads/move/project/SuperProject/apps/frontend/dev',
     '/Users/currentUser/Downloads/move/project/SuperProject/apps/frontend/src/static' ],
  timeout: 1000,
  options:
   { verbose: true,
     legacyWatch: true,
     watch: [ 'dev', 'src/static', re: /dev|src\/static/ ],
     dump: true,
     ignore:
      [ '.git',
        '.nyc_output',
        '.sass-cache',
        'bower_components',
        'coverage',
        'node_modules',
        re: /\.git|\.nyc_output|\.sass\-cache|bower_components|coverage|node_modules/ ],
     ignoreRoot:
      [ '.git',
        '.nyc_output',
        '.sass-cache',
        'bower_components',
        'coverage',
        'node_modules' ],
     restartable: 'rs',
     colours: true,
     execMap: { py: 'python', rb: 'ruby' },
     stdin: true,
     runOnChangeOnly: false,
     stdout: true,
     execOptions:
      { script: 'dev/mock/server.js',
        exec: 'node',
        args: [ '--debug' ],
        scriptPosition: 1,
        nodeArgs: undefined,
        ext: 'js,json',
        env: {},
        execArgs: [] },
     monitor:
      [ '/Users/currentUser/Downloads/move/project/SuperProject/apps/frontend/dev/**/*',
        '/Users/currentUser/Downloads/move/project/SuperProject/apps/frontend/src/static/**/*',
        '!.git',
        '!/Users/currentUser/Downloads/move/project/SuperProject/apps/frontend/.nyc_output/**/*',
        '!.sass-cache',
        '!bower_components',
        '!/Users/currentUser/Downloads/move/project/SuperProject/apps/frontend/coverage/**/*',
        '!/Users/currentUser/Downloads/move/project/SuperProject/apps/frontend/node_modules/**/*' ] },
  load: [Function],
  reset: [Function: reset],
  lastStarted: 0,
  loaded: [],
  watchInterval: null,
  command:
   { raw:
      { executable: 'node',
        args: [ '--debug', 'dev/mock/server.js' ] },
     string: 'node --debug dev/mock/server.js' } }
--------------
[nodemon] exiting
```

**Comment by remy** [comment]
@junejie your config is not set to watch yaml files. You need to add that to your extension list.

**Comment by andrerpena** [comment]
I have the same problem on Windows 10 using `nodemon@1.11.0`.

**nodemon.json**:

```
{
    "watch": [
        "./src/**/*.ts"
    ],
    "exec": "ts-node ./src/server/index.ts",
    "verbose": true
}
```

**Dump**:
```

--------------
node: v7.4.0
nodemon: 1.9.1
command: C:\Program Files\nodejs\node.exe C:\Users\andrerpena\AppData\Roaming\npm\node_modules\nodemon\bin\nodemon.js --dump
cwd: C:\Git\pushpad-ts
OS: win32 x64
--------------
{ run: false,
  system: { cwd: 'C:\\Git\\pushpad-ts' },
  required: false,
  dirs: [ 'C:\\Git\\pushpad-ts\\src' ],
  timeout: 1000,
  options: 
   { dump: true,
     watch: [ './src/**/*.ts', re: /\.\/src\/.*.*\/.*\.ts/ ],
     exec: 'ts-node ./src/server/index.ts',
     verbose: true,
     ignore: 
      [ '.git',
        '.nyc_output',
        '.sass-cache',
        'bower_components',
        'coverage',
        'node_modules',
        re: /\.git|\.nyc_output|\.sass\-cache|bower_components|coverage|node_modules/ ],
     ignoreRoot: 
      [ '.git',
        '.nyc_output',
        '.sass-cache',
        'bower_components',
        'coverage',
        'node_modules' ],
     restartable: 'rs',
     colours: true,
     execMap: { py: 'python', rb: 'ruby' },
     stdin: true,
     runOnChangeOnly: false,
     stdout: true,
     execOptions: 
      { script: null,
        exec: 'ts-node ./src/server/index.ts',
        args: [],
        scriptPosition: null,
        nodeArgs: undefined,
        ext: 'js,json',
        env: {},
        execArgs: [] },
     monitor: 
      [ './src/**/*.ts',
        '!C:\\Git\\pushpad-ts\\.git/**/*',
        '!.nyc_output',
        '!.sass-cache',
        '!bower_components',
        '!coverage',
        '!C:\\Git\\pushpad-ts\\node_modules/**/*' ] },
  load: [Function],
  reset: [Function: reset],
  lastStarted: 0,
  loaded: [ 'C:\\Git\\pushpad-ts\\nodemon.json' ],
  watchInterval: null,
  command: 
   { raw: { executable: 'ts-node ./src/server/index.ts', args: [] },
     string: 'ts-node ./src/server/index.ts' } }
--------------
[33m[nodemon] exiting[39m

```

When I change a ts file, it detects it but doesn't run `rs`. If I run `rs` manually it works:

![image](https://cloud.githubusercontent.com/assets/1581429/22229645/2acf1994-e1c0-11e6-968f-649ba349805d.png)

**Comment by climaa** [comment]
Same error on linux on same version v1.11.0.

**Comment by sherlockgrace** [comment]
did anyone find an answer to this? im getting this message

C:\Users\Charlotte\Desktop\web-socket  (web-socket@1.0.0)
λ nodemon index
[nodemon] 1.11.0
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node index index.js`
module.js:471
    throw err;
    ^

Error: Cannot find module 'C:\Users\Charlotte\Desktop\web-socket\index'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:504:3
[nodemon] app crashed - waiting for file changes before starting...
