### ISSUE TITLE
Passing -d flag to application causes error

### ISSUE THREAD

**Issue by jdarling** [remy/nodemon#666]
Trying to execute an application with a flag that is "reserved" for nodemon causes an error in the latest version.  In 1.7.0 this worked (if I remember properly) but in 1.7.1 this throws an error.

```
nodemon server -d
```

Results in
```
TypeError: Cannot read property 'match' of undefined
    at parseDelay (/usr/lib/node_modules/nodemon/lib/cli/parse.js:224:12)
    at nodemonOption (/usr/lib/node_modules/nodemon/lib/cli/parse.js:166:21)
    at parse (/usr/lib/node_modules/nodemon/lib/cli/parse.js:80:11)
    at Object.module.exports.parse (/usr/lib/node_modules/nodemon/lib/cli/index.js:47:12)
    at Object.<anonymous> (/usr/lib/node_modules/nodemon/bin/nodemon.js:5:19)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:475:10)
```

I'm sure this is the same for other "reserved flags"

**Comment by remy** [comment]
To pass `-d` to your program, you need to use the "stop slurping" argument `--`:

```shell
nodemon server -- -d
```
