### ISSUE TITLE
Uncaught, unspecified "error" event.

### ISSUE THREAD

**Issue by gajus** [remy/nodemon#667]
```
curiosity:table gajus$ nodemon --exec "flow" --quiet ./src/

/Users/gajus/Documents/dev/gajus/table/src/validateData.js:16:5,13: string
This type is incompatible with
/Users/gajus/Documents/dev/gajus/table/src/validateData.js:13:23,27: array type

/Users/gajus/Documents/dev/gajus/table/src/validateData.js:16:5,13: +=
Error:
/Users/gajus/Documents/dev/gajus/table/src/validateData.js:16:5,8: array type
This type is incompatible with
/Users/gajus/Documents/dev/gajus/table/src/validateData.js:16:5,13: string

/Users/gajus/Documents/dev/gajus/table/src/validateData.js:16:5,13: +=
Error:
/Users/gajus/Documents/dev/gajus/table/src/validateData.js:16:13,13: number
This type is incompatible with
/Users/gajus/Documents/dev/gajus/table/src/validateData.js:16:5,13: string

Found 3 errors
events.js:146
      throw err;
      ^

Error: Uncaught, unspecified "error" event. (2)
    at emit (events.js:144:17)
    at ChildProcess.<anonymous> (/Users/gajus/.nvm/versions/node/v4.1.0/lib/node_modules/nodemon/lib/monitor/run.js:124:11)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
```

**Comment by remy** [comment]
This is a pre-cursor to `failed to start process, possible issue with exec arguments`. It's part bug in nodemon, part bug in your command.

**Comment by gajus** [comment]
How can it be fixed from my end?

**Comment by mikael-entefy** [comment]
The problem is that mocha is sending a non-zero exit code which causes nodemon to exit.
Mocha isn't very consistent in it's exit codes...

My workaround is to create mocha-wrap.js
```
'use strict';

process.on('exit', () => {
  process.exit();
});

require('.bin/mocha');
```
Then `nodemon mocha-wrap.js`.
