### ISSUE TITLE
is nodemon hijacking the current user / env variables?

### ISSUE THREAD

**Issue by derickbailey** [remy/nodemon#673]
I'm working on a project that uses oracle/node-oracledb library for Oracle access in Node.js

When I run my code like `node agents/oracle.js` everything works fine:

```
$ node agents/oracle.js
connected to rabbitmq
subscribing steps
receiving from agent.oracle-pl-sql step.oracle-pl-sql
```

this is the output I expect to see.

but, when I change `node` to `nodemon` for this process, it fails:

```
$ nodemon agents/oracle.js
6 Oct 14:43:40 - [nodemon] 1.7.1
6 Oct 14:43:40 - [nodemon] to restart at any time, enter `rs`
6 Oct 14:43:40 - [nodemon] watching: *.*
6 Oct 14:43:40 - [nodemon] starting `node agents/oracle.js`
/Users/derickbailey/dev/projects/seabass/node_modules/oracledb/lib/oracledb.js:28
    throw err;
    ^

Error: dlopen(/Users/derickbailey/dev/projects/seabass/node_modules/oracledb/build/Release/oracledb.node, 1): Library not loaded: /ade/b/2649109290/oracle/rdbms/lib/libclntsh.dylib.11.1
  Referenced from: /Users/derickbailey/dev/projects/seabass/node_modules/oracledb/build/Release/oracledb.node
  Reason: image not found
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/derickbailey/dev/projects/seabass/node_modules/oracledb/lib/oracledb.js:23:15)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
6 Oct 14:43:41 - [nodemon] app crashed - waiting for file changes before starting...
```

According to [this issue on an oracle related library](https://github.com/joeferner/node-oracle/issues/43), the "image not found" reason is related to environment variables not being set.

so, i'm wondering... why would nodemon change which environment variables are available? is it hijacking the current user or context or env vars that are set, when it runs the node app? if so, what user / context is it running in?

**Comment by derickbailey** [comment]
I'm continuing to dig, and it looks like the env vars are still there... but out of order, and 2 minor differences.

here is the result of running `env` on my box:

```
GIT_PS1_SHOWDIRTYSTATE=true
rvm_bin_path=/Users/derickbailey/.rvm/bin
TERM_PROGRAM=Apple_Terminal
TERM=xterm-color
SHELL=/bin/bash
CLICOLOR=1
TMPDIR=/var/folders/5g/x1ddqhp94gq6m7y5qmtpw2dw0000gn/T/
Apple_PubSub_Socket_Render=/private/tmp/com.apple.launchd.RkBIX6HG6B/Render
TERM_PROGRAM_VERSION=361
OLDPWD=/Users/derickbailey/dev/scott-white/seabass
TERM_SESSION_ID=CB0AB4E7-4B7C-491F-8770-98B9F748AAD7
USER=derickbailey
_system_type=Darwin
rvm_path=/Users/derickbailey/.rvm
SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.iuKGW3YjeP/Listeners
TERM_SESSION_CLASS_ID=C29BE20F-D24D-4589-A2A0-8073931B8071
__CF_USER_TEXT_ENCODING=0x1F5:0x0:0x0
LSCOLORS=Dxfxcxdxbxegedabagacad
rvm_prefix=/Users/derickbailey
PATH=/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/derickbailey/.rvm/bin:./node_modules/.bin:/Users/derickbailey/.rvm/bin:/usr/local/sbin
PWD=/Users/derickbailey/dev/scott-white/seabass
EDITOR=mvim
LANG=en_US.UTF-8
NODE_PATH=./lib:.
_system_arch=x86_64
XPC_FLAGS=0x0
_system_version=10.11
GIT_PS1_SHOWUNTRACKEDFILES=true
XPC_SERVICE_NAME=0
rvm_version=1.23.14 (stable)
HOME=/Users/derickbailey
SHLVL=1
GIT_PS1_SHOWSTASHSTATE=true
LOGNAME=derickbailey
GIT_PS1_SHOWUPSTREAM=auto
OCI_INC_DIR=/opt/oracle/instantclient/sdk/include
CC=/usr/bin/gcc-4.2
OCI_LIB_DIR=/opt/oracle/instantclient
SECURITYSESSIONID=186a7
_system_name=OSX
_=/usr/bin/env
```

and here is the result of running `nodemon --exec env` on the same box, still logged in as me

```
GIT_PS1_SHOWDIRTYSTATE=true
TERM_PROGRAM=Apple_Terminal
rvm_bin_path=/Users/derickbailey/.rvm/bin
SHELL=/bin/bash
TERM=xterm-color
CLICOLOR=1
TMPDIR=/var/folders/5g/x1ddqhp94gq6m7y5qmtpw2dw0000gn/T/
Apple_PubSub_Socket_Render=/private/tmp/com.apple.launchd.RkBIX6HG6B/Render
TERM_PROGRAM_VERSION=361
TERM_SESSION_ID=CB0AB4E7-4B7C-491F-8770-98B9F748AAD7
USER=derickbailey
_system_type=Darwin
rvm_path=/Users/derickbailey/.rvm
TERM_SESSION_CLASS_ID=C29BE20F-D24D-4589-A2A0-8073931B8071
SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.iuKGW3YjeP/Listeners
__CF_USER_TEXT_ENCODING=0x1F5:0x0:0x0
LSCOLORS=Dxfxcxdxbxegedabagacad
rvm_prefix=/Users/derickbailey
PATH=/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/derickbailey/.rvm/bin:./node_modules/.bin:/Users/derickbailey/.rvm/bin:/usr/local/sbin
_=/usr/bin/env
PWD=/Users/derickbailey/dev/scott-white/seabass
EDITOR=mvim
LANG=en_US.UTF-8
NODE_PATH=./lib:.
XPC_FLAGS=0x0
_system_arch=x86_64
GIT_PS1_SHOWUNTRACKEDFILES=true
_system_version=10.11
XPC_SERVICE_NAME=0
rvm_version=1.23.14 (stable)
SHLVL=2
HOME=/Users/derickbailey
GIT_PS1_SHOWSTASHSTATE=true
LOGNAME=derickbailey
GIT_PS1_SHOWUPSTREAM=auto
CC=/usr/bin/gcc-4.2
OCI_INC_DIR=/opt/oracle/instantclient/sdk/include
OCI_LIB_DIR=/opt/oracle/instantclient
SECURITYSESSIONID=186a7
_system_name=OSX
```

other than things being not in the same order, there is a small difference.

`SHLVL=2` for the nodemon version, and the addition of `OLD_PWD` on the non-nodemon version

i'm wondering if this order change would make a difference... or if there's something else going on that i'm not seeing, that is causing my problem

**Comment by remy** [comment]
Can you run the nodemon command again, but this time run as `DEBUG=nodemon nodemon --dump agents/oracle.js` and paste the output here. 

Nodemon does its best to pass along all the environment but its clear something isn't the same here, so hopefully more detail will help.

**Comment by derickbailey** [comment]
here are the results of running that:

```
$ DEBUG=nodemon nodemon --dump agents/oracle.js
  nodemon bus new listener: reset (0) +0ms
  nodemon bus new listener: reset (0) +2ms
  nodemon bus new listener: quit (0) +9ms
  nodemon bus new listener: quit (0) +0ms
  nodemon bus new listener: restart (0) +0ms
  nodemon bus new listener: restart (0) +0ms
  nodemon bus new listener: reset (2) +4ms
  nodemon bus emit: reset +1ms
  nodemon reset +0ms
  nodemon config: dirs +122ms [ '/Users/derickbailey/dev/scott-white/seabass' ]
13 Oct 08:21:42 - [nodemon] 1.7.1
13 Oct 08:21:42 - [nodemon] to restart at any time, enter `rs`
13 Oct 08:21:42 - [nodemon] watching: *.*
--------------
node: v4.1.2
nodemon: 1.7.1
command: /usr/local/bin/node /usr/local/bin/nodemon --dump agents/oracle.js
cwd: /Users/derickbailey/dev/scott-white/seabass
OS: darwin x64
--------------
{ run: false,
  system: { cwd: '/Users/derickbailey/dev/scott-white/seabass' },
  required: false,
  dirs: [ '/Users/derickbailey/dev/scott-white/seabass' ],
  timeout: 1000,
  options: 
   { dump: true,
     ignore: 
      [ '.git',
        'node_modules',
        'bower_components',
        '.sass-cache',
        re: /\.git|node_modules|bower_components|\.sass\-cache/ ],
     watch: [ '*.*', re: /.*\..*/ ],
     ignoreRoot: [ '.git', 'node_modules', 'bower_components', '.sass-cache' ],
     restartable: 'rs',
     colours: true,
     execMap: { py: 'python', rb: 'ruby' },
     stdin: true,
     runOnChangeOnly: false,
     verbose: false,
     stdout: true,
     execOptions: 
      { script: 'agents/oracle.js',
        exec: 'node',
        args: [],
        scriptPosition: 0,
        nodeArgs: undefined,
        ext: 'js',
        env: {},
        execArgs: [] },
     monitor: 
      [ '*.*',
        '!/Users/derickbailey/dev/scott-white/seabass/.git/**/*',
        '!/Users/derickbailey/dev/scott-white/seabass/node_modules/**/*',
        '!bower_components',
        '!.sass-cache' ] },
  load: [Function],
  reset: [Function: reset],
  lastStarted: 0,
  loaded: [],
  watchInterval: null,
  command: 
   { raw: { executable: 'node', args: [ 'agents/oracle.js' ] },
     string: 'node agents/oracle.js' } }
--------------
```

**Comment by remy** [comment]
I don't think this is actually a bug, the ordering "issue" isn't an issue. It's a object so you can't rely on the order (though, I _think_ the ordering is fixed in es6, which _might_ be in node 4, but I'm not 100% sure).

nodemon is definitely *not* hijacking or changing env values.

**Comment by derickbailey** [comment]
i agree that nodemon isn't modifying the vars in any significant way...but i'm still stuck with a problem, here. i can't run the code from nodemon, making development a pain in the butt as i have to manually restart the process after every change. :(

i'd love to know what's happening, and why nodemon can't run the code

**Comment by derickbailey** [comment]
FWIW, I finally figured out what's causing this - OSX 10.11 (El Capitan) won't forward the DYLD_LIBRARY_PATH environment variable to sub / child shells... and this env var is required for the oracle node lib to work.

it's not just nodemon that has this problem... any launcher / shell tool will have this problem, including foreverjs. sucks, but there's not much i can do about this, because of the SIP security thing that El Capitan introduced.
