### ISSUE TITLE
Can't start nodemon (cannot find module 'debug')

### ISSUE THREAD

**Issue by geiszla** [remy/nodemon#678]
Nodemon worked fine, until I once closed, and when I wanted to open it showed an error:
```
D:\user\Dropbox\Programming\TunnelerOnline\TunnelerOnline>nodemon
module.js:338
    throw err;
    ^

Error: Cannot find module 'debug'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (C:\Users\user\AppData\Roaming\npm\node_modules\nod
emon\lib\nodemon.js:1:75)
    at Module._compile (module.js:430:26)
    at Object.Module._extensions..js (module.js:448:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
```

Debug is installed in the project's node_modules as well as in nodemon/node_modules. I tried everything from uninstalling and reinstalling all modules (including force install) to deleting all nodemon files I could find, but nothing seems to work. However "npm start" works perfectly.

**Comment by geiszla** [comment]
Removed everything manually and then reinstalled, now it works fine.
