### ISSUE TITLE
Tests are failing but Travis CI reports success

### ISSUE THREAD

**Issue by cbas** [remy/nodemon#680]
I'm unable to pass tests locally (OSX 10.11 & nodejs 4.1.2). Tests fail and `npm test` returns non-zero. On Travis CI, however, they also fail yet the build is reported as passing. What's going on here?

https://travis-ci.org/remy/nodemon/jobs/82140562#L467

```
test/misc/listeners.test.js
  listeners clean up
(node) warning: possible EventEmitter memory leak detected. 11 data listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at ReadStream.addListener (events.js:239:17)
    at ReadStream.Readable.on (_stream_readable.js:655:33)
    at ReadStream.Readable.pipe (_stream_readable.js:522:7)
    at Object.run (/home/travis/build/remy/nodemon/lib/monitor/run.js:231:19)
    at /home/travis/build/remy/nodemon/lib/nodemon.js:191:15
    at /home/travis/build/remy/nodemon/lib/config/index.js:79:7
    at lib$es6$promise$$internal$$tryCatch (/home/travis/build/remy/nodemon/node_modules/es6-promise/dist/es6-promise.js:326:16)
    at lib$es6$promise$$internal$$invokeCallback (/home/travis/build/remy/nodemon/node_modules/es6-promise/dist/es6-promise.js:338:17)
    at lib$es6$promise$$internal$$publish (/home/travis/build/remy/nodemon/node_modules/es6-promise/dist/es6-promise.js:309:11)
    at lib$es6$promise$asap$$flush (/home/travis/build/remy/nodemon/node_modules/es6-promise/dist/es6-promise.js:120:9)
    at doNTCallback0 (node.js:407:9)
    at process._tickCallback (node.js:336:13)
  ✓ should be able to re-run in required mode, many times, and not leaklisteners (2856ms)
  1 passing (3s)
```

**Comment by remy** [comment]
It's a warning not a failure.
