### ISSUE TITLE
Error: Cannot find module 'braces'

### ISSUE THREAD

**Issue by cleechtech** [remy/nodemon#696]
I tried to upgrade nodemon and it broke
```

┌──────────────────────────────────────────┐
│ Update available: 1.7.3 (current: 1.5.0) │
│ Run npm install -g nodemon to update.    │
└──────────────────────────────────────────┘

➜  react-jwt-starter git:(master) ✗ npm i -g nodemon
...
write-file-atomic@1.1.3 node_modules/nodemon/node_modules/update-notifier/node_modules/configstore/node_modules/write-file-atomic -> node_modules/nodemon/node_modules/write-file-atomic
xdg-basedir@2.0.0 node_modules/nodemon/node_modules/update-notifier/node_modules/configstore/node_modules/xdg-basedir -> node_modules/nodemon/node_modules/xdg-basedir
configstore@1.2.1 node_modules/nodemon/node_modules/update-notifier/node_modules/configstore -> node_modules/nodemon/node_modules/configstore
/usr/local/lib
└── (empty)

npm ERR! code 1
➜  react-jwt-starter git:(master) ✗ nodemon server  
module.js:339
    throw err;
    ^

Error: Cannot find module 'braces'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/nodemon/node_modules/chokidar/node_modules/anymatch/node_modules/micromatch/lib/glob.js:3:14)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
```

Here are the node versions I am running on OSX

```
➜  react-jwt-starter git:(master) ✗ node --version
v4.2.1
➜  react-jwt-starter git:(master) ✗ npm -v
3.3.6
```

**Comment by cleechtech** [comment]
Ewww so I ran the global install where I had a local package.json and got the error. I changed directories to where no `node_modules` existed and the global install ran fine

**Comment by cleechtech** [comment]
Closing this but can reopen if it is a problem for other peeps

**Comment by remy** [comment]
Bizarre.

**Comment by andrewjmead** [comment]
Same issue, same solution. Thanks for posting.
