### ISSUE TITLE
EACCES error on Mac for nodemon file

### ISSUE THREAD

**Issue by ORESoftware** [remy/nodemon#712]
I can run nodemon with sudo to avoid this problem

just want to see if it's something you haven't seen before

```
Error: EACCES, permission denied '/Users/amills001c/.config/configstore/update-notifier-nodemon.json'
You don't have access to this file.

    at Error (native)
    at Object.fs.openSync (fs.js:500:18)
    at Object.fs.readFileSync (fs.js:352:15)
    at Object.create.all.get (/usr/local/lib/node_modules/nodemon/node_modules/update-notifier/node_modules/configstore/index.js:34:26)
    at Object.Configstore (/usr/local/lib/node_modules/nodemon/node_modules/update-notifier/node_modules/configstore/index.js:27:44)
    at new UpdateNotifier (/usr/local/lib/node_modules/nodemon/node_modules/update-notifier/index.js:34:17)
    at module.exports (/usr/local/lib/node_modules/nodemon/node_modules/update-notifier/index.js:123:23)
    at Object.<anonymous> (/usr/local/lib/node_modules/nodemon/bin/nodemon.js:15:27)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
```

**Comment by gmontalvoriv** [comment]
This appears to be an npm problem when installing packages globally. You should check the [fixing npm permissions](https://docs.npmjs.com/getting-started/fixing-npm-permissions) section on their site.

**Comment by ORESoftware** [comment]
thanks I will investigate appreciate the feedback

**Comment by ctaorminainn** [comment]
After going through option 2 on the [fixing npm permissions section](https://docs.npmjs.com/getting-started/fixing-npm-permissions) and reinstalling nodemon, I still receive this error. Is there any other way to deal with this?

**Comment by ORESoftware** [comment]
the way I have been dealing with it is to use nodemon with Gulp, via the
gulp-nodemon plugin

otherwise I am still having the issue as the person above

**Comment by ctaorminainn** [comment]
I was just able to get around the issue by changing the ownership on the file manually using the following

 sudo chown youruseraccount:admin pathtocontainingfolder/.config/configstore/update-notifier-nodemon.json

**Comment by meghanadasigi** [comment]
It is an ownership problem. Try running the command with 'sudo'.

**Comment by saadaouad** [comment]
@meghanadasigi :+1:

**Comment by tottran** [comment]
Thank you @meghanadasigi

**Comment by abs1010** [comment]
sudo npm install -g nodemon

this one worked for me
