### ISSUE TITLE
Nodemon not restarting

### ISSUE THREAD

**Issue by StevenDStanton** [remy/nodemon#717]
I have nodemon working on another server

I just started up a new node 4.2.0 server and am making changes to the code base.

However, when I upload a files nodemon is not reloading the server

In the log below I waited until I recieved the app crash and tried to reupload the file with fixes and nothing happened. I have to either type in rs or close and restart nodemon

root@callcenterwest:/var/www# npm remove -g nodemon
unbuild nodemon@1.8.0
root@callcenterwest:/var/www# npm install -g nodemon
npm WARN optional dep failed, continuing fsevents@1.0.2
/usr/local/bin/nodemon -> /usr/local/lib/node_modules/nodemon/bin/nodemon.js
nodemon@1.8.0 /usr/local/lib/node_modules/nodemon
├── undefsafe@0.0.3
├── es6-promise@3.0.2
├── debug@2.2.0 (ms@0.7.1)
├── minimatch@3.0.0 (brace-expansion@1.1.1)
├── touch@1.0.0 (nopt@1.0.10)
├── lodash.defaults@3.1.2 (lodash.restparam@3.6.1, lodash.assign@3.2.0)
├── ps-tree@1.0.1 (event-stream@3.3.2)
├── chokidar@1.2.0 (arrify@1.0.0, path-is-absolute@1.0.0, glob-parent@2.0.0, async-each@0.1.6, is-binary-path@1.0.1, is-glob@2.0.1, lodash.flatten@3.0.2, readdirp@2.0.0, anymatch@1.3.0)
└── update-notifier@0.5.0 (is-npm@1.0.0, string-length@1.0.1, chalk@1.1.1, repeating@1.1.3, semver-diff@2.0.0, configstore@1.3.0, latest-version@1.0.1)
root@callcenterwest:/var/www# nodemon bin/www
[nodemon] 1.8.0
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node bin/www`
error connecting: Error: Handshake inactivity timeout
    at Handshake.<anonymous> (/var/www/node_modules/mysql/lib/protocol/Protocol.js:154:17)
    at emitNone (events.js:67:13)
    at Handshake.emit (events.js:166:7)
    at Handshake._onTimeout (/var/www/node_modules/mysql/lib/protocol/sequences/Sequence.js:116:8)
    at Timer.listOnTimeout (timers.js:92:15)
    --------------------
    at Protocol._enqueue (/var/www/node_modules/mysql/lib/protocol/Protocol.js:135:48)
    at Protocol.handshake (/var/www/node_modules/mysql/lib/protocol/Protocol.js:52:41)
    at Connection.connect (/var/www/node_modules/mysql/lib/Connection.js:123:18)
    at Object.<anonymous> (/var/www/routes/index.js:124:12)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/var/www/app.js:12:14)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
[ [ { RegisterSubCategoryDescription: 'Water' } ],
  returnValue: 0 ]

/var/www/node_modules/mongoose/lib/index.js:333
      throw new mongoose.Error.MissingSchemaError(name);
      ^
MissingSchemaError: Schema hasn't been registered for model "v3communication".
Use mongoose.model(name, schema)
    at Mongoose.model (/var/www/node_modules/mongoose/lib/index.js:333:13)
    at null._repeat (/var/www/routes/index.js:51:14)
    at wrapper [as _onTimeout] (timers.js:264:19)
    at Timer.listOnTimeout (timers.js:92:15)
[nodemon] app crashed - waiting for file changes before starting...
^Croot@callcenterwest:/var/www#

**Comment by madbence** [comment]
see #711

**Comment by StevenDStanton** [comment]
As a work around for now I just moved back to Node 1.4.1 

For anyone who is not familiar with how to do that just...

npm remove -g nodemon
npm install -g nodemon@1.4.1

**Comment by remy** [comment]
Can you try nodemon@1.8.1 (just released).

**Comment by StevenDStanton** [comment]
Node 1.8.1 resolved the issue
