### ISSUE TITLE
doesn't escape arguments correctly

### ISSUE THREAD

**Issue by kevinawoo** [remy/nodemon#729]
I'm trying to run 
```bash
$ NODE_ENV=test nodemon -x 'mocha' -- --ui bdd --timeout 10000 'modules/**/__tests__/*-test.js' -b --grep='/(sub|charge)/i'
```

but it gives me an error
```
[nodemon] 1.8.1
[nodemon] reading config /Users/kevin/repos/repo/nodemon.json
[nodemon] to restart at any time, enter `rs`
[nodemon] ignoring: /Users/kevin/repos/repo/.git/**/* /Users/kevin/repos/repo/node_modules/**/* bower_components .sass-cache /Users/kevin/repos/repo/coverage/**/* /Users/kevin/repos/repo/node_modules/**/* /Users/kevin/repos/repo/.git/**/* /Users/kevin/repos/repo/.idea/**/* npm-debug.json /Users/kevin/repos/repo/tmp/**/* /Users/kevin/repos/repo/apidoc/**/*
[nodemon] watching: /Users/kevin/repos/repo/modules/**/* /Users/kevin/repos/repo/db/**/* /Users/kevin/repos/repo/config/**/* /Users/kevin/repos/repo/scripts/**/* apidoc_template/**/* /Users/kevin/repos/repo/work/**/* /Users/kevin/repos/repo/.bin/**/* nodemon.json .eslintrc
[nodemon] watching extensions: json,js,sql,html
[nodemon] starting `mocha --ui bdd --timeout 10000 modules/**/__tests__/*-test.js -b --grep=/(sub|charge)/i`
[nodemon] child pid: 41504
sh: -c: line 0: syntax error near unexpected token `('
sh: -c: line 0: `mocha --ui bdd --timeout 10000 modules/**/__tests__/*-test.js -b --grep=/(sub|charge)/i'
[nodemon] failed to start process, possible issue with exec arguments
[nodemon] exiting
events.js:146
      throw err;
            ^
Error: Uncaught, unspecified "error" event. (2)
    at emit (events.js:144:17)
    at ChildProcess.<anonymous> (/Users/kevin/.nvm/versions/io.js/v2.5.0/lib/node_modules/nodemon/lib/monitor/run.js:124:11)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
```

**Comment by kevinawoo** [comment]
escaping `--grep=/(sub|charge)/i` to `--grep='/\(sub|charge\)/i'` works.
