### ISSUE TITLE
I use the nodemon in window when recent,it's can't work!!!!(My mac is work,the node version is v5.1.0)

### ISSUE THREAD

**Issue by strongwray** [remy/nodemon#737]
>nodemon app.js
[nodemon] 1.8.1
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node app.js`
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: spawn cmd ENOENT
    at exports._errnoException (util.js:856:11)
    at Process.ChildProcess._handle.onexit (int
    at onErrorNT (internal/child_process.js:344
    at doNTCallback2 (node.js:452:9)
    at process._tickCallback (node.js:366:17)

**Comment by OmgImAlexis** [comment]
It's not clear what you're asking in the issue title. Can you elaborate a bit?

**Comment by strongwray** [comment]
$ nodemon app.js
15 Sep 20:51:36 - [nodemon] v1.8.1
15 Sep 20:51:36 - [nodemon] to restart at any time, enter `rs`
15 Sep 20:51:36 - [nodemon] watching: *.*
15 Sep 20:51:36 - [nodemon] starting `node app.js`
DGE db opened
GET / 304 626.838 ms - -

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:1001:11)
    at Process.ChildProcess._handle.onexit (child_process.js:792:34)
15 Sep 20:51:45 - [nodemon] app crashed - waiting for file changes before starting...

I start the server in the window7, it's has the problem.

**Comment by OmgImAlexis** [comment]
Again... It's not clear what you're asking in the issue title or the description. Can you elaborate a bit?
