### ISSUE TITLE
exception in nodemon killing node

### ISSUE THREAD

**Issue by Jakobud** [remy/nodemon#741]
Node 5.1.1

Just installed nodemon and I get this:

```
# nodemon --help
exception in nodemon killing node
Error: Cannot find module 'configstore'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/nodemon/node_modules/update-notifier/index.js:4:19)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)

----------------------------------------------------------
If appropriate, please file an error with the output from:
$ /usr/local/bin/node /usr/local/bin/nodemon --help --dump
At http://github.com/remy/nodemon/issues/new
----------------------------------------------------------
```

Any clues? When I try to do the `--dump` command above I get the same error without any other output.

**Comment by remy** [comment]
Looks like it didn't install correctly. Configstore is part of update-notifier, one of the few deps. Try again?

**Comment by Jakobud** [comment]
Weird. Worked this time. Thanks,

**Comment by suissa** [comment]
For me dont install correctly, only show:

```
...
npm WARN install:object-assign ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/nodemon/node_modules/got/node_modules/object-assign' -> '/usr/local/lib/node_modules/nodemon/node_modules/got/node_modules/object-assign'
npm WARN install:minimist ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/nodemon/node_modules/rc/node_modules/minimist' -> '/usr/local/lib/node_modules/nodemon/node_modules/rc/node_modules/minimist'
npm WARN install:minimatch ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/nodemon/node_modules/readdirp/node_modules/minimatch' -> '/usr/local/lib/node_modules/nodemon/node_modules/readdirp/node_modules/minimatch'
object-assign@3.0.0 node_modules/nodemon/node_modules/got/node_modules/object-assign -> node_modules/nodemon/node_modules/got/node_modules/object-assign
minimist@1.2.0 node_modules/nodemon/node_modules/rc/node_modules/minimist -> node_modules/nodemon/node_modules/rc/node_modules/minimist
minimatch@2.0.10 node_modules/nodemon/node_modules/readdirp/node_modules/minimatch -> node_modules/nodemon/node_modules/readdirp/node_modules/minimatch
registry-url@3.0.3 node_modules/nodemon/node_modules/update-notifier/node_modules/latest-version/node_modules/package-json/node_modules/registry-url -> node_modules/nodemon/node_modules/registry-url
read-all-stream@3.0.1 node_modules/nodemon/node_modules/update-notifier/node_modules/latest-version/node_modules/package-json/node_modules/got/node_modules/read-all-stream -> node_modules/nodemon/node_modules/read-all-stream
string-length@1.0.1 node_modules/nodemon/node_modules/update-notifier/node_modules/string-length -> node_modules/nodemon/node_modules/string-length
end-of-stream@1.0.0 node_modules/nodemon/node_modules/update-notifier/node_modules/latest-version/node_modules/package-json/node_modules/got/node_modules/duplexify/node_modules/end-of-stream -> node_modules/nodemon/node_modules/end-of-stream
duplexify@3.4.2 node_modules/nodemon/node_modules/update-notifier/node_modules/latest-version/node_modules/package-json/node_modules/got/node_modules/duplexify -> node_modules/nodemon/node_modules/duplexify
got@3.3.1 node_modules/nodemon/node_modules/update-notifier/node_modules/latest-version/node_modules/package-json/node_modules/got -> node_modules/nodemon/node_modules/got
package-json@1.2.0 node_modules/nodemon/node_modules/update-notifier/node_modules/latest-version/node_modules/package-json -> node_modules/nodemon/node_modules/package-json
latest-version@1.0.1 node_modules/nodemon/node_modules/update-notifier/node_modules/latest-version -> node_modules/nodemon/node_modules/latest-version
- readdirp node_modules/nodemon/node_modules/readdirp
/usr/local/lib
└── (empty)

npm ERR! code 1
```
