### ISSUE TITLE
Error: Cannot find module 'got'

### ISSUE THREAD

**Issue by dcsan** [remy/nodemon#753]
I get this error `Error: Cannot find module 'got'` on running nodemon -v
so the install seems totally borked.
I have nodemon installed locally in my project.

but, running it with 

`./node_modules/nodemon/bin/nodemon.js`

seems to work fine.
is there a way to force it to run the local install to the project?

I did uninstall and reinstall the --global version but it still seems borken. be nice to know what the reason for that might be. there is no `nodemon.debug` created.

```
nodemon -v
exception in nodemon killing node
Error: Cannot find module 'got'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/nodemon/node_modules/update-notifier/node_modules/latest-version/node_modules/package-json/index.js:2:11)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
```

**Comment by atom0s** [comment]
Had this problem too after upgrading to the latest Node.js 5.x install. 
Simple uninstall / reinstall got things going again for me though:

    npm uninstall -g nodemon
    npm install -g nodemon

**Comment by bapinney** [comment]
I am _**SO**_ glad I found this thread.  I started recently getting this problem and could not figure out why--especially given that I did not make any recent changes to my config/etc.

I just wanted to say that I had the same issue as dcsan and that atom0s' solution fixed the problem.

**Comment by remy** [comment]
Should this be moved into the FAQ? 

That said, all modules should be re-installed when you move from node 4 to 5 since any compiled deps might be shot through (I presume `got` is a deep dependency).

**Comment by atom0s** [comment]
@remy sounds good to me. Makes sense to need a rebuild/reinstall of things between a major release ie. v4.x.x -> v5.x.x

**Comment by iposton** [comment]
Thanks @atom0s. The unintsall then install nodemon worked for me. I recently upgraded to node 5.5 happy to have nodemon back and working as it should.
