### ISSUE TITLE
Cannot find module micromatch

### ISSUE THREAD

**Issue by chrislewispac** [remy/nodemon#793]
nodemon app.js
module.js:338
    throw err;
    ^

Error: Cannot find module 'micromatch'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/nodemon/node_modules/chokidar/node_modules/anymatch/index.js:4:18)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)

**Comment by remy** [comment]
What version of npm are you using? It might lead to a clue.

**Comment by Sequoia** [comment]
NPM 3.3.6 here. Looks like something is explicitly requiring `./node_modules/...` perhaps?

```
$ npm i -g nodemon
npm WARN install:object-assign ENOENT: no such file or directory, rename '/Users/sequoia/.npm-packages/lib/node_modules/nodemon/node_modules/got/node_modules/object-assign' -> '/Users/sequoia/.npm-packages/lib/node_modules/nodemon/node_modules/got/node_modules/object-assign'
npm WARN install:minimist ENOENT: no such file or directory, rename '/Users/sequoia/.npm-packages/lib/node_modules/nodemon/node_modules/rc/node_modules/minimist' -> '/Users/sequoia/.npm-packages/lib/node_modules/nodemon/node_modules/rc/node_modules/minimist'
npm WARN install:minimatch ENOENT: no such file or directory, rename '/Users/sequoia/.npm-packages/lib/node_modules/nodemon/node_modules/readdirp/node_modules/minimatch' -> '/Users/sequoia/.npm-packages/lib/node_modules/nodemon/node_modules/readdirp/node_modules/minimatch'
object-assign@3.0.0 node_modules/nodemon/node_modules/got/node_modules/object-assign -> node_modules/nodemon/node_modules/got/node_modules/object-assign
minimist@1.2.0 node_modules/nodemon/node_modules/rc/node_modules/minimist -> node_modules/nodemon/node_modules/rc/node_modules/minimist
minimatch@2.0.10 node_modules/nodemon/node_modules/readdirp/node_modules/minimatch -> node_modules/nodemon/node_modules/readdirp/node_modules/minimatch
registry-url@3.0.3 node_modules/nodemon/node_modules/update-notifier/node_modules/latest-version/node_modules/package-json/node_modules/registry-url -> node_modules/nodemon/node_modules/registry-url
string-length@1.0.1 node_modules/nodemon/node_modules/update-notifier/node_modules/string-length -> node_modules/nodemon/node_modules/string-length
got@3.3.1 node_modules/nodemon/node_modules/update-notifier/node_modules/latest-version/node_modules/package-json/node_modules/got -> node_modules/nodemon/node_modules/got
package-json@1.2.0 node_modules/nodemon/node_modules/update-notifier/node_modules/latest-version/node_modules/package-json -> node_modules/nodemon/node_modules/package-json
latest-version@1.0.1 node_modules/nodemon/node_modules/update-notifier/node_modules/latest-version -> node_modules/nodemon/node_modules/latest-version
- /Users/sequoia/.npm-packages/lib/node_modules/nodemon/node_modules/readdirp node_modules/nodemon/node_modules/readdirp
/Users/sequoia/.npm-packages/lib
└── (empty)

npm ERR! code 1
```

**Comment by Sequoia** [comment]
installed it this way & I couldn't reproduce the issue... it installed fine 
`npm i -g --verbose nodemon`
¯\_(ツ)_/¯

**Comment by chrislewispac** [comment]
npm 3.3.12 (I use nvm)

**Comment by Sequoia** [comment]
I use NVM as well.

**Comment by shikloshi** [comment]
Happens to me as well since upgrading to 1.9
