### ISSUE TITLE
Nodemon doesn't kill child process when receiving SIGTERM

### ISSUE THREAD

**Issue by aalexgabi** [remy/nodemon#882]
Nodemon doesn't kill the child process when receiving SIGTERM but it does when receiving SIGINT.

```
$ nodemon -v
1.9.2
```

**Comment by aalexgabi** [comment]
Probably #34 is related.

**Comment by reesmanp** [comment]
```
$ nodemon -v
1.12.0
```
Nodemon kills the child process on `rs` and on SIGINT. However when it restarts due to file changes, it does not kill the child process.

```
[nodemon] 1.12.0
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node server.js`
*****
MAIL SERVER
11:43:22 | 08 Sep 2017
localhost:1025
*****
*****
SERVER
11:43:22 | 08 Sep 2017
http://local:3000
*****
rs
[nodemon] starting `node server.js`
*****
MAIL SERVER
11:43:31 | 08 Sep 2017
localhost:1025
*****
*****
SERVER
11:43:31 | 08 Sep 2017
http://local:3000
*****
[nodemon] restarting due to changes...
[nodemon] starting `node server.js`
events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::1025
    at Object.exports._errnoException (util.js:1026:11)
    at exports._exceptionWithHostPort (util.js:1049:20)
    at Server.setupListenHandle [as _listen2] (net.js:1305:14)
    at listenInCluster (net.js:1353:12)
    at Server.listen (net.js:1453:7)
    at SMTPServer.listen (node_modules/smtp-server/lib/smtp-server.js:98:21)
    at MailServer.run (mailServer.js:37:8)
    at Object.<anonymous> (server.js:23:23)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
[nodemon] app crashed - waiting for file changes before starting...
^C
```

**Comment by reesmanp** [comment]
@remy bump

**Comment by remy** [comment]
@reesmanp can you try with nodemon@1.12.6 - the spawn code has been refactored and _might_ solve this problem.

**Comment by remy** [comment]
edit: can you try with nodemon@latest (currently 1.12.7)

**Comment by reesmanp** [comment]
@remy The most recent version does fix this. It restarts properly of `rs` and on file change. Thanks.

**Comment by remy** [comment]
👍

**Comment by zakiAzfar** [comment]
it is not solved
