### ISSUE TITLE
Can I specify -e flag (which extensions to watch) from the config file?  

### ISSUE THREAD

**Issue by light24bulbs** [remy/nodemon#924]
Didn't see this in the docs.  I feel like the nodemon.json sample should have every possible option so we can see them.

I feel like it might work like 

``` json
"watch_extensions": ["jade","ruby"]
```

**Comment by light24bulbs** [comment]
I found this in the code which looks like all the config options and their defaults
```js
  restartable: 'rs',
  colours: true,
  execMap: {
    py: 'python',
    rb: 'ruby',
    // more can be added here such as ls: lsc - but please ensure it's cross
    // compatible with linux, mac and windows, or make the default.js
    // dynamically append the `.cmd` for node based utilities
  },
  ignoreRoot: ignoreRoot,
  watch: ['*.*'],
  stdin: true,
  runOnChangeOnly: false,
  verbose: false,
  // 'stdout' refers to the default behaviour of a required nodemon's child,
  // but also includes stderr. If this is false, data is still dispatched via
  // nodemon.on('stdout/stderr')
  stdout: true,
```

I tried using watch like 
```json
"watch": ["*.coffee", "*.jade", "*.scss"]
```
but that didn't do it

**Comment by remy** [comment]
(bit late - sorry), but yes, use `"ext": ["jade","ruby"]` in your config (same as the CLI usage).

**Comment by crapthings** [comment]
```
nodemon index.js
/Users/monsterstep/.nvm/versions/node/v10.15.0/lib/node_modules/nodemon/lib/config/exec.js:205
  extension = (extension.match(/[^,*\s]+/g) || [])
                         ^

TypeError: extension.match is not a function
    at exec (/Users/monsterstep/.nvm/versions/node/v10.15.0/lib/node_modules/nodemon/lib/config/exec.js:205:26)
    at mutateExecOptions (/Users/monsterstep/.nvm/versions/node/v10.15.0/lib/node_modules/nodemon/lib/config/load.js:236:25)
    at /Users/monsterstep/.nvm/versions/node/v10.15.0/lib/node_modules/nodemon/lib/config/load.js:86:7
    at callback (/Users/monsterstep/.nvm/versions/node/v10.15.0/lib/node_modules/nodemon/lib/config/load.js:177:5)
    at /Users/monsterstep/.nvm/versions/node/v10.15.0/lib/node_modules/nodemon/lib/config/load.js:217:5
    at FSReqWrap.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:53:3)
```

nodemon.json

```json
{
  "ext": ["conf"]
}
```
