### ISSUE TITLE
Not supporting comments in nodemon.json configuration file.

### ISSUE THREAD

**Issue by vajahath** [remy/nodemon#926]
Nodemon is an awesome tool. Please fix this.

The below nodemon.json file
```javascript
/**
 * nodemon config file.
 */
{
	"ignore": [
		"public/**/*",
		"README"
	]
}
```
produce an error like this:
```
nodemon start
SyntaxError: Unexpected token / in JSON at position 0
    at Object.parse (native)
    at /usr/lib/node_modules/nodemon/lib/config/load.js:180:23
    at tryToString (fs.js:455:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:442:12)
[nodemon] Failed to parse config /home/vaju/Documents/Drasperry/oofme/oofme-app/nodemon.json

```
Add support for comments in the nodemon.json file.

**Comment by remy** [comment]
The file, as per the extension, is JSON. JSON does not support comments.

**Comment by Abhishek5991** [comment]
Thanks remy it really worked

**Comment by Kali-Jones** [comment]
Thanks Remy it has also helped me
