### ISSUE TITLE
nodemon es7

### ISSUE THREAD

**Issue by mkhanal** [remy/nodemon#942]
npm : 3.10.8
node : v7.0.0

```
$ nodemon app.js
exception in nodemon killing node
Error: Cannot find module 'internal/fs'
    at Function.Module._resolveFilename (module.js:472:15)
    at Function.Module._load (module.js:420:25)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at evalmachine.<anonymous>:17:20
    at Object.<anonymous> (/usr/local/lib/node_modules/nodemon/node_modules/update-notifier/node_modules/configstore/node_modules/graceful-fs/fs.js:11:1)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
```

Cannot produce dump, I get the same issue when i use any nodemon command/options

### app.js
```js
require('babel-register')({ presets: ['es2015', 'stage-0'] });
require('babel-polyfill');
require('./server.js');
```

**Comment by mkhanal** [comment]
Turns out that this was because of some issue with my installation. Now that I've done a clean reinstall of nodemon, i run into 
```
export new Router();
^^^^^^
SyntaxError: Unexpected token export
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:545:28)
```

Does this mean nodemon is not be able to compile and run with inline 'babel require hooks'

**Comment by mkhanal** [comment]
Nevermind

This was possibly because of issues in one of the packages I was using. I deleted my node modules and installed packages again, and its working fine now.
