### ISSUE TITLE
connection is reset when rs

### ISSUE THREAD

**Issue by mmclau14** [remy/nodemon#975]
looks like the connection is being reset when i do an rs, but nothing is being logged out.
```
> nodemon ./bin/www --ignore public/ --ignore node_modules/

[nodemon] 1.11.0
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node ./bin/www`
rs
^C
michaelmclaughlin@test-624:~/cloud-compiler/editor$ events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at exports._errnoException (util.js:1022:11)
    at Pipe.onread (net.js:572:26)
npm run dev

> editor@0.0.0 dev /home/michaelmclaughlin/cloud-compiler/editor
> nodemon ./bin/www --ignore public/ --ignore node_modules/

```

**Comment by GongT** [comment]
#397
