### ISSUE TITLE
Nodemon is thworing err on startup

### ISSUE THREAD

**Issue by animeshsinghweb** [remy/nodemon#992]
Nodemon throwing err on startup
```
$ nodemon start
[nodemon] 1.11.0
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node start app.js`
module.js:471
    throw err;
    ^

Error: Cannot find module 'C:\Users\animeshweb\Desktop\projects\eb-v2\start'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
[nodemon] app crashed - waiting for file changes before starting...
rs
[nodemon] starting `node start app.js`
module.js:471
    throw err;
    ^

Error: Cannot find module 'C:\Users\animeshweb\Desktop\projects\eb-v2\start'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
[nodemon] app crashed - waiting for file changes before starting...

$ nodemon -v
1.11.0

```

**Comment by remy** [comment]
Nodemon doesn't replace npm. Drop the `start` in your command and it'll run.

**Comment by animeshsinghweb** [comment]
Actually I was able to use this `nodemon start` and it was working, but don't know why it got stuck since few hours.
